// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Publiparking.Core.Data.SqlServer.Entities
{
    public partial class anagrafica_ruolo_mansione
    {
        public anagrafica_ruolo_mansione()
        {
            anagrafica_risorse = new HashSet<anagrafica_risorse>();
        }

        [Key]
        public int id_ruolo_mansione { get; set; }
        [Required]
        [StringLength(6)]
        public string cod_ruolo_mansione { get; set; }
        [Required]
        [StringLength(50)]
        public string descr_ruolo_mansione { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? data_inizio { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? data_fine { get; set; }
        [Required]
        [StringLength(1)]
        public string flag_on_off { get; set; }
        public int cod_ger { get; set; }

        [InverseProperty("id_ruolo_mansioneNavigation")]
        public virtual ICollection<anagrafica_risorse> anagrafica_risorse { get; set; }
    }
}