// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Publiparking.Core.Data.SqlServer.Entities
{
    /// <summary>
    /// Tabella dele province italiane
    /// </summary>
    public partial class ser_province
    {
        public ser_province()
        {
            anagrafica_ente = new HashSet<anagrafica_ente>();
            ser_comuni = new HashSet<ser_comuni>();
        }

        [Key]
        public int cod_provincia { get; set; }
        [Required]
        [StringLength(50)]
        public string des_provincia { get; set; }
        [Required]
        [StringLength(2)]
        public string sig_provincia { get; set; }
        public int cod_regione { get; set; }
        [Required]
        [StringLength(6)]
        public string cod_istat { get; set; }
        public int f_provincia_sto { get; set; }

        [ForeignKey(nameof(cod_regione))]
        [InverseProperty(nameof(ser_regioni.ser_province))]
        public virtual ser_regioni cod_regioneNavigation { get; set; }
        [InverseProperty("cod_provinciaNavigation")]
        public virtual ICollection<anagrafica_ente> anagrafica_ente { get; set; }
        [InverseProperty("cod_provinciaNavigation")]
        public virtual ICollection<ser_comuni> ser_comuni { get; set; }
    }
}