// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Publiparking.Core.Data.SqlServer.Entities
{
    public partial class tab_tassonomia_pagopa
    {
        [Key]
        public int Id_tassonomia { get; set; }
        public int? Id_tipo_ente { get; set; }
        public int? Id_entrata { get; set; }
        [StringLength(15)]
        public string Codice_tassonomia_pagopa { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Data_inizio_validita { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Data_fine_validita { get; set; }
        [StringLength(1)]
        public string flag_on_off { get; set; }
    }
}