// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Publiparking.Core.Data.SqlServer.Entities
{
    public partial class tab_utenti
    {
        [Key]
        public int id_utente { get; set; }
        [Required]
        [StringLength(100)]
        public string nome_utente { get; set; }
        [Required]
        [StringLength(50)]
        public string password_utente { get; set; }
        [StringLength(16)]
        public string codice_fiscale { get; set; }
        [StringLength(100)]
        public string nome { get; set; }
        [StringLength(100)]
        public string cognome { get; set; }
        [StringLength(100)]
        public string ragione_sociale { get; set; }
        [Required]
        [StringLength(1)]
        public string tipo_utente { get; set; }
        [StringLength(100)]
        public string email { get; set; }
        [StringLength(50)]
        public string nazionalita { get; set; }
        [StringLength(8)]
        public string pref_mobile { get; set; }
        [StringLength(14)]
        public string telefono_mobile { get; set; }
        [StringLength(8)]
        public string pref_fisso { get; set; }
        [StringLength(14)]
        public string telefono_fisso { get; set; }
        [StringLength(11)]
        public string p_iva { get; set; }
        public int? livello_autorizzazione_esterno { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        [Required]
        [StringLength(7)]
        public string cod_stato { get; set; }
        [Required]
        [StringLength(1)]
        public string flag_on_off { get; set; }
        public bool flag_utente_attivo { get; set; }
        public bool flag_password_sistema { get; set; }
        public int? id_ente_riconoscimento { get; set; }
        public int? codice_contribuente_riconoscimento { get; set; }
        [Column(TypeName = "decimal(10, 0)")]
        public decimal? id_contribuente_riconoscimento { get; set; }
        public int? id_domanda_segreta { get; set; }
        public string risposta_domanda_segreta { get; set; }
        [StringLength(50)]
        public string codice_reset_password { get; set; }
        [StringLength(100)]
        public string email_spid { get; set; }
        [StringLength(100)]
        public string telefono_mobile_spid { get; set; }
        [StringLength(100)]
        public string codice_spid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? data_ultima_verifica_email_spid { get; set; }
    }
}