// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Publiparking.Core.Data.SqlServer.Entities
{
    public partial class tab_idpspid
    {
        [Key]
        public int id_tab_idpspid { get; set; }
        [StringLength(100)]
        public string EntityId { get; set; }
        [StringLength(100)]
        public string OrganizationName { get; set; }
        [StringLength(100)]
        public string OrganizationDisplayName { get; set; }
        [StringLength(100)]
        public string OrganizationUrl { get; set; }
        [StringLength(100)]
        public string SingleSignOnServiceUrl { get; set; }
        [StringLength(100)]
        public string SingleLogoutServiceUrl { get; set; }
        [StringLength(100)]
        public string SubjectNameIdRemoveText { get; set; }
        [StringLength(50)]
        public string DateTimeFormat { get; set; }
        public double? NowDelta { get; set; }
        public string logo { get; set; }
        public string Description { get; set; }
        [StringLength(1)]
        public string ambiente { get; set; }
        [StringLength(1)]
        public string flag_on_off { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? data_stato { get; set; }
        public string certificate { get; set; }
        public string url_metadata { get; set; }
    }
}