// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Publiparking.Core.Data.SqlServer.Entities
{
    public partial class tab_toponimi
    {
        [Key]
        public int id_toponimo { get; set; }
        public int id_tipo_toponimo { get; set; }
        public int cod_comune_toponimo { get; set; }
        [Required]
        [StringLength(5)]
        public string cap_toponimo { get; set; }
        [StringLength(10)]
        public string cod_toponimo { get; set; }
        [Required]
        [StringLength(100)]
        public string descrizione_toponimo { get; set; }
        [Required]
        [StringLength(100)]
        public string desc_toponimo { get; set; }
        [StringLength(50)]
        public string frazione_toponimo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime data_inizio_val_toponimo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime data_fine_val_toponimo { get; set; }
        [Required]
        [StringLength(1)]
        public string flag_val_toponimo { get; set; }
        [StringLength(50)]
        public string cod_fonte { get; set; }
        public int? id_stato { get; set; }
        [StringLength(7)]
        public string cod_stato { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? data_stato { get; set; }
        public int? id_struttura_stato { get; set; }
        public int? id_risorsa_stato { get; set; }
        [Required]
        [StringLength(1)]
        public string flag_on_off { get; set; }
        public int? id_strada_db_postale { get; set; }
        public int? id_toponimo_ente { get; set; }
    }
}