// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Publiparking.Core.Data.SqlServer.Entities
{
    public partial class tab_cc_riscossione
    {
        [Key]
        public int id_tab_cc_riscossione { get; set; }
        public int? id_ente { get; set; }
        [StringLength(1)]
        public string flag_tipo_cc { get; set; }
        [StringLength(100)]
        public string intestazione_cc { get; set; }
        [StringLength(100)]
        public string intestazione_cc1_bollettino { get; set; }
        [StringLength(40)]
        public string intestazione_cc2_bollettino { get; set; }
        [StringLength(10)]
        public string ABI_CC { get; set; }
        [StringLength(10)]
        public string CAB_CC { get; set; }
        [StringLength(20)]
        public string num_cc { get; set; }
        [StringLength(100)]
        public string aut_cc { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? data_apertura_cc { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? data_chiusura_cc { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? periodo_contabilizzazione_a { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? data_ultima_contabilizzazione { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? periodo_rendicontazione_a { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? data_ultima_rendicontazione { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? periodo_rettifica_rendicontazione_a { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? data_ultima_rettifica_rendicontazione { get; set; }
        [StringLength(2)]
        public string periodicita_rendicontazione { get; set; }
        public int? giorni_scadenza_rendicontazione { get; set; }
        [StringLength(1)]
        public string tipo_riversamento { get; set; }
        public int? COD_COMUNE { get; set; }
        [StringLength(38)]
        public string DES_COMUNE { get; set; }
        [StringLength(1)]
        public string flag_on_off { get; set; }
        [StringLength(30)]
        public string IBAN { get; set; }
        [StringLength(1)]
        public string flag_registro { get; set; }
        [StringLength(1)]
        public string flag_recupero_spese_riscossione { get; set; }
        [Column(TypeName = "decimal(18, 4)")]
        public decimal? perc_recupero_spese_riscossione { get; set; }
        [StringLength(2)]
        public string periodicita_rettifica_rendicontazione { get; set; }
        public int? giorni_scadenza_rettifica_rendicontazione { get; set; }
        [StringLength(12)]
        public string NUMERO_CONTO_CONTABILE_CC_RISCOSSIONE { get; set; }
        [StringLength(12)]
        public string NUMERO_CONTO_CONTABILE_SPESE_RISCOSSIONE { get; set; }
        [Column(TypeName = "decimal(18, 4)")]
        public decimal? perc_rimborso { get; set; }
        [StringLength(1)]
        public string Flag_riversamenti_anticipati { get; set; }
        public int? id_contratto { get; set; }
        [StringLength(1)]
        public string Flag_tipo_rendicontazione { get; set; }
        public int? id_entrata { get; set; }
        [StringLength(20)]
        public string num_cc_new { get; set; }
        public int? id_anagrafica_abi_cab { get; set; }
        public int? id_tipo_servizio { get; set; }
        [StringLength(1)]
        public string Flag_modalita_pagamento_standard { get; set; }
        [StringLength(2)]
        public string periodicita_esportazione_pagamenti { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? periodo_rif_a_ultima_esportazione_pagamenti { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? periodo_rif_a_ultima_esportazione_detris { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? periodo_rif_a_ultimo_consuntivo_detris { get; set; }
        [StringLength(11)]
        public string bic_swift { get; set; }
        [StringLength(100)]
        public string aut_cc_pagopa { get; set; }
    }
}