//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publiparking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abbonamenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abbonamenti()
        {
            this.Cellulari = new HashSet<Cellulari>();
        }
    
        public int idAbbonamento { get; set; }
        public string codice { get; set; }
        public Nullable<int> idRivenditore { get; set; }
        public Nullable<System.DateTime> dataStampa { get; set; }
        public Nullable<System.DateTime> dataConsegna { get; set; }
        public Nullable<System.DateTime> dataAbilitazione { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cellulari> Cellulari { get; set; }
    }
}
