//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publiparking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configurazione
    {
        public decimal giorniScadenzaPassword { get; set; }
        public string modalitaPagamento { get; set; }
        public int frequenzaFoto { get; set; }
        public int bloccoInattivitaTotem { get; set; }
        public bool bloccoVerbali { get; set; }
        public string versioneMinimaTerminali { get; set; }
        public bool integrazioneDB { get; set; }
        public bool pagamentoConTarga { get; set; }
        public bool emissioneTitoliOperatore { get; set; }
        public string CodParcometroOP { get; set; }
        public int idTipoVerbaleSostaScaduta { get; set; }
        public bool penali { get; set; }
        public decimal percentualeRiduzioneVerbale { get; set; }
        public string testoAbbonamento { get; set; }
        public Nullable<int> idPDMPyng { get; set; }
        public string codiceOperatorePyng { get; set; }
        public string passwordPyng { get; set; }
        public Nullable<int> giorniTolleranzaPenale { get; set; }
        public Nullable<int> idTipoOggetto { get; set; }
        public Nullable<int> idEntrata { get; set; }
        public Nullable<int> giorniScadenzaAvvPag { get; set; }
        public string secondaSerie { get; set; }
        public string primaSerie { get; set; }
        public Nullable<int> idAnagraficaCategoriaDefault { get; set; }
        public Nullable<int> idStruttura { get; set; }
        public string contoCorrenteSecondaSerie { get; set; }
        public string fonte { get; set; }
        public Nullable<int> idEnte { get; set; }
        public Nullable<int> idTipoLista { get; set; }
        public Nullable<int> idTipoAvvPagSenzaVerbale { get; set; }
        public Nullable<int> idTipoAvvPagPenaleConVerbale { get; set; }
        public Nullable<int> idTipoAvvPag { get; set; }
        public Nullable<int> idTrasgressoreAssenteCausale { get; set; }
        public string numSmsModemTelecom { get; set; }
        public string userSmsModemTelecom { get; set; }
        public string pwdSmsModemTelecom { get; set; }
        public Nullable<int> idPDMPhonzie { get; set; }
        public string codiceOperatorePhonzie { get; set; }
        public string passwordPhonzie { get; set; }
        public int idConfigurazione { get; set; }
        public string numeroMittente { get; set; }
        public string msg_scadenza_rinnovo { get; set; }
        public string msg_scadenza_pass { get; set; }
        public Nullable<int> msg_scadenza_numgiorni { get; set; }
        public Nullable<int> msg_scadenza_pass_numgiorni { get; set; }
    }
}
