//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publiparking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StalliFrequenzaFoto
    {
        public int idStallo { get; set; }
        public int oraInizio { get; set; }
        public int oraFine { get; set; }
        public int frequenzaFoto { get; set; }
    
        public virtual Stalli Stalli { get; set; }
    }
}
