//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publiparking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_toponimi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tab_toponimi()
        {
            this.Stalli = new HashSet<Stalli>();
        }
    
        public int id_toponimo { get; set; }
        public int id_tipo_toponimo { get; set; }
        public int cod_comune_toponimo { get; set; }
        public string cap_toponimo { get; set; }
        public string cod_toponimo { get; set; }
        public string descrizione_toponimo { get; set; }
        public string desc_toponimo { get; set; }
        public string frazione_toponimo { get; set; }
        public System.DateTime data_inizio_val_toponimo { get; set; }
        public System.DateTime data_fine_val_toponimo { get; set; }
        public string flag_val_toponimo { get; set; }
        public string cod_fonte { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public Nullable<System.DateTime> data_stato { get; set; }
        public Nullable<int> id_struttura_stato { get; set; }
        public Nullable<int> id_risorsa_stato { get; set; }
        public string flag_on_off { get; set; }
        public Nullable<int> id_strada_db_postale { get; set; }
        public Nullable<int> id_toponimo_ente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stalli> Stalli { get; set; }
    }
}
