//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publiparking.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitoliSMSTarga
    {
        public int idTitoloSMSTarga { get; set; }
        public int idCellulare { get; set; }
        public string codice { get; set; }
        public Nullable<int> idStallo { get; set; }
        public string codice_titolo { get; set; }
        public System.DateTime dataPagamento { get; set; }
        public System.DateTime scadenza { get; set; }
        public decimal importo { get; set; }
    
        public virtual Cellulari Cellulari { get; set; }
        public virtual Stalli Stalli { get; set; }
    }
}
