//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class anagrafica_pagopa_intermediari
    {
        public anagrafica_pagopa_intermediari()
        {
            this.anagrafica_pagopa_stazioni = new HashSet<anagrafica_pagopa_stazioni>();
        }
    
        public int id_intermediario { get; set; }
        public string cod_intermediario { get; set; }
        public string cod_connettore_pdd { get; set; }
        public string cod_connettore_ftp { get; set; }
        public string denominazione { get; set; }
        public int id_ente { get; set; }
    
        ///<summary><para>Relazione: fk_intermediario</para> Chiave Origine: id_intermediario</summary>
     public virtual ICollection<anagrafica_pagopa_stazioni> anagrafica_pagopa_stazioni { get; set; }
        ///<summary><para>Relazione: fk_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
    }
}
