//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class anagrafica_cod_stato_base
    {
        public anagrafica_cod_stato_base()
        {
            this.anagrafica_tipo_relazione = new HashSet<anagrafica_tipo_relazione>();
            this.join_ente_strutture = new HashSet<join_ente_strutture>();
            this.join_risorse_strutture = new HashSet<join_risorse_strutture>();
            this.tab_pianificazione_cicli = new HashSet<tab_pianificazione_cicli>();
            this.tab_pianificazione_cicli_dettaglio = new HashSet<tab_pianificazione_cicli_dettaglio>();
            this.tab_esecuzione_applicazioni = new HashSet<tab_esecuzione_applicazioni>();
            this.join_controlli_avvpag_fatt_emissione = new HashSet<join_controlli_avvpag_fatt_emissione>();
            this.anagrafica_controlli_qualita_emissione_avvpag = new HashSet<anagrafica_controlli_qualita_emissione_avvpag>();
            this.tab_avvisi_anomali_liste_carico = new HashSet<tab_avvisi_anomali_liste_carico>();
            this.tab_controlli_qualita_liste_carico = new HashSet<tab_controlli_qualita_liste_carico>();
            this.join_referente_contribuente = new HashSet<join_referente_contribuente>();
            this.tab_referente = new HashSet<tab_referente>();
            this.tab_utenti = new HashSet<tab_utenti>();
        }
    
        public int id_anagrafica_cod_stato_base { get; set; }
        public string cod_stato { get; set; }
        public string descrizione { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
    
        ///<summary><para>Relazione: FK_anagrafica_tipo_relazione_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato</summary>
     public virtual ICollection<anagrafica_tipo_relazione> anagrafica_tipo_relazione { get; set; }
        ///<summary><para>Relazione: FK_join_ente_strutture_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato</summary>
     public virtual ICollection<join_ente_strutture> join_ente_strutture { get; set; }
        ///<summary><para>Relazione: FK_join_risorse_strutture_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato</summary>
     public virtual ICollection<join_risorse_strutture> join_risorse_strutture { get; set; }
        ///<summary><para>Relazione: FK_tab_pianificazione_cicli_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato</summary>
     public virtual ICollection<tab_pianificazione_cicli> tab_pianificazione_cicli { get; set; }
        ///<summary><para>Relazione: FK_tab_pianificazione_cicli_dettaglio_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato</summary>
     public virtual ICollection<tab_pianificazione_cicli_dettaglio> tab_pianificazione_cicli_dettaglio { get; set; }
        ///<summary><para>Relazione: FK_tab_esecuzione_applicazioni_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato</summary>
     public virtual ICollection<tab_esecuzione_applicazioni> tab_esecuzione_applicazioni { get; set; }
        ///<summary><para>Relazione: FK_join_controlli_avvpag_fatt_emissione_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato</summary>
     public virtual ICollection<join_controlli_avvpag_fatt_emissione> join_controlli_avvpag_fatt_emissione { get; set; }
        ///<summary><para>Relazione: FK_anagrafica_controlli_qualita_emissione_avvpag_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato</summary>
     public virtual ICollection<anagrafica_controlli_qualita_emissione_avvpag> anagrafica_controlli_qualita_emissione_avvpag { get; set; }
        ///<summary><para>Relazione: FK_tab_avvisi_anomali_liste_carico_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato_avv_pag_fatt_emissione</summary>
     public virtual ICollection<tab_avvisi_anomali_liste_carico> tab_avvisi_anomali_liste_carico { get; set; }
        ///<summary><para>Relazione: FK_tab_controlli_qualita_liste_carico_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato</summary>
     public virtual ICollection<tab_controlli_qualita_liste_carico> tab_controlli_qualita_liste_carico { get; set; }
        ///<summary><para>Relazione: FK_join_referente_contribuente_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato</summary>
     public virtual ICollection<join_referente_contribuente> join_referente_contribuente { get; set; }
        ///<summary><para>Relazione: FK_tab_referente_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato</summary>
     public virtual ICollection<tab_referente> tab_referente { get; set; }
        ///<summary><para>Relazione: FK_tab_login_utente_anagrafica_cod_stato_base1</para> Chiave Origine: cod_stato</summary>
     public virtual ICollection<tab_utenti> tab_utenti { get; set; }
    }
}
