//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class anagrafica_stato_avv_pag
    {
        public anagrafica_stato_avv_pag()
        {
            this.tab_avv_pag_fatt_rettifica = new HashSet<tab_avv_pag_fatt_rettifica>();
            this.tab_avv_pag_fatt_emissione = new HashSet<tab_avv_pag_fatt_emissione>();
            this.tab_avv_pag_fatt_emissione1 = new HashSet<tab_avv_pag_fatt_emissione>();
            this.tab_avv_pag_stato = new HashSet<tab_avv_pag>();
            this.tab_avv_pag_stato_avv_pag = new HashSet<tab_avv_pag>();
        }
    
        public int id_anagrafica_stato { get; set; }
        public string cod_stato { get; set; }
        public string desc_stato { get; set; }
        public int flag_istanza_ricorso { get; set; }
        public string trasc_sicra { get; set; }
        public string trasc_altro { get; set; }
        public string flag_visualizzabile { get; set; }
        public string flag_validita { get; set; }
        public string cod_stato_riferimento { get; set; }
        public string desc_stato_riferimento { get; set; }
        public int priorita_visualizzazione { get; set; }
    
        ///<summary><para>Relazione: FK_tab_avv_pag_fatt_rettifica_anagrafica_stato_avv_pag</para> Chiave Origine: id_stato_avv_pag</summary>
     public virtual ICollection<tab_avv_pag_fatt_rettifica> tab_avv_pag_fatt_rettifica { get; set; }
        ///<summary><para>Relazione: FK_tab_avv_pag_fatt_emissione_anagrafica_stato_avv_pag</para> Chiave Origine: id_stato_avv_pag</summary>
     public virtual ICollection<tab_avv_pag_fatt_emissione> tab_avv_pag_fatt_emissione { get; set; }
        ///<summary><para>Relazione: FK_tab_avv_pag_fatt_emissione_anagrafica_stato_avv_pag1</para> Chiave Origine: id_stato</summary>
     public virtual ICollection<tab_avv_pag_fatt_emissione> tab_avv_pag_fatt_emissione1 { get; set; }
        ///<summary><para>Relazione: FK_tab_avv_pag_anagrafica_stato</para> Chiave Origine: id_stato</summary>
     public virtual ICollection<tab_avv_pag> tab_avv_pag_stato { get; set; }
        ///<summary><para>Relazione: FK_tab_avv_pag_anagrafica_stato_avv_pag</para> Chiave Origine: id_stato_avv_pag</summary>
     public virtual ICollection<tab_avv_pag> tab_avv_pag_stato_avv_pag { get; set; }
    }
}
