//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class anagrafica_veicoli_marche
    {
        public anagrafica_veicoli_marche()
        {
            this.anagrafica_veicoli_tipo_serie = new HashSet<anagrafica_veicoli_tipo_serie>();
        }
    
        public int id_marca { get; set; }
        public string descrizione { get; set; }
    
        ///<summary><para>Relazione: FK_anagrafica_veicoli_tipo_serie_anagrafica_veicoli_marche</para> Chiave Origine: id_marca</summary>
     public virtual ICollection<anagrafica_veicoli_tipo_serie> anagrafica_veicoli_tipo_serie { get; set; }
    }
}
