//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class anagrafica_controlli_qualita_emissione_avvpag
    {
        public anagrafica_controlli_qualita_emissione_avvpag()
        {
            this.join_controlli_avvpag_fatt_emissione = new HashSet<join_controlli_avvpag_fatt_emissione>();
            this.tab_controlli_qualita_liste_carico = new HashSet<tab_controlli_qualita_liste_carico>();
            this.tab_avvisi_anomali_liste_carico = new HashSet<tab_avvisi_anomali_liste_carico>();
            this.tab_anomalie_spedizioni = new HashSet<tab_anomalie_spedizioni>();
        }
    
        public int id_anagrafica_controllo { get; set; }
        public string descrizione_controllo { get; set; }
        public int id_ente { get; set; }
        public int id_entrata { get; set; }
        public int id_tipo_lista { get; set; }
        public Nullable<int> id_tipo_servizio { get; set; }
        public string codice_controllo { get; set; }
        public Nullable<bool> flag_avvpag_composto { get; set; }
        public string tipo_record_controllo { get; set; }
        public string modalita_esecuzione { get; set; }
        public int ordine_visualizzazione { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public string flag_controllo_filtro { get; set; }
        public string codice_errore { get; set; }
        public string descrizione_errore { get; set; }
        public string tipo_errore { get; set; }
    
        ///<summary><para>Relazione: FK_anagrafica_controlli_qualita_emissione_avvpag_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato</summary>
     public virtual anagrafica_cod_stato_base anagrafica_cod_stato_base { get; set; }
        ///<summary><para>Relazione: FK_anagrafica_controlli_qualita_emissione_avvpag_anagrafica_entrate</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate { get; set; }
        ///<summary><para>Relazione: FK_anagrafica_controlli_qualita_emissione_avvpag_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_anagrafica_controlli_qualita_emissione_avvpag_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_anagrafica_controlli_qualita_emissione_avvpag_anagrafica_tipo_servizi</para> Chiave Origine: id_tipo_servizio</summary>
     public virtual anagrafica_tipo_servizi anagrafica_tipo_servizi { get; set; }
        ///<summary><para>Relazione: FK_anagrafica_controlli_qualita_emissione_avvpag_tab_tipo_lista</para> Chiave Origine: id_tipo_lista</summary>
     public virtual tab_tipo_lista tab_tipo_lista { get; set; }
        ///<summary><para>Relazione: FK_join_controlli_avvpag_fatt_emissione_anagrafica_controlli_qualita_emissione_avvpag</para> Chiave Origine: id_anagrafica_controllo</summary>
     public virtual ICollection<join_controlli_avvpag_fatt_emissione> join_controlli_avvpag_fatt_emissione { get; set; }
        ///<summary><para>Relazione: FK_tab_controlli_qualita_liste_carico_anagrafica_controlli_qualita_emissione_avvpag</para> Chiave Origine: id_anagrafica_controllo</summary>
     public virtual ICollection<tab_controlli_qualita_liste_carico> tab_controlli_qualita_liste_carico { get; set; }
        ///<summary><para>Relazione: FK_tab_avvisi_anomali_liste_carico_anagrafica_controlli_qualita_emissione_avvpag</para> Chiave Origine: id_anagrafica_controllo</summary>
     public virtual ICollection<tab_avvisi_anomali_liste_carico> tab_avvisi_anomali_liste_carico { get; set; }
        ///<summary><para>Relazione: FK_tab_anomalie_spedizioni_anagrafica_controlli_qualita_emissione_avvpag</para> Chiave Origine: id_anagrafica_controllo</summary>
     public virtual ICollection<tab_anomalie_spedizioni> tab_anomalie_spedizioni { get; set; }
        ///<summary><para>Relazione: FK_anagrafica_controlli_qualita_emissione_avvpag_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
    }
}
