//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class anagrafica_cicli_dettaglio
    {
        public anagrafica_cicli_dettaglio()
        {
            this.tab_cicli_ente_dettaglio = new HashSet<tab_cicli_ente_dettaglio>();
        }
    
        public int id_ciclo_dettaglio { get; set; }
        public int id_ciclo { get; set; }
        public int id_tab_applicazioni { get; set; }
        public int sequenza { get; set; }
        public System.DateTime data_creazione { get; set; }
    
        ///<summary><para>Relazione: FK_anagrafica_cicli_dettaglio_anagrafica_cicli</para> Chiave Origine: id_ciclo</summary>
     public virtual anagrafica_cicli anagrafica_cicli { get; set; }
        ///<summary><para>Relazione: FK_tab_cicli_ente_dettaglio_anagrafica_cicli_dettaglio</para> Chiave Origine: id_ciclo_dettaglio</summary>
     public virtual ICollection<tab_cicli_ente_dettaglio> tab_cicli_ente_dettaglio { get; set; }
        ///<summary><para>Relazione: FK_anagrafica_cicli_dettaglio_tab_applicazioni</para> Chiave Origine: id_tab_applicazioni</summary>
     public virtual tab_applicazioni tab_applicazioni { get; set; }
    }
}
