//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class anagrafica_ente_codici
    {
        public int id_ente_codici { get; set; }
        public int id_ente { get; set; }
        public string codice_ente { get; set; }
        public Nullable<int> id_ente_riv { get; set; }
    
        ///<summary><para>Relazione: FK_anagrafica_ente_codici_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
    }
}
