//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class anagrafica_utilizzo
    {
        public anagrafica_utilizzo()
        {
            this.tab_categoria_tariffaria_ici = new HashSet<tab_categoria_tariffaria_ici>();
            this.tab_categoria_tariffaria_immobili = new HashSet<tab_categoria_tariffaria_immobili>();
            this.tab_categoria_tariffaria_imu = new HashSet<tab_categoria_tariffaria_imu>();
            this.tab_categoria_tariffaria_tasi = new HashSet<tab_categoria_tariffaria_tasi>();
            this.tab_categorie_fabbricati = new HashSet<tab_categorie_fabbricati>();
            this.tab_categorie_fabbricati1 = new HashSet<tab_categorie_fabbricati>();
            this.tab_oggetti_contribuzione = new HashSet<tab_oggetti_contribuzione>();
            this.tab_qualita_terreno = new HashSet<tab_qualita_terreno>();
            this.tab_qualita_terreno1 = new HashSet<tab_qualita_terreno>();
        }
    
        public int id_utilizzo { get; set; }
        public int id_entrata { get; set; }
        public string des_utilizzo { get; set; }
        public string flag_occupazione { get; set; }
        public string flag_proprieta { get; set; }
        public Nullable<int> id_ente { get; set; }
        public string flag_tipo_pubblicita { get; set; }
        public string codice { get; set; }
    
        ///<summary><para>Relazione: FK_anagrafica_utilizzo_tab_macroentrate</para> Chiave Origine: id_entrata</summary>
     public virtual tab_macroentrate tab_macroentrate { get; set; }
        ///<summary><para>Relazione: FK_tab_categoria_tariffaria_ici_anagrafica_utilizzo</para> Chiave Origine: id_utilizzo</summary>
     public virtual ICollection<tab_categoria_tariffaria_ici> tab_categoria_tariffaria_ici { get; set; }
        ///<summary><para>Relazione: FK_tab_categoria_tariffaria_immobili_anagrafica_utilizzo</para> Chiave Origine: id_utilizzo</summary>
     public virtual ICollection<tab_categoria_tariffaria_immobili> tab_categoria_tariffaria_immobili { get; set; }
        ///<summary><para>Relazione: FK_tab_categoria_tariffaria_imu_anagrafica_utilizzo</para> Chiave Origine: id_utilizzo</summary>
     public virtual ICollection<tab_categoria_tariffaria_imu> tab_categoria_tariffaria_imu { get; set; }
        ///<summary><para>Relazione: FK_tab_categoria_tariffaria_tasi_anagrafica_utilizzo</para> Chiave Origine: id_utilizzo</summary>
     public virtual ICollection<tab_categoria_tariffaria_tasi> tab_categoria_tariffaria_tasi { get; set; }
        ///<summary><para>Relazione: FK_tab_categorie_fabbricati_anagrafica_utilizzo</para> Chiave Origine: id_utilizzo_ici</summary>
     public virtual ICollection<tab_categorie_fabbricati> tab_categorie_fabbricati { get; set; }
        ///<summary><para>Relazione: FK_tab_categorie_fabbricati_anagrafica_utilizzo1</para> Chiave Origine: id_utilizzo_imu</summary>
     public virtual ICollection<tab_categorie_fabbricati> tab_categorie_fabbricati1 { get; set; }
        ///<summary><para>Relazione: FK_tab_oggetti_contribuzione_anagrafica_utilizzo</para> Chiave Origine: id_utilizzo</summary>
     public virtual ICollection<tab_oggetti_contribuzione> tab_oggetti_contribuzione { get; set; }
        ///<summary><para>Relazione: FK_tab_qualita_terreno_anagrafica_utilizzo_ici</para> Chiave Origine: id_utilizzo_ente_ici</summary>
     public virtual ICollection<tab_qualita_terreno> tab_qualita_terreno { get; set; }
        ///<summary><para>Relazione: FK_tab_qualita_terreno_anagrafica_utilizzo_imu</para> Chiave Origine: id_utilizzo_ente_imu</summary>
     public virtual ICollection<tab_qualita_terreno> tab_qualita_terreno1 { get; set; }
        ///<summary><para>Relazione: FK_anagrafica_utilizzo_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
    }
}
