//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class anagrafica_stato_riga_avv_pag
    {
        public int id_anagrafica_stato { get; set; }
        public string cod_stato { get; set; }
        public string desc_stato { get; set; }
        public string flag_on_off { get; set; }
    }
}
