//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_doc_input_pag_avvpag
    {
        public join_doc_input_pag_avvpag()
        {
            this.join_documenti_pratiche = new HashSet<join_documenti_pratiche>();
        }
    
        public int id_join_doc_input_pag_avvpag { get; set; }
        public int id_join_avv_pag_doc_input { get; set; }
        public int id_causale_istanza { get; set; }
        public string note_causale { get; set; }
        public Nullable<int> id_tab_mov_pag { get; set; }
        public Nullable<int> id_tab_cc_riscossione { get; set; }
        public string num_cc_dichiarato_istanza { get; set; }
        public Nullable<int> id_tipo_pagamento { get; set; }
        public string tipo_cc_pagamento { get; set; }
        public Nullable<int> id_cuas { get; set; }
        public string uff_postale { get; set; }
        public Nullable<System.DateTime> data_operazione_pagamento { get; set; }
        public Nullable<System.DateTime> data_accredito_pagamento { get; set; }
        public Nullable<System.DateTime> data_valuta_pagamento { get; set; }
        public Nullable<decimal> importo_mov_pagato { get; set; }
        public string code_line_pagamento { get; set; }
        public string tipo_boll_pagamento { get; set; }
        public string cognome_rag_soc_pagante { get; set; }
        public string nome_pagante { get; set; }
        public string indirizzo_pagante { get; set; }
        public string nr_civico_pagante { get; set; }
        public string cap_pagante { get; set; }
        public string localita_pagante { get; set; }
        public string codice_fiscale_pagante { get; set; }
        public string note_pagamento { get; set; }
        public Nullable<decimal> imp_mov_da_imputare_avvpag { get; set; }
        public int id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public string iban_beneficiario_bonifico { get; set; }
        public string nominativo_rag_soc_beneficiario { get; set; }
        public string codice_fiscale_piva_beneficiario { get; set; }
        public Nullable<System.DateTime> data_nascita_beneficiario { get; set; }
        public string comune_nascita_beneficiario { get; set; }
        public string stato_nascita_benficiario { get; set; }
        public string indirizzo_residenza_beneficiario { get; set; }
        public string comune_residenza_benficiario { get; set; }
        public string sigla_provincia_residenza_beneficiario { get; set; }
        public string stato_residenza_beneficiario { get; set; }
        public Nullable<decimal> importo_rimborso { get; set; }
        public string flag_beneficiario_rimborso { get; set; }
        public Nullable<decimal> id_contribuente_destinatario { get; set; }
        public Nullable<int> id_referente_destinatario { get; set; }
        public Nullable<int> id_terzo_destinatario { get; set; }
    
        ///<summary><para>Relazione: FK_join_doc_input_pag_avvpag_anagrafica_causale</para> Chiave Origine: id_causale_istanza</summary>
     public virtual anagrafica_causale anagrafica_causale { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_pag_avvpag_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_pag_avvpag_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_pag_avvpag_anagrafica_tipo_pagamento</para> Chiave Origine: id_tipo_pagamento</summary>
     public virtual anagrafica_tipo_pagamento anagrafica_tipo_pagamento { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_pag_avvpag_join_tab_avv_pag_tab_doc_input</para> Chiave Origine: id_join_avv_pag_doc_input</summary>
     public virtual join_tab_avv_pag_tab_doc_input join_tab_avv_pag_tab_doc_input { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_pag_avvpag_tab_cc_riscossione</para> Chiave Origine: id_tab_cc_riscossione</summary>
     public virtual tab_cc_riscossione tab_cc_riscossione { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_pag_avvpag_tab_contribuente</para> Chiave Origine: id_contribuente_destinatario</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_pag_avvpag_tab_cuas</para> Chiave Origine: id_cuas</summary>
     public virtual tab_cuas tab_cuas { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_pag_avvpag_tab_referente</para> Chiave Origine: id_referente_destinatario</summary>
     public virtual tab_referente tab_referente { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_pag_avvpag_tab_terzo</para> Chiave Origine: id_terzo_destinatario</summary>
     public virtual tab_terzo tab_terzo { get; set; }
        ///<summary><para>Relazione: FK_join_documenti_pratiche_join_doc_input_pag_avvpag</para> Chiave Origine: id_join_doc_input_pag_avvpag</summary>
     public virtual ICollection<join_documenti_pratiche> join_documenti_pratiche { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_pag_avvpag_tab_mov_pag</para> Chiave Origine: id_tab_mov_pag</summary>
     public virtual tab_mov_pag tab_mov_pag { get; set; }
    }
}
