//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_terzo_referente
    {
        public int id_join_terzo_referente { get; set; }
        public int id_terzo { get; set; }
        public int id_referente { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public string cod_stato { get; set; }
        public int id_tipo_relazione { get; set; }
    
        ///<summary><para>Relazione: FK_join_terzo_referente_tab_referente</para> Chiave Origine: id_referente</summary>
     public virtual tab_referente tab_referente { get; set; }
        ///<summary><para>Relazione: FK_join_terzo_referente_tab_terzo</para> Chiave Origine: id_terzo</summary>
     public virtual tab_terzo tab_terzo { get; set; }
        ///<summary><para>Relazione: FK_join_terzo_referente_anagrafica_tipo_relazione</para> Chiave Origine: id_tipo_relazione</summary>
     public virtual anagrafica_tipo_relazione anagrafica_tipo_relazione { get; set; }
    }
}
