//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_contenitori_join_file
    {
        public int id_join_contenitori_join_file { get; set; }
        public int id_tab_contenitori { get; set; }
        public int id_join_file { get; set; }
        public int id_operatore { get; set; }
    
        ///<summary><para>Relazione: FK_join_contenitori_join_file_anagrafica_risorse</para> Chiave Origine: id_operatore</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_join_contenitori_join_file_join_file</para> Chiave Origine: id_join_file</summary>
     public virtual join_file join_file { get; set; }
        ///<summary><para>Relazione: FK_join_contenitori_join_file_tab_contenitori</para> Chiave Origine: id_tab_contenitori</summary>
     public virtual tab_contenitori tab_contenitori { get; set; }
    }
}
