//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_causale_doc_new
    {
        public int id_join_causale_doc { get; set; }
        public Nullable<int> id_funzione { get; set; }
        public Nullable<int> id_tipo_doc_entrate { get; set; }
        public Nullable<int> id_causale { get; set; }
        public string flag_trattamento { get; set; }
        public Nullable<int> id_tipo_avv_pag { get; set; }
        public string flag_join { get; set; }
        public string codice_stato_iniziale { get; set; }
        public string flag_esclusione { get; set; }
        public string flag_tipo_operazione { get; set; }
        public string codice_stato_finale_doc_new { get; set; }
        public string codice_stato_finale_doc_old { get; set; }
        public Nullable<decimal> importo_causale { get; set; }
    
        ///<summary><para>Relazione: FK_join_causale_doc_anagrafica_causale</para> Chiave Origine: id_causale</summary>
     public virtual anagrafica_causale anagrafica_causale { get; set; }
        ///<summary><para>Relazione: FK_join_causale_doc_anagrafica_tipo_avv_pag</para> Chiave Origine: id_tipo_avv_pag</summary>
     public virtual anagrafica_tipo_avv_pag anagrafica_tipo_avv_pag { get; set; }
        ///<summary><para>Relazione: FK_join_causale_doc_tab_funzioni</para> Chiave Origine: id_funzione</summary>
     public virtual tab_funzioni tab_funzioni { get; set; }
        ///<summary><para>Relazione: FK_join_causale_doc_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrate</summary>
     public virtual tab_tipo_doc_entrate tab_tipo_doc_entrate { get; set; }
    }
}
