//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_lst_emissione_lst_sped_not
    {
        public int id_join_lst_emissione_lst_sped_not { get; set; }
        public int id_lista_emissione { get; set; }
        public int id_lista_sped_not { get; set; }
    
        ///<summary><para>Relazione: FK_join_lst_emissione_lst_sped_not_tab_lista_sped_notifiche1</para> Chiave Origine: id_lista_sped_not</summary>
     public virtual tab_lista_sped_notifiche tab_lista_sped_notifiche { get; set; }
        ///<summary><para>Relazione: FK_join_lst_emissione_lst_sped_not_tab_liste1</para> Chiave Origine: id_lista_emissione</summary>
     public virtual tab_liste tab_liste { get; set; }
    }
}
