//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_documenti_pratiche_richiesti
    {
        public int id_join_documenti_richiesti { get; set; }
        public int id_ente { get; set; }
        public int id_ente_gestito { get; set; }
        public int id_entrata { get; set; }
        public int id_tipo_doc_entrata { get; set; }
        public int id_categoria_contribuzione { get; set; }
        public Nullable<int> id_causale { get; set; }
        public int id_anagrafica_documento { get; set; }
        public string flag_obbligatorieta { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public string flag_on_off { get; set; }
    
        ///<summary><para>Relazione: FK_join_documenti_pratiche_richiesti_anagrafica_categoria</para> Chiave Origine: id_categoria_contribuzione</summary>
     public virtual anagrafica_categoria anagrafica_categoria { get; set; }
        ///<summary><para>Relazione: FK_join_documenti_pratiche_richiesti_anagrafica_causale</para> Chiave Origine: id_causale</summary>
     public virtual anagrafica_causale anagrafica_causale { get; set; }
        ///<summary><para>Relazione: FK_join_documenti_pratiche_richiesti_anagrafica_documenti</para> Chiave Origine: id_anagrafica_documento</summary>
     public virtual anagrafica_documenti anagrafica_documenti { get; set; }
        ///<summary><para>Relazione: FK_join_documenti_pratiche_richiesti_anagrafica_ente_gestito</para> Chiave Origine: id_ente_gestito</summary>
     public virtual anagrafica_ente_gestito anagrafica_ente_gestito { get; set; }
        ///<summary><para>Relazione: FK_join_documenti_pratiche_richiesti_anagrafica_entrate</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate { get; set; }
        ///<summary><para>Relazione: FK_join_documenti_pratiche_richiesti_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_join_documenti_pratiche_richiesti_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_join_documenti_pratiche_richiesti_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
    }
}
