//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_tab_avv_pag_tab_doc_input
    {
        public join_tab_avv_pag_tab_doc_input()
        {
            this.join_doc_input_beni_avvpag = new HashSet<join_doc_input_beni_avvpag>();
            this.join_doc_input_not_avvpag = new HashSet<join_doc_input_not_avvpag>();
            this.join_doc_input_riga_avvpag = new HashSet<join_doc_input_riga_avvpag>();
            this.join_documenti_pratiche = new HashSet<join_documenti_pratiche>();
            this.join_tab_avv_pag_tab_doc_input1 = new HashSet<join_tab_avv_pag_tab_doc_input>();
            this.tab_agevolazioni_verifica = new HashSet<tab_agevolazioni_verifica>();
            this.tab_rimborsi = new HashSet<tab_rimborsi>();
            this.tab_vincoli_beni_pignorati = new HashSet<tab_vincoli_beni_pignorati>();
            this.join_doc_input_pag_avvpag = new HashSet<join_doc_input_pag_avvpag>();
        }
    
        public int id_join_avv_pag_doc_input { get; set; }
        public int id_tab_doc_input { get; set; }
        public Nullable<int> id_avv_pag { get; set; }
        public Nullable<int> id_avv_pag_collegato { get; set; }
        public Nullable<int> id_causale { get; set; }
        public Nullable<decimal> importo_pagato { get; set; }
        public string nominativo_pagante { get; set; }
        public string cod_fisc_pagante { get; set; }
        public Nullable<int> id_tipo_pagamento { get; set; }
        public string cc_pagamento { get; set; }
        public Nullable<System.DateTime> data_pagamento { get; set; }
        public Nullable<decimal> importo_da_rateizzare { get; set; }
        public Nullable<int> id_rateizzazione { get; set; }
        public Nullable<int> num_rate_concesse { get; set; }
        public Nullable<System.DateTime> data_scadenza_1_rata_richiesta { get; set; }
        public Nullable<decimal> importo_da_rimborsare { get; set; }
        public Nullable<decimal> importo_totale_cartella { get; set; }
        public Nullable<decimal> importo_cartella_da_sgravare { get; set; }
        public string num_cartella { get; set; }
        public string anno_riferimento_cartella { get; set; }
        public Nullable<int> id_tipo_tributo_cartella { get; set; }
        public string descrizione_tributo_cartella { get; set; }
        public string annotazioni_acquisizione { get; set; }
        public string estremi_pagamento { get; set; }
        public Nullable<int> id_sped_not { get; set; }
        public Nullable<int> id_tipo_delegato { get; set; }
        public string nominativo_delegato { get; set; }
        public string cod_fisc_delegato { get; set; }
        public Nullable<int> id_tipo_documento_delegato { get; set; }
        public string num_documento_delegato { get; set; }
        public Nullable<System.DateTime> data_rilascio_documento_delegato { get; set; }
        public Nullable<int> id_ente_rilascio_documento_riconoscimento { get; set; }
        public string flag_esito_storico { get; set; }
        public string flag_esito_pre_1_rettifica { get; set; }
        public string flag_esito { get; set; }
        public Nullable<int> id_causale_esito { get; set; }
        public Nullable<System.DateTime> data_esito { get; set; }
        public string annotazioni_esito { get; set; }
        public int id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public Nullable<int> id_tab_avv_pag_fatt_emissione { get; set; }
        public string cognome_rag_soc_debitore { get; set; }
        public string nome_debitore { get; set; }
        public string cod_fis_piva_debitore { get; set; }
        public string nominativo_procuratore_terzo { get; set; }
        public string codice_fiscale_procuratore_terzo { get; set; }
        public string descrizione_procura_terzo { get; set; }
        public Nullable<int> dichiarazione_terzo_somme_disponibili { get; set; }
        public Nullable<System.DateTime> dichiarazione_terzo_data_disponibilita { get; set; }
        public Nullable<int> num_rate_avv_pag_fatt_emissione { get; set; }
        public Nullable<decimal> tot_da_rateizzare_fatt_emissione { get; set; }
        public Nullable<decimal> imp_prima_rata_fatt_emissione { get; set; }
        public Nullable<decimal> imp_rate_successive_fatt_emissione { get; set; }
        public Nullable<int> periodicita_rate { get; set; }
        public Nullable<decimal> importo_reddito_valprod_dichiarato { get; set; }
        public Nullable<System.DateTime> data_controllo { get; set; }
        public Nullable<int> id_addetto_lavorazione { get; set; }
        public Nullable<int> id_addetto_controllo { get; set; }
        public Nullable<System.DateTime> data_inizio_lav { get; set; }
        public Nullable<System.DateTime> data_fine_lav { get; set; }
        public string provvedimento_esito_approvazione { get; set; }
        public string pec_procuratore { get; set; }
        public string email_procuratore { get; set; }
        public string riferimento_pratica_terzo { get; set; }
        public Nullable<int> id_tipo_bene { get; set; }
        public Nullable<decimal> importo_dichiarato_anno { get; set; }
        public Nullable<decimal> importo_dichiarato_mensile { get; set; }
        public Nullable<decimal> importo_dichiarato_tfr { get; set; }
        public Nullable<decimal> importo_dichiarato_titoli { get; set; }
        public Nullable<int> numero_intestazioni_titoli { get; set; }
        public Nullable<decimal> importo_totale_vincolato { get; set; }
        public Nullable<System.DateTime> data_decorrenza_disponibilita_dichiarato { get; set; }
        public Nullable<decimal> somme_accantonate { get; set; }
        public Nullable<decimal> percentuale_copertura_totale_crediti { get; set; }
        public Nullable<System.DateTime> data_scadenza_disponibilita_dichiarato { get; set; }
        public Nullable<System.DateTime> data_decorrenza_disponibilita_tfr { get; set; }
        public Nullable<decimal> importo_dichiarato_redditi_una_tantum { get; set; }
        public Nullable<System.DateTime> data_decorrenza_disponibilita_dichiarato_redditi_una_tantum { get; set; }
        public Nullable<decimal> percentuale_proprieta_immobile_locazione { get; set; }
        public Nullable<decimal> importo_dichiarato_cc_depositi { get; set; }
        public Nullable<System.DateTime> data_decorrenza_disponibilita_cc_depositi { get; set; }
        public Nullable<int> numero_intestazioni_cc_depositi { get; set; }
        public Nullable<System.DateTime> data_decorrenza_disponibilita_titoli { get; set; }
        public Nullable<decimal> totale_complessivo_dichiarato { get; set; }
        public Nullable<System.DateTime> data_scadenza_importo_vincolato { get; set; }
        public Nullable<decimal> totale_pignorabile_mensile { get; set; }
        public Nullable<decimal> totale_pignorabile_una_tantum { get; set; }
        public Nullable<decimal> totale_complessivo_pignorabile { get; set; }
        public Nullable<int> numero_mesi_pignorabili { get; set; }
        public string annotazioni_esito_lavorazione { get; set; }
        public Nullable<int> id_stato_lavorazione { get; set; }
        public string cod_stato_lavorazione { get; set; }
        public Nullable<int> id_join_avv_pag_doc_input_collegata { get; set; }
        public Nullable<int> id_join_fattcont_fattconsumi { get; set; }
    
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_anagrafica_causale</para> Chiave Origine: id_causale</summary>
     public virtual anagrafica_causale anagrafica_causale { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_anagrafica_risorse1</para> Chiave Origine: id_addetto_controllo</summary>
     public virtual anagrafica_risorse anagrafica_risorse1 { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_anagrafica_risorse2</para> Chiave Origine: id_addetto_lavorazione</summary>
     public virtual anagrafica_risorse anagrafica_risorse2 { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_anagrafica_stato_doc</para> Chiave Origine: id_stato</summary>
     public virtual anagrafica_stato_doc anagrafica_stato_doc { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_anagrafica_stato_doc1</para> Chiave Origine: id_stato_lavorazione</summary>
     public virtual anagrafica_stato_doc anagrafica_stato_doc1 { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_beni_avvpag_join_tab_avv_pag_tab_doc_input</para> Chiave Origine: id_join_avv_pag_doc_input</summary>
     public virtual ICollection<join_doc_input_beni_avvpag> join_doc_input_beni_avvpag { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_not_avvpag_join_tab_avv_pag_tab_doc_input</para> Chiave Origine: id_join_avv_pag_doc_input</summary>
     public virtual ICollection<join_doc_input_not_avvpag> join_doc_input_not_avvpag { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_riga_avvpag_join_tab_avv_pag_tab_doc_input</para> Chiave Origine: id_join_avv_pag_doc_input</summary>
     public virtual ICollection<join_doc_input_riga_avvpag> join_doc_input_riga_avvpag { get; set; }
        ///<summary><para>Relazione: FK_join_documenti_pratiche_join_tab_avv_pag_tab_doc_input</para> Chiave Origine: id_join_avv_pag_doc_input</summary>
     public virtual ICollection<join_documenti_pratiche> join_documenti_pratiche { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_join_tab_avv_pag_tab_doc_input1</para> Chiave Origine: id_join_avv_pag_doc_input_collegata</summary>
     public virtual ICollection<join_tab_avv_pag_tab_doc_input> join_tab_avv_pag_tab_doc_input1 { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_join_tab_avv_pag_tab_doc_input1</para> Chiave Origine: id_join_avv_pag_doc_input_collegata</summary>
     public virtual join_tab_avv_pag_tab_doc_input join_tab_avv_pag_tab_doc_input2 { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_tab_avv_pag</para> Chiave Origine: id_avv_pag</summary>
     public virtual tab_avv_pag tab_avv_pag { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_tab_avv_pag_fatt_emissione</para> Chiave Origine: id_tab_avv_pag_fatt_emissione</summary>
     public virtual tab_avv_pag_fatt_emissione tab_avv_pag_fatt_emissione { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_tab_avv_pag1</para> Chiave Origine: id_avv_pag_collegato</summary>
     public virtual tab_avv_pag tab_avv_pag1 { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_tab_doc_input</para> Chiave Origine: id_tab_doc_input</summary>
     public virtual tab_doc_input tab_doc_input { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_tab_rateizzazioni</para> Chiave Origine: id_rateizzazione</summary>
     public virtual tab_rateizzazioni tab_rateizzazioni { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_tab_tipo_bene</para> Chiave Origine: id_tipo_bene</summary>
     public virtual tab_tipo_bene tab_tipo_bene { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_verifica_join_tab_avv_pag_tab_doc_input</para> Chiave Origine: id_join_avv_pag_doc_input</summary>
     public virtual ICollection<tab_agevolazioni_verifica> tab_agevolazioni_verifica { get; set; }
        ///<summary><para>Relazione: FK_tab_rimborsi_join_tab_avv_pag_tab_doc_input</para> Chiave Origine: id_join_tab_avv_pag_tab_doc_input</summary>
     public virtual ICollection<tab_rimborsi> tab_rimborsi { get; set; }
        ///<summary><para>Relazione: FK_tab_vincoli_beni_pignorati_join_tab_avv_pag_tab_doc_input</para> Chiave Origine: id_join_avv_pag_doc_input</summary>
     public virtual ICollection<tab_vincoli_beni_pignorati> tab_vincoli_beni_pignorati { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_pag_avvpag_join_tab_avv_pag_tab_doc_input</para> Chiave Origine: id_join_avv_pag_doc_input</summary>
     public virtual ICollection<join_doc_input_pag_avvpag> join_doc_input_pag_avvpag { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_join_fattcont_fattconsumi</para> Chiave Origine: id_join_fattcont_fattconsumi</summary>
     public virtual join_fattcont_fattconsumi join_fattcont_fattconsumi { get; set; }
    }
}
