//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_documenti_contrib_ref
    {
        public int id_join_doc_presentati_contrib_ref { get; set; }
        public int id_tab_documenti { get; set; }
        public Nullable<int> id_join_contribuente_referente { get; set; }
    
        ///<summary><para>Relazione: FK_join_doc_presentati_contrib_ref_tab_doc_anagrafici</para> Chiave Origine: id_tab_documenti</summary>
     public virtual tab_documenti tab_documenti { get; set; }
        ///<summary><para>Relazione: FK_join_doc_presentati_contrib_ref_join_referente_contribuente</para> Chiave Origine: id_join_contribuente_referente</summary>
     public virtual join_referente_contribuente join_referente_contribuente { get; set; }
    }
}
