//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_avvcoa_ing
    {
        public int id_join_avvcoa { get; set; }
        public int id_avviso_coattivo { get; set; }
        public int id_avviso_collegato { get; set; }
        public string flag_on_off { get; set; }
    
        ///<summary><para>Relazione: FK_join_avvcoa_ing_tab_avv_pag</para> Chiave Origine: id_avviso_coattivo</summary>
     public virtual tab_avv_pag tab_avv_pag { get; set; }
        ///<summary><para>Relazione: FK_join_avvcoa_ing_tab_avv_pag1</para> Chiave Origine: id_avviso_collegato</summary>
     public virtual tab_avv_pag tab_avv_pag1 { get; set; }
    }
}
