//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_documenti_contribuenti
    {
        public int id_join_documenti_contribuenti { get; set; }
        public int id_tab_documenti { get; set; }
        public Nullable<decimal> id_contribuente_sto { get; set; }
    
        ///<summary><para>Relazione: FK_join_doc_presentati_contribuenti_tab_doc_anagrafici</para> Chiave Origine: id_tab_documenti</summary>
     public virtual tab_documenti tab_documenti { get; set; }
        ///<summary><para>Relazione: FK_join_doc_presentati_contribuenti_tab_contribuente_sto</para> Chiave Origine: id_contribuente_sto</summary>
     public virtual tab_contribuente_sto_new tab_contribuente_sto_new { get; set; }
    }
}
