//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_proprietari_immobili_coattivo
    {
        public int id_join_proprietari_immobili_coattivo { get; set; }
        public Nullable<decimal> id_contribuente { get; set; }
        public Nullable<int> id_referente { get; set; }
        public int id_tab_immobili_coattivo { get; set; }
        public decimal percentuale_possesso { get; set; }
        public Nullable<int> id_tipo_diritto { get; set; }
        public System.DateTime data_inizio { get; set; }
        public Nullable<System.DateTime> data_fine { get; set; }
        public int id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public string cf_piva_proprietario { get; set; }
    
        ///<summary><para>Relazione: FK_join_proprietari_immobili_coattivo_anagrafica_tipo_diritto</para> Chiave Origine: id_tipo_diritto</summary>
     public virtual anagrafica_tipo_diritto anagrafica_tipo_diritto { get; set; }
        ///<summary><para>Relazione: FK_join_proprietari_immobili_coattivo_tab_immobili_coattivo</para> Chiave Origine: id_tab_immobili_coattivo</summary>
     public virtual tab_immobili_coattivo tab_immobili_coattivo { get; set; }
        ///<summary><para>Relazione: FK_join_proprietari_immobili_coattivo_tab_contribuente</para> Chiave Origine: id_contribuente</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
        ///<summary><para>Relazione: FK_join_proprietari_immobili_coattivo_tab_referente</para> Chiave Origine: id_referente</summary>
     public virtual tab_referente tab_referente { get; set; }
    }
}
