//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_referente_contribuente
    {
        public join_referente_contribuente()
        {
            this.join_documenti_contrib_ref = new HashSet<join_documenti_contrib_ref>();
            this.join_referente_contribuente_avv_pag = new HashSet<join_referente_contribuente_avv_pag>();
            this.join_avv_pag_soggetto_debitore = new HashSet<join_avv_pag_soggetto_debitore>();
            this.join_avv_pag_fatt_emissione_soggetto_debitore = new HashSet<join_avv_pag_fatt_emissione_soggetto_debitore>();
        }
    
        public int id_join_referente_contribuente { get; set; }
        public int id_tab_referente { get; set; }
        public decimal id_anag_contribuente { get; set; }
        public int id_tipo_relazione { get; set; }
        public System.DateTime data_inizio_validita { get; set; }
        public Nullable<System.DateTime> data_fine_validita { get; set; }
        public Nullable<int> id_utente { get; set; }
        public string flag_verifica_validita { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public string cod_stato { get; set; }
        public int livello_autorizzazione_interno { get; set; }
        public string flag_coobbligato { get; set; }
        public decimal coobbligazione_percentuale { get; set; }
        public Nullable<int> id_anagrafica_parentela { get; set; }
        public Nullable<int> id_referente_delegante { get; set; }
        public bool flag_destinatario { get; set; }
        public decimal importo_max_obbligazione { get; set; }
    
        ///<summary><para>Relazione: FK_join_referente_contribuente_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato</summary>
     public virtual anagrafica_cod_stato_base anagrafica_cod_stato_base { get; set; }
        ///<summary><para>Relazione: FK_join_referente_contribuente_anagrafica_parentela</para> Chiave Origine: id_anagrafica_parentela</summary>
     public virtual anagrafica_parentela anagrafica_parentela { get; set; }
        ///<summary><para>Relazione: FK_join_referente_contribuente_anagrafica_tipo_relazione</para> Chiave Origine: id_tipo_relazione</summary>
     public virtual anagrafica_tipo_relazione anagrafica_tipo_relazione { get; set; }
        ///<summary><para>Relazione: FK_join_doc_presentati_contrib_ref_join_referente_contribuente</para> Chiave Origine: id_join_contribuente_referente</summary>
     public virtual ICollection<join_documenti_contrib_ref> join_documenti_contrib_ref { get; set; }
        ///<summary><para>Relazione: FK_join_referente_contribuente_avv_pag_join_referente_contribuente</para> Chiave Origine: id_join_referente_contribuente</summary>
     public virtual ICollection<join_referente_contribuente_avv_pag> join_referente_contribuente_avv_pag { get; set; }
        ///<summary><para>Relazione: FK_join_avv_pag_soggetto_debitore_join_referente_contribuente</para> Chiave Origine: id_join_referente_contribuente</summary>
     public virtual ICollection<join_avv_pag_soggetto_debitore> join_avv_pag_soggetto_debitore { get; set; }
        ///<summary><para>Relazione: FK_join_avv_pag_fatt_emissione_soggetto_debitore_join_referente_contribuente</para> Chiave Origine: id_join_referente_contribuente</summary>
     public virtual ICollection<join_avv_pag_fatt_emissione_soggetto_debitore> join_avv_pag_fatt_emissione_soggetto_debitore { get; set; }
        ///<summary><para>Relazione: FK_join_referente_contribuente_tab_contribuente</para> Chiave Origine: id_anag_contribuente</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
        ///<summary><para>Relazione: FK_join_referente_contribuente_tab_referente</para> Chiave Origine: id_tab_referente</summary>
     public virtual tab_referente tab_referente { get; set; }
        ///<summary><para>Relazione: FK_join_referente_contribuente_tab_referente1</para> Chiave Origine: id_referente_delegante</summary>
     public virtual tab_referente tab_referente1 { get; set; }
        ///<summary><para>Relazione: FK_join_referente_contribuente_tab_utenti</para> Chiave Origine: id_utente</summary>
     public virtual tab_utenti tab_utenti { get; set; }
    }
}
