//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_documenti_referenti
    {
        public int id_join_documenti_referenti { get; set; }
        public int id_tab_documenti { get; set; }
        public Nullable<int> id_referente_sto { get; set; }
    
        ///<summary><para>Relazione: FK_join_doc_presentati_referenti_tab_doc_anagrafici</para> Chiave Origine: id_tab_documenti</summary>
     public virtual tab_documenti tab_documenti { get; set; }
        ///<summary><para>Relazione: FK_join_doc_presentati_referenti_tab_referente_sto</para> Chiave Origine: id_referente_sto</summary>
     public virtual tab_referente_sto tab_referente_sto { get; set; }
    }
}
