//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_contribuenti_procedure_concorsuali
    {
        public int id_join_contribuenti_procedure_concorsuali { get; set; }
        public int id_procedura_concorsuale { get; set; }
        public decimal id_contribuente { get; set; }
        public Nullable<System.DateTime> data_avviso_apertura_procedura { get; set; }
        public int id_tab_doc_input { get; set; }
        public int id_avv_pag_domanda_ammissione { get; set; }
        public string numero_protocollo_domanda { get; set; }
        public Nullable<System.DateTime> data_presentazione_domanda { get; set; }
        public Nullable<decimal> tot_crediti_privilegiati_domanda { get; set; }
        public Nullable<decimal> tot_crediti_chirografari_domanda { get; set; }
        public string flag_adunanza_creditori { get; set; }
        public string flag_progetto_stato_passivo { get; set; }
        public Nullable<decimal> tot_crediti_privilegiati_riconosciuti { get; set; }
        public Nullable<decimal> tot_crediti_chirografari_riconosciuti { get; set; }
        public Nullable<decimal> tot_crediti_riconosciuti { get; set; }
        public string flag_opposizione { get; set; }
        public Nullable<System.DateTime> data_comunicazione { get; set; }
        public int id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
    
        ///<summary><para>Relazione: FK_join_contribuenti_procedure_concorsuali_tab_avv_pag</para> Chiave Origine: id_avv_pag_domanda_ammissione</summary>
     public virtual tab_avv_pag tab_avv_pag { get; set; }
        ///<summary><para>Relazione: FK_join_contribuenti_procedure_concorsuali_tab_contribuente</para> Chiave Origine: id_contribuente</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
        ///<summary><para>Relazione: FK_join_contribuenti_procedure_concorsuali_tab_doc_input</para> Chiave Origine: id_tab_doc_input</summary>
     public virtual tab_doc_input tab_doc_input { get; set; }
        ///<summary><para>Relazione: FK_join_contribuenti_procedure_concorsuali_tab_procedure_concorsuali</para> Chiave Origine: id_procedura_concorsuale</summary>
     public virtual tab_procedure_concorsuali tab_procedure_concorsuali { get; set; }
    }
}
