//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_applicazioni_link
    {
        public int id_join_applicazioni_link { get; set; }
        public int id_tab_applicazioni { get; set; }
        public int id_tab_applicazioni_link { get; set; }
        public string label { get; set; }
        public Nullable<int> ordine { get; set; }
        public bool selezione_richiesta { get; set; }
    
        ///<summary><para>Relazione: FK_join_applicazioni_link_tab_applicazioni</para> Chiave Origine: id_tab_applicazioni</summary>
     public virtual tab_applicazioni tab_applicazioni { get; set; }
        ///<summary><para>Relazione: FK_join_applicazioni_link_tab_applicazioni_link</para> Chiave Origine: id_tab_applicazioni_link</summary>
     public virtual tab_applicazioni tab_applicazioni1 { get; set; }
    }
}
