//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_tab_supervisione_profili
    {
        public join_tab_supervisione_profili()
        {
            this.tab_esito_aci = new HashSet<tab_esito_aci>();
        }
    
        public int id_join_tab_supervisione_profili { get; set; }
        public Nullable<int> id_tab_supervisione_finale { get; set; }
        public Nullable<int> id_tab_profilo_contribuente { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public string num_protocollo_registro_iscrizione_bene { get; set; }
        public Nullable<System.DateTime> data_protocollo_registro_iscrizione_bene { get; set; }
        public string num_protocollo_registro_sospensione_iscrizione { get; set; }
        public Nullable<System.DateTime> data_protocollo_registro_sospensione_iscrizione { get; set; }
        public string num_protocollo_registro_annullamento_iscrizione { get; set; }
        public Nullable<System.DateTime> data_protocollo_registro_annullamento_iscrizione { get; set; }
        public string num_protocollo_registro_cancellazione_iscrizione { get; set; }
        public Nullable<System.DateTime> data_protocollo_registro_cancellazione_iscrizione { get; set; }
        public Nullable<int> id_stato { get; set; }
        public Nullable<int> id_progressivo_formalita_aci { get; set; }
        public Nullable<decimal> importo_iscrizione_fermo { get; set; }
        public Nullable<decimal> id_pratica_presentazione { get; set; }
        public Nullable<int> codice_formalita_presentazione { get; set; }
        public Nullable<System.DateTime> data_presentazione_pratica { get; set; }
        public string id_pratica_iscrizione_bene { get; set; }
        public Nullable<System.DateTime> data_pratica_iscrizione_bene { get; set; }
        public string id_pratica_sospensione_iscrizione { get; set; }
        public Nullable<System.DateTime> data_pratica_sospensione_iscrizione { get; set; }
        public string id_pratica_annullamento_iscrizione { get; set; }
        public Nullable<System.DateTime> data_pratica_annullamento_iscrizione { get; set; }
        public string id_pratica_cancellazione_iscrizione { get; set; }
        public Nullable<System.DateTime> data_pratica_cancellazione_iscrizione { get; set; }
        public string identificativo_provv_revoca { get; set; }
        public Nullable<System.DateTime> data_provv_revoca { get; set; }
        public string identificativo_provv_cancellazione { get; set; }
        public Nullable<System.DateTime> data_provv_cancellazione { get; set; }
        public string vincolo_isc_rp_formalita_trascrizione { get; set; }
        public Nullable<System.DateTime> vincolo_isc_data_formalita_trascrizione { get; set; }
        public string vincolo_isc_provincia_rp_formalita_trascrizione { get; set; }
        public Nullable<System.DateTime> vincolo_isc_data_vincolo { get; set; }
        public string vincolo_ufficio_pra_competente { get; set; }
        public string isc_tipo_veicolo { get; set; }
        public string isc_targa { get; set; }
        public string isc_intestatario_cf { get; set; }
        public string cf_piva_nuovo_proprietario { get; set; }
    
        ///<summary><para>Relazione: FK_join_tab_supervisione_profili_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_join_tab_supervisione_profili_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_join_tab_supervisione_profili_tab_profilo_contribuente_new</para> Chiave Origine: id_tab_profilo_contribuente</summary>
     public virtual tab_profilo_contribuente_new tab_profilo_contribuente_new { get; set; }
        ///<summary><para>Relazione: FK_join_tab_supervisione_profili_TAB_SUPERVISIONE_FINALE_V2</para> Chiave Origine: id_tab_supervisione_finale</summary>
     public virtual TAB_SUPERVISIONE_FINALE_V2 TAB_SUPERVISIONE_FINALE_V2 { get; set; }
        ///<summary><para>Relazione: FK_join_tab_supervisione_profili_tab_progressivi_formalita_aci</para> Chiave Origine: id_progressivo_formalita_aci</summary>
     public virtual tab_progressivi_formalita_aci tab_progressivi_formalita_aci { get; set; }
        ///<summary><para>Relazione: FK_tab_esito_aci_join_tab_supervisione_profili</para> Chiave Origine: id_join_tab_supervisione_profili</summary>
     public virtual ICollection<tab_esito_aci> tab_esito_aci { get; set; }
    }
}
