//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_tipo_stato_referenza
    {
        public int id_join_tipo_stato_referenza { get; set; }
        public Nullable<int> id_stato_contribuente { get; set; }
        public Nullable<int> id_tipo_contribuente { get; set; }
        public Nullable<int> id_tipo_relazione { get; set; }
        public string flag_coobbligato { get; set; }
        public bool flag_destinatario { get; set; }
    
        ///<summary><para>Relazione: FK_join_tipo_stato_referenza_anagrafica_stato_contribuente</para> Chiave Origine: id_stato_contribuente</summary>
     public virtual anagrafica_stato_contribuente anagrafica_stato_contribuente { get; set; }
        ///<summary><para>Relazione: FK_join_tipo_stato_referenza_anagrafica_tipo_contribuente</para> Chiave Origine: id_tipo_contribuente</summary>
     public virtual anagrafica_tipo_contribuente anagrafica_tipo_contribuente { get; set; }
        ///<summary><para>Relazione: FK_join_tipo_stato_referenza_anagrafica_tipo_relazione</para> Chiave Origine: id_tipo_relazione</summary>
     public virtual anagrafica_tipo_relazione anagrafica_tipo_relazione { get; set; }
    }
}
