//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_tab_carrello_tab_rate
    {
        public int id_join_carrello_rate { get; set; }
        public int id_carrello { get; set; }
        public int id_rata { get; set; }
        public Nullable<decimal> importo_da_pagare_rata { get; set; }
        public string bic_accredito { get; set; }
        public string iban_accredito { get; set; }
        public Nullable<decimal> importo_rata_maggiorato_interessi { get; set; }
        public Nullable<decimal> importo_rata_maggiorato_sanzioni { get; set; }
        public decimal id_contribuente_debitore { get; set; }
        public string tipo_soggetto_debitore { get; set; }
        public string cf_piva_debitore { get; set; }
        public string cognome_ragsoc_debitore { get; set; }
        public string nome_debitore { get; set; }
        public string indirizzo_debitore { get; set; }
        public string cap_debitore { get; set; }
        public string comune_debitore { get; set; }
        public string nazione_debitore { get; set; }
        public string tipo_marca_da_bollo { get; set; }
        public string hashDocumento_digitale { get; set; }
        public string sigla_autonom_prov_soggetto_debitore { get; set; }
        public string cod_stato { get; set; }
        public string identificativo_rt { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cf_piva_dominio_ente_creditore { get; set; }
        public Nullable<System.DateTime> data_regolamento_flusso { get; set; }
        public Nullable<System.DateTime> data_flusso { get; set; }
        public Nullable<int> id_flusso_rendicontazione { get; set; }
        public string identificativo_flusso { get; set; }
        public string identificativo_univoco_regolamento { get; set; }
        public string causale_versamento { get; set; }
    
        ///<summary><para>Relazione: FK_join_tab_carrello_tab_rate_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_join_tab_carrello_tab_rate_anagrafica_stato_carrello</para> Chiave Origine: id_stato</summary>
     public virtual anagrafica_stato_carrello anagrafica_stato_carrello { get; set; }
        ///<summary><para>Relazione: FK_join_tab_carrello_tab_rate_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_join_tab_carrello_tab_rate_tab_carrello</para> Chiave Origine: id_carrello</summary>
     public virtual tab_carrello tab_carrello { get; set; }
        ///<summary><para>Relazione: FK_join_tab_carrello_tab_rate_tab_contribuente</para> Chiave Origine: id_contribuente_debitore</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
        ///<summary><para>Relazione: FK_join_tab_carrello_tab_rate_tab_rata_avv_pag</para> Chiave Origine: id_rata</summary>
     public virtual tab_rata_avv_pag tab_rata_avv_pag { get; set; }
    }
}
