//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_oggetti_immobili
    {
        public int id_join_oggetto_immobile { get; set; }
        public decimal id_oggetto { get; set; }
        public int id_tab_immobili { get; set; }
    
        ///<summary><para>Relazione: FK_join_oggetti_immobili_tab_immobili</para> Chiave Origine: id_tab_immobili</summary>
     public virtual tab_immobili tab_immobili { get; set; }
        ///<summary><para>Relazione: FK_join_oggetti_immobili_tab_oggetti</para> Chiave Origine: id_oggetto</summary>
     public virtual tab_oggetti tab_oggetti { get; set; }
    }
}
