//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_avv_pag_mov_pag_fatt_emissione
    {
        public int id_avv_pag_mov_pag { get; set; }
        public int id_mov_pag { get; set; }
        public int id_avv_pag_pagato { get; set; }
        public decimal importo_pagato { get; set; }
        public Nullable<int> id_oper_acc { get; set; }
        public Nullable<System.DateTime> data_oper_acc { get; set; }
        public Nullable<int> id_avv_pag_accreditato { get; set; }
        public Nullable<int> id_avv_pag_stornato { get; set; }
        public string flag_adesione { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
    
        ///<summary><para>Relazione: FK_join_avv_pag_mov_pag_fatt_emissione_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_join_avv_pag_mov_pag_fatt_emissione_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_join_avv_pag_mov_pag_fatt_emissione_tab_avv_pag</para> Chiave Origine: id_avv_pag_pagato</summary>
     public virtual tab_avv_pag tab_avv_pag { get; set; }
        ///<summary><para>Relazione: FK_join_avv_pag_mov_pag_fatt_emissione_tab_avv_pag1</para> Chiave Origine: id_avv_pag_accreditato</summary>
     public virtual tab_avv_pag tab_avv_pag1 { get; set; }
        ///<summary><para>Relazione: FK_join_avv_pag_mov_pag_fatt_emissione_tab_avv_pag2</para> Chiave Origine: id_avv_pag_stornato</summary>
     public virtual tab_avv_pag tab_avv_pag2 { get; set; }
        ///<summary><para>Relazione: FK_join_avv_pag_mov_pag_fatt_emissione_tab_mov_pag</para> Chiave Origine: id_mov_pag</summary>
     public virtual tab_mov_pag tab_mov_pag { get; set; }
    }
}
