//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class join_spuntisti_prenotazione_piazzole
    {
        public int id_spuntisti_prenotazione_piazzole { get; set; }
        public int id_spuntista { get; set; }
        public int id_area_mercato { get; set; }
        public Nullable<System.DateTime> giorno { get; set; }
        public Nullable<int> numero_piazzole_prenotate_pagate { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
    
        ///<summary><para>Relazione: FK_join_spuntisti_prenotazione_piazzole_tab_occupazione_piazzole</para> Chiave Origine: id_area_mercato</summary>
     public virtual tab_area_mercato tab_area_mercato { get; set; }
        ///<summary><para>Relazione: FK_join_spuntisti_prenotazione_piazzole_tab_spuntista</para> Chiave Origine: id_spuntista</summary>
     public virtual tab_spuntista tab_spuntista { get; set; }
    }
}
