//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ser_codici_catastali
    {
        public int id_ser_codici_catastali { get; set; }
        public string cod_catastale { get; set; }
        public string comune { get; set; }
        public string prov { get; set; }
    }
}
