//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_categoria_tariffaria_imu
    {
        public int id_categoria_tariffaria_imu { get; set; }
        public Nullable<int> id_anagrafica_categoria { get; set; }
        public Nullable<int> id_utilizzo { get; set; }
        public int anno { get; set; }
        public string um { get; set; }
        public decimal rivalutazione_rendita_catastale { get; set; }
        public decimal aliquota_base_semestre1 { get; set; }
        public decimal aliquota_base_semestre2 { get; set; }
        public decimal coefficiente_categoria { get; set; }
        public bool esente { get; set; }
    
        ///<summary><para>Relazione: FK_tab_categoria_tariffaria_imu_anagrafica_categoria</para> Chiave Origine: id_anagrafica_categoria</summary>
     public virtual anagrafica_categoria anagrafica_categoria { get; set; }
        ///<summary><para>Relazione: FK_tab_categoria_tariffaria_imu_anagrafica_utilizzo</para> Chiave Origine: id_utilizzo</summary>
     public virtual anagrafica_utilizzo anagrafica_utilizzo { get; set; }
    }
}
