//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_pianificazione_cicli_input_emissione
    {
        public int id_pianificazione_ciclo_input_emissione { get; set; }
        public int id_pianificazione_ciclo { get; set; }
        public int id_tipo_avvpag { get; set; }
        public int id_tipo_ciclo { get; set; }
        public int id_tipo_servizio { get; set; }
        public Nullable<int> anno_rif_ordinario { get; set; }
        public Nullable<System.DateTime> periodo_rif_ordinario_da { get; set; }
        public Nullable<System.DateTime> periodo_rif_ordinario_a { get; set; }
        public Nullable<int> anno_rif_fattura_idrica { get; set; }
        public Nullable<System.DateTime> periodo_rif_fattura_idrica_da { get; set; }
        public Nullable<System.DateTime> periodo_rif_fattura_idrica_a { get; set; }
        public string fattura_tipo_calcolo { get; set; }
        public Nullable<int> id_lista_rif_1 { get; set; }
        public Nullable<int> id_lista_rif_2 { get; set; }
        public Nullable<int> id_lista_rif_3 { get; set; }
        public Nullable<int> id_lista_rif_4 { get; set; }
        public Nullable<int> id_lista_rif_5 { get; set; }
        public Nullable<int> importo_minimo_avvpag { get; set; }
        public Nullable<int> importo_massimo_avvpag { get; set; }
        public Nullable<bool> controllo_anagrafico { get; set; }
        public Nullable<bool> creazione_bollettini { get; set; }
        public Nullable<bool> arrotondamento { get; set; }
        public Nullable<int> anno_rif_accertamento_1 { get; set; }
        public Nullable<System.DateTime> periodo_rif_accertamento_1_da { get; set; }
        public Nullable<System.DateTime> periodo_rif_accertamento_1_a { get; set; }
        public Nullable<int> anno_rif_accertamento_2 { get; set; }
        public Nullable<System.DateTime> periodo_rif_accertamento_2_da { get; set; }
        public Nullable<System.DateTime> periodo_rif_accertamento_2_a { get; set; }
        public Nullable<int> anno_rif_accertamento_3 { get; set; }
        public Nullable<System.DateTime> periodo_rif_accertamento_3_da { get; set; }
        public Nullable<System.DateTime> periodo_rif_accertamento_3_a { get; set; }
        public Nullable<int> anno_rif_accertamento_4 { get; set; }
        public Nullable<System.DateTime> periodo_rif_accertamento_4_da { get; set; }
        public Nullable<System.DateTime> periodo_rif_accertamento_4_a { get; set; }
        public Nullable<int> anno_rif_accertamento_5 { get; set; }
        public Nullable<System.DateTime> periodo_rif_accertamento_5_da { get; set; }
        public Nullable<System.DateTime> periodo_rif_accertamento_5_a { get; set; }
        public Nullable<bool> ingiunzioni_entrate_tutte { get; set; }
        public Nullable<int> ingiunzioni_entrata_1 { get; set; }
        public Nullable<int> ingiunzioni_entrata_2 { get; set; }
        public Nullable<int> ingiunzioni_entrata_3 { get; set; }
        public Nullable<int> ingiunzioni_entrata_4 { get; set; }
        public Nullable<int> ingiunzioni_entrata_5 { get; set; }
        public Nullable<int> ingiunzioni_entrata_6 { get; set; }
        public Nullable<int> ingiunzioni_entrata_7 { get; set; }
        public Nullable<int> ingiunzioni_entrata_8 { get; set; }
        public Nullable<int> ingiunzioni_entrata_9 { get; set; }
        public Nullable<int> ingiunzioni_entrata_10 { get; set; }
        public Nullable<bool> intimazioni_solleciti_rif_ing_tutte { get; set; }
        public Nullable<System.DateTime> intimazioni_solleciti_rif_ing_da { get; set; }
        public Nullable<System.DateTime> intimazioni_solleciti_rif_ing_a { get; set; }
        public Nullable<int> precoa_bonari_importo_da { get; set; }
        public Nullable<int> precoa_bonari_importo_a { get; set; }
        public Nullable<System.DateTime> precoa_bonari_data_importo_da { get; set; }
        public Nullable<System.DateTime> precoa_bonari_data_importo_a { get; set; }
        public Nullable<bool> avvintimazioni_solleciti_rif_ing_tutte { get; set; }
        public Nullable<int> id_lista_generata { get; set; }
        public string id_tipi_avv_pag_list { get; set; }
    
        ///<summary><para>Relazione: FK_tab_pianificazione_cicli_input_emissione_anagrafica_tipo_ciclo</para> Chiave Origine: id_tipo_ciclo</summary>
     public virtual anagrafica_tipo_ciclo anagrafica_tipo_ciclo { get; set; }
        ///<summary><para>Relazione: FK_tab_pianificazione_cicli_input_emissione_anagrafica_tipo_servizi</para> Chiave Origine: id_tipo_servizio</summary>
     public virtual anagrafica_tipo_servizi anagrafica_tipo_servizi { get; set; }
        ///<summary><para>Relazione: FK_tab_pianificazione_cicli_input_emissione_tab_pianificazione_cicli</para> Chiave Origine: id_pianificazione_ciclo</summary>
     public virtual tab_pianificazione_cicli tab_pianificazione_cicli { get; set; }
        ///<summary><para>Relazione: FK_tab_pianificazione_cicli_input_emissione_anagrafica_tipo_avv_pag</para> Chiave Origine: id_tipo_avvpag</summary>
     public virtual anagrafica_tipo_avv_pag anagrafica_tipo_avv_pag { get; set; }
    }
}
