//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_quantita_spedizione
    {
        public int id_tab_quantita_spedizione { get; set; }
        public int id_ente { get; set; }
        public int id_tipo_avvpag { get; set; }
        public string nazione { get; set; }
        public string cod_regione { get; set; }
        public string cod_provincia { get; set; }
        public string cap { get; set; }
        public Nullable<System.DateTime> data_inizio_validita { get; set; }
        public Nullable<System.DateTime> data_fine_validita { get; set; }
        public Nullable<int> MAX_quantita_singola_spedizione { get; set; }
        public string Progressivo { get; set; }
    }
}
