//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_idpspid
    {
        public int id_tab_idpspid { get; set; }
        public string EntityId { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationDisplayName { get; set; }
        public string OrganizationUrl { get; set; }
        public string SingleSignOnServiceUrl { get; set; }
        public string SingleLogoutServiceUrl { get; set; }
        public string SubjectNameIdRemoveText { get; set; }
        public string DateTimeFormat { get; set; }
        public Nullable<double> NowDelta { get; set; }
        public string ambiente { get; set; }
        public string flag_on_off { get; set; }
        public Nullable<System.DateTime> data_stato { get; set; }
        public string logo { get; set; }
        public string Description { get; set; }
        public string certificate { get; set; }
        public string url_metadata { get; set; }
    }
}
