//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_terzo
    {
        public tab_terzo()
        {
            this.tab_terzo_debitore = new HashSet<tab_terzo_debitore>();
            this.tab_avvisi_anomali_liste_carico = new HashSet<tab_avvisi_anomali_liste_carico>();
            this.join_avv_pag_soggetto_debitore = new HashSet<join_avv_pag_soggetto_debitore>();
            this.join_avv_pag_fatt_emissione_soggetto_debitore = new HashSet<join_avv_pag_fatt_emissione_soggetto_debitore>();
            this.tab_terzo_sto = new HashSet<tab_terzo_sto>();
            this.tab_doc_input = new HashSet<tab_doc_input>();
            this.tab_sped_not = new HashSet<tab_sped_not>();
            this.join_dichiarazione_terzo_contribuente = new HashSet<join_dichiarazione_terzo_contribuente>();
            this.tab_citazioni = new HashSet<tab_citazioni>();
            this.join_doc_input_pag_avvpag = new HashSet<join_doc_input_pag_avvpag>();
            this.tab_carrello = new HashSet<tab_carrello>();
            this.tab_autorizzazioni = new HashSet<tab_autorizzazioni>();
            this.join_terzo_referente = new HashSet<join_terzo_referente>();
            this.tab_mov_pag = new HashSet<tab_mov_pag>();
        }
    
        public int id_terzo { get; set; }
        public Nullable<int> id_stato_terzo { get; set; }
        public string cod_stato_terzo { get; set; }
        public Nullable<System.DateTime> data_inizio_stato { get; set; }
        public Nullable<System.DateTime> data_fine_stato { get; set; }
        public string fonte_stato { get; set; }
        public string nome { get; set; }
        public string cognome { get; set; }
        public string cod_fiscale { get; set; }
        public string rag_sociale { get; set; }
        public string denominazione_commerciale { get; set; }
        public string p_iva { get; set; }
        public string stato_nas { get; set; }
        public string comune_nas { get; set; }
        public Nullable<int> cod_comune_nas { get; set; }
        public Nullable<System.DateTime> data_nas { get; set; }
        public Nullable<System.DateTime> data_morte { get; set; }
        public Nullable<int> id_sesso { get; set; }
        public Nullable<int> id_tipo_terzo { get; set; }
        public Nullable<int> id_toponimo { get; set; }
        public string indirizzo { get; set; }
        public string edificio { get; set; }
        public Nullable<int> nr_civico { get; set; }
        public string sigla_civico { get; set; }
        public string scala { get; set; }
        public string piano { get; set; }
        public string interno { get; set; }
        public string condominio { get; set; }
        public string frazione { get; set; }
        public string stato { get; set; }
        public string citta { get; set; }
        public Nullable<int> cod_citta { get; set; }
        public string cap { get; set; }
        public string prov { get; set; }
        public string e_mail { get; set; }
        public string pec { get; set; }
        public string fax { get; set; }
        public string tel { get; set; }
        public string cell { get; set; }
        public string note { get; set; }
        public Nullable<int> id_utente { get; set; }
        public string flag_verifica_stato { get; set; }
        public string flag_verifica_cf_piva { get; set; }
        public string flag_verifica_pec { get; set; }
        public string flag_ricerca_indirizzo_emigrazione { get; set; }
        public string flag_ricerca_indirizzo_mancata_notifica { get; set; }
        public Nullable<System.DateTime> data_inizio_validita_altri_dati { get; set; }
        public Nullable<System.DateTime> data_fine_validita_altri_dati { get; set; }
        public string fonte_altri_dati { get; set; }
        public Nullable<System.DateTime> data_inizio_validita_indirizzo { get; set; }
        public Nullable<System.DateTime> data_fine_validita_indirizzo { get; set; }
        public string fonte_indirizzo { get; set; }
        public Nullable<int> contatore_verifiche_indirizzo_valido { get; set; }
        public string flag_irreperibilita_definitiva { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public string cod_stato { get; set; }
        public Nullable<decimal> km { get; set; }
        public Nullable<int> id_strada_db_poste { get; set; }
        public string colore { get; set; }
        public Nullable<int> id_tipo_bene_riferimento { get; set; }
        public Nullable<int> id_abi_cab { get; set; }
        public string cod_fiscale_pg { get; set; }
        public Nullable<System.DateTime> data_ultima_verifica { get; set; }
        public Nullable<int> id_toponimo_normalizzato { get; set; }
        public string pec_stragiudiziale { get; set; }
    
        ///<summary><para>Relazione: FK_tab_terzo_anagrafica_stato_contribuente</para> Chiave Origine: id_stato_terzo</summary>
     public virtual anagrafica_stato_contribuente anagrafica_stato_contribuente { get; set; }
        ///<summary><para>Relazione: FK_tab_terzo_anagrafica_tipo_contribuente</para> Chiave Origine: id_tipo_terzo</summary>
     public virtual anagrafica_tipo_contribuente anagrafica_tipo_contribuente { get; set; }
        ///<summary><para>Relazione: FK_tab_terzo_tab_toponimi</para> Chiave Origine: id_toponimo</summary>
     public virtual tab_toponimi tab_toponimi { get; set; }
        ///<summary><para>Relazione: FK_tab_terzo_debitore_tab_terzo</para> Chiave Origine: id_terzo</summary>
     public virtual ICollection<tab_terzo_debitore> tab_terzo_debitore { get; set; }
        ///<summary><para>Relazione: FK_tab_avvisi_anomali_liste_carico_tab_terzo</para> Chiave Origine: id_terzo</summary>
     public virtual ICollection<tab_avvisi_anomali_liste_carico> tab_avvisi_anomali_liste_carico { get; set; }
        ///<summary><para>Relazione: FK_join_avv_pag_soggetto_debitore_tab_terzo_debitore</para> Chiave Origine: id_terzo_debitore</summary>
     public virtual ICollection<join_avv_pag_soggetto_debitore> join_avv_pag_soggetto_debitore { get; set; }
        ///<summary><para>Relazione: FK_join_avv_pag_fatt_emissione_soggetto_debitore_tab_terzo</para> Chiave Origine: id_terzo_debitore</summary>
     public virtual ICollection<join_avv_pag_fatt_emissione_soggetto_debitore> join_avv_pag_fatt_emissione_soggetto_debitore { get; set; }
        ///<summary><para>Relazione: FK_tab_terzo_ANAGRAFICA_ABI_CAB</para> Chiave Origine: id_abi_cab</summary>
     public virtual ANAGRAFICA_ABI_CAB ANAGRAFICA_ABI_CAB { get; set; }
        ///<summary><para>Relazione: FK_tab_terzo_tab_tipo_bene</para> Chiave Origine: id_tipo_bene_riferimento</summary>
     public virtual tab_tipo_bene tab_tipo_bene { get; set; }
        ///<summary><para>Relazione: FK_tab_terzo_tab_poste_strada</para> Chiave Origine: id_strada_db_poste</summary>
     public virtual tab_poste_strada tab_poste_strada { get; set; }
        ///<summary><para>Relazione: FK_tab_terzo_sto_tab_terzo</para> Chiave Origine: id_terzo</summary>
     public virtual ICollection<tab_terzo_sto> tab_terzo_sto { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_tab_terzo_debitore</para> Chiave Origine: id_terzo</summary>
     public virtual ICollection<tab_doc_input> tab_doc_input { get; set; }
        ///<summary><para>Relazione: FK_tab_sped_not_tab_terzo</para> Chiave Origine: id_terzo_debitore</summary>
     public virtual ICollection<tab_sped_not> tab_sped_not { get; set; }
        ///<summary><para>Relazione: FK_join_dichiarazione_terzo_contribuente_tab_terzo</para> Chiave Origine: id_terzo</summary>
     public virtual ICollection<join_dichiarazione_terzo_contribuente> join_dichiarazione_terzo_contribuente { get; set; }
        ///<summary><para>Relazione: FK_tab_citazioni_tab_terzo</para> Chiave Origine: id_terzo</summary>
     public virtual ICollection<tab_citazioni> tab_citazioni { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_pag_avvpag_tab_terzo</para> Chiave Origine: id_terzo_destinatario</summary>
     public virtual ICollection<join_doc_input_pag_avvpag> join_doc_input_pag_avvpag { get; set; }
        ///<summary><para>Relazione: FK_tab_carrello_tab_terzo</para> Chiave Origine: id_terzo_versante</summary>
     public virtual ICollection<tab_carrello> tab_carrello { get; set; }
        ///<summary><para>Relazione: FK_tab_terzo_tab_utenti</para> Chiave Origine: id_utente</summary>
     public virtual tab_utenti tab_utenti { get; set; }
        ///<summary><para>Relazione: FK_tab_autorizzazioni_tab_terzo</para> Chiave Origine: id_terzo_richiesta_accesso</summary>
     public virtual ICollection<tab_autorizzazioni> tab_autorizzazioni { get; set; }
        ///<summary><para>Relazione: FK_join_terzo_referente_tab_terzo</para> Chiave Origine: id_terzo</summary>
     public virtual ICollection<join_terzo_referente> join_terzo_referente { get; set; }
        ///<summary><para>Relazione: FK_tab_mov_pag_tab_terzo</para> Chiave Origine: Id_terzo</summary>
     public virtual ICollection<tab_mov_pag> tab_mov_pag { get; set; }
    }
}
