//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_toponimi_catasto
    {
        public tab_toponimi_catasto()
        {
            this.tab_fabbricati_indirizzi = new HashSet<tab_fabbricati_indirizzi>();
        }
    
        public int id_tab_toponimi_catasto { get; set; }
        public int id_tab_tipi_toponimo_catasto { get; set; }
        public string toponimo { get; set; }
        public Nullable<int> id_toponimo_ente { get; set; }
    
        ///<summary><para>Relazione: fk_tab_fabbricati_indirizzi_tab_toponimi_catasto</para> Chiave Origine: id_tab_toponimi_catasto</summary>
     public virtual ICollection<tab_fabbricati_indirizzi> tab_fabbricati_indirizzi { get; set; }
        ///<summary><para>Relazione: fk_tab_toponimi_catasto_tab_tipi_toponimo_catasto</para> Chiave Origine: id_tab_tipi_toponimo_catasto</summary>
     public virtual tab_tipi_toponimo_catasto tab_tipi_toponimo_catasto { get; set; }
        ///<summary><para>Relazione: FK_tab_toponimi_catasto_tab_toponimi</para> Chiave Origine: id_toponimo_ente</summary>
     public virtual tab_toponimi tab_toponimi { get; set; }
    }
}
