//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_mov_pag_ici
    {
        public tab_mov_pag_ici()
        {
            this.tab_dett_mov_pag_ici = new HashSet<tab_dett_mov_pag_ici>();
        }
    
        public int id_tab_mov_pag { get; set; }
        public Nullable<decimal> id_contribuente { get; set; }
        public Nullable<int> id_nucleo_coabitazione_dettaglio { get; set; }
        public int id_tab_cc_riscossione { get; set; }
        public int id_tipo_pagamento { get; set; }
        public Nullable<int> id_tab_com_smarrimento { get; set; }
        public Nullable<int> id_tab_estrattoconto { get; set; }
        public string tipo_cc { get; set; }
        public Nullable<int> id_cuas { get; set; }
        public string uff_postale { get; set; }
        public Nullable<System.DateTime> data_operazione { get; set; }
        public System.DateTime data_accredito { get; set; }
        public Nullable<System.DateTime> data_valuta { get; set; }
        public decimal importo_mov_pagato { get; set; }
        public string code_line { get; set; }
        public string tipo_boll { get; set; }
        public string cognome_rag_soc { get; set; }
        public string nome { get; set; }
        public string indirizzo { get; set; }
        public string nr_civico { get; set; }
        public string cap { get; set; }
        public string localita { get; set; }
        public string codice_fiscale { get; set; }
        public string note { get; set; }
        public string nome_file_immagine { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public Nullable<decimal> importo_accoppiato { get; set; }
        public string flag_insanabile { get; set; }
        public string causale_pagamento { get; set; }
        public Nullable<int> anno_riferimento { get; set; }
        public string comune_ubicazione_immobili { get; set; }
        public string flag_ins_file { get; set; }
    
        ///<summary><para>Relazione: FK_tab_mov_pag_ici_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_mov_pag_ici_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_tab_mov_pag_ici_tab_tipo_pagamento</para> Chiave Origine: id_tipo_pagamento</summary>
     public virtual tab_tipo_pagamento tab_tipo_pagamento { get; set; }
        ///<summary><para>Relazione: FK_tab_dett_mov_pag_ici_tab_mov_pag_ici</para> Chiave Origine: id_tab_mov_pag</summary>
     public virtual ICollection<tab_dett_mov_pag_ici> tab_dett_mov_pag_ici { get; set; }
        ///<summary><para>Relazione: FK_tab_mov_pag_ici_tab_estratto_conto</para> Chiave Origine: id_tab_estrattoconto</summary>
     public virtual tab_estratto_conto tab_estratto_conto { get; set; }
        ///<summary><para>Relazione: FK_tab_mov_pag_ici_tab_contribuente</para> Chiave Origine: id_contribuente</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
    }
}
