//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_file_esiti_notifiche
    {
        public int id_tab_file_esiti_notifiche { get; set; }
        public Nullable<int> id_ente { get; set; }
        public string nome_file { get; set; }
        public int numero_riga { get; set; }
        public string testo { get; set; }
        public Nullable<int> id_anagrafica_controllo { get; set; }
    }
}
