//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_cod_identificativi_secondo_cf
    {
        public int id_identificativo_secondo_cf { get; set; }
        public string codice { get; set; }
        public string descrizione { get; set; }
        public Nullable<int> id_anagrafica_tipo_relazione { get; set; }
    }
}
