//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_log_operazioni_operatore
    {
        public int id_log_operazioni_operatore { get; set; }
        public int id_log_operatori { get; set; }
        public System.DateTime data { get; set; }
        public int id_tab_applicazione { get; set; }
        public Nullable<decimal> id_anag_contribuente { get; set; }
        public string operazione { get; set; }
        public string note { get; set; }
        public Nullable<int> id_ente { get; set; }
        public Nullable<int> id_utente { get; set; }
        public string tipo_messaggio { get; set; }
    
        ///<summary><para>Relazione: FK_tab_log_operazioni_operatore_tab_log_operatori</para> Chiave Origine: id_log_operatori</summary>
     public virtual tab_log_operatori tab_log_operatori { get; set; }
        ///<summary><para>Relazione: FK_tab_log_operazioni_operatore_tab_applicazioni</para> Chiave Origine: id_tab_applicazione</summary>
     public virtual tab_applicazioni tab_applicazioni { get; set; }
        ///<summary><para>Relazione: FK_tab_log_operazioni_operatore_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
        ///<summary><para>Relazione: FK_tab_log_operazioni_operatore_tab_utenti</para> Chiave Origine: id_utente</summary>
     public virtual tab_utenti tab_utenti { get; set; }
    }
}
