//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_tipo_contatore
    {
        public tab_tipo_contatore()
        {
            this.tab_contatore = new HashSet<tab_contatore>();
        }
    
        public int id_tipo_contatore { get; set; }
        public string marca { get; set; }
        public string sigla { get; set; }
        public string classe { get; set; }
        public string calibro { get; set; }
        public Nullable<decimal> qta_mc_min { get; set; }
        public Nullable<decimal> qta_mc_max { get; set; }
        public Nullable<int> lung_senza_raccordo { get; set; }
        public Nullable<int> lung_con_raccordo { get; set; }
        public Nullable<int> num_omologazione_cee { get; set; }
        public Nullable<decimal> ultimo_prezzo_unitario { get; set; }
        public Nullable<decimal> noleggio_annuo { get; set; }
        public Nullable<decimal> costo_annuo_manutenzione { get; set; }
    
        ///<summary><para>Relazione: FK_tab_contatore_tab_tipo_contatore</para> Chiave Origine: id_tipo_contatore</summary>
     public virtual ICollection<tab_contatore> tab_contatore { get; set; }
    }
}
