//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_ingiunzioni_ispezione
    {
        public tab_ingiunzioni_ispezione()
        {
            this.join_ispezioni_ingiunzioni = new HashSet<join_ispezioni_ingiunzioni>();
            this.join_ingfis_supervisione = new HashSet<join_ingfis_supervisione>();
        }
    
        public int id_tab_ingiunzioni_ispezione { get; set; }
        public decimal id_anag_contribuente { get; set; }
        public int id_tab_avv_pag { get; set; }
        public Nullable<decimal> importo_totale { get; set; }
        public Nullable<decimal> importo_da_pagare { get; set; }
        public Nullable<System.DateTime> data_emissione_ingiunzione { get; set; }
        public Nullable<System.DateTime> data_crezione_ingiunzione_ispezione { get; set; }
        public Nullable<bool> flag_assenza_attisuccecssivi { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public string flag_assoggettabile_atti_esecutivi { get; set; }
    
        ///<summary><para>Relazione: FK_tab_ingiunzioni_ispezione_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_ingiunzioni_ispezione_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_join_ispezioni_ingiunzioni_tab_ingiunzioni_ispezione</para> Chiave Origine: id_tab_ingiunzioni_ispezione</summary>
     public virtual ICollection<join_ispezioni_ingiunzioni> join_ispezioni_ingiunzioni { get; set; }
        ///<summary><para>Relazione: FK_join_ingfis_supervisione_tab_ingiunzioni_ispezione</para> Chiave Origine: id_tab_ingiunzione</summary>
     public virtual ICollection<join_ingfis_supervisione> join_ingfis_supervisione { get; set; }
        ///<summary><para>Relazione: FK_tab_ingiunzioni_ispezione_tab_avv_pag</para> Chiave Origine: id_tab_avv_pag</summary>
     public virtual tab_avv_pag tab_avv_pag { get; set; }
        ///<summary><para>Relazione: FK_tab_ingiunzioni_ispezione_tab_contribuente</para> Chiave Origine: id_anag_contribuente</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
    }
}
