//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_registro_cookie
    {
        public int id_tab_registro_cookie { get; set; }
        public string indirizzo_ip { get; set; }
        public string headers { get; set; }
        public string session_id { get; set; }
        public Nullable<System.DateTime> data_prima_visita { get; set; }
        public Nullable<System.DateTime> data_ultima_visita { get; set; }
        public string consenso { get; set; }
        public Nullable<bool> consenso_necessari { get; set; }
        public Nullable<bool> consenso_preferenze { get; set; }
        public Nullable<bool> consenso_statistiche { get; set; }
        public Nullable<System.DateTime> data_stato { get; set; }
    }
}
