//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_doc_input
    {
        public tab_doc_input()
        {
            this.join_denunce_doc_input = new HashSet<join_denunce_doc_input>();
            this.join_documenti_pratiche_presentati = new HashSet<join_documenti_pratiche_presentati>();
            this.join_tab_doc_input_tab_doc_output = new HashSet<join_tab_doc_input_tab_doc_output>();
            this.tab_boll_pag = new HashSet<tab_boll_pag>();
            this.tab_fascicolo = new HashSet<tab_fascicolo>();
            this.tab_udienze = new HashSet<tab_udienze>();
            this.tab_ipoteche = new HashSet<tab_ipoteche>();
            this.join_documenti_pratiche = new HashSet<join_documenti_pratiche>();
            this.tab_sentenze = new HashSet<tab_sentenze>();
            this.tab_rimborsi = new HashSet<tab_rimborsi>();
            this.tab_ricorsi = new HashSet<tab_ricorsi>();
            this.tab_ricorsi1 = new HashSet<tab_ricorsi>();
            this.join_denunce_oggetti = new HashSet<join_denunce_oggetti>();
            this.tab_agevolazioni_verifica = new HashSet<tab_agevolazioni_verifica>();
            this.tab_citazioni = new HashSet<tab_citazioni>();
            this.tab_citazioni1 = new HashSet<tab_citazioni>();
            this.tab_citazioni2 = new HashSet<tab_citazioni>();
            this.tab_citazioni3 = new HashSet<tab_citazioni>();
            this.tab_citazioni4 = new HashSet<tab_citazioni>();
            this.tab_citazioni5 = new HashSet<tab_citazioni>();
            this.tab_citazioni6 = new HashSet<tab_citazioni>();
            this.join_tab_avv_pag_tab_doc_input = new HashSet<join_tab_avv_pag_tab_doc_input>();
            this.join_contribuenti_procedure_concorsuali = new HashSet<join_contribuenti_procedure_concorsuali>();
            this.tab_registro_assegnazione_pratiche = new HashSet<tab_registro_assegnazione_pratiche>();
        }
    
        public int id_tab_doc_input { get; set; }
        public int id_ente { get; set; }
        public Nullable<int> id_ente_gestito { get; set; }
        public int id_entrata { get; set; }
        public Nullable<decimal> id_contribuente { get; set; }
        public Nullable<int> id_tipo_doc_entrate { get; set; }
        public Nullable<int> anno { get; set; }
        public Nullable<int> prog_tipo_doc_entrata { get; set; }
        public string cod_doc { get; set; }
        public Nullable<int> id_causale { get; set; }
        public Nullable<System.DateTime> data_presentazione { get; set; }
        public string annotazioni_acquisizione { get; set; }
        public Nullable<System.DateTime> data_decorrenza { get; set; }
        public Nullable<System.DateTime> data_scadenza { get; set; }
        public Nullable<System.DateTime> data_assegnazione_lav { get; set; }
        public Nullable<System.DateTime> data_controllo { get; set; }
        public Nullable<int> id_addetto_acquisizione { get; set; }
        public Nullable<int> id_addetto_assegnazione_lav { get; set; }
        public Nullable<int> id_addetto_lavorazione { get; set; }
        public Nullable<int> id_addetto_controllo { get; set; }
        public Nullable<int> id_addetto_supervisione { get; set; }
        public string flag_esito { get; set; }
        public Nullable<int> id_causale_esito { get; set; }
        public Nullable<System.DateTime> data_esito { get; set; }
        public string annotazioni_esito { get; set; }
        public Nullable<System.DateTime> data_inizio_lav { get; set; }
        public Nullable<System.DateTime> data_fine_lav { get; set; }
        public int id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public Nullable<int> id_risorsa_stato { get; set; }
        public Nullable<int> id_utente { get; set; }
        public string identificativo_doc_input { get; set; }
        public string tipo_utente { get; set; }
        public Nullable<int> id_referente { get; set; }
        public Nullable<int> id_terzo { get; set; }
        public Nullable<int> id_autorita_giudiziaria { get; set; }
        public Nullable<int> id_procura { get; set; }
    
        ///<summary><para>Relazione: FK_tab_doc_input_anagrafica_causale</para> Chiave Origine: id_causale</summary>
     public virtual anagrafica_causale anagrafica_causale { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_anagrafica_causale1</para> Chiave Origine: id_causale_esito</summary>
     public virtual anagrafica_causale anagrafica_causale1 { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_anagrafica_ente_gestito</para> Chiave Origine: id_ente_gestito</summary>
     public virtual anagrafica_ente_gestito anagrafica_ente_gestito { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_anagrafica_entrate</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_anagrafica_risorse</para> Chiave Origine: id_addetto_acquisizione</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_anagrafica_risorse1</para> Chiave Origine: id_addetto_assegnazione_lav</summary>
     public virtual anagrafica_risorse anagrafica_risorse1 { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_anagrafica_risorse2</para> Chiave Origine: id_addetto_lavorazione</summary>
     public virtual anagrafica_risorse anagrafica_risorse2 { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_anagrafica_risorse3</para> Chiave Origine: id_addetto_controllo</summary>
     public virtual anagrafica_risorse anagrafica_risorse3 { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_anagrafica_risorse4</para> Chiave Origine: id_addetto_supervisione</summary>
     public virtual anagrafica_risorse anagrafica_risorse4 { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_anagrafica_stato_doc</para> Chiave Origine: id_stato</summary>
     public virtual anagrafica_stato_doc anagrafica_stato_doc { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_join_denunce_doc_input_tab_doc_input</para> Chiave Origine: id_doc_input</summary>
     public virtual ICollection<join_denunce_doc_input> join_denunce_doc_input { get; set; }
        ///<summary><para>Relazione: FK_join_documenti_pratiche_presentati_tab_doc_input</para> Chiave Origine: id_tab_doc_input</summary>
     public virtual ICollection<join_documenti_pratiche_presentati> join_documenti_pratiche_presentati { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_join_risorse_ser_comuni</para> Chiave Origine: id_tipo_doc_entrate</summary>
     public virtual join_risorse_ser_comuni join_risorse_ser_comuni { get; set; }
        ///<summary><para>Relazione: FK_join_tab_doc_input_tab_doc_output_tab_doc_input</para> Chiave Origine: id_tab_doc_input</summary>
     public virtual ICollection<join_tab_doc_input_tab_doc_output> join_tab_doc_input_tab_doc_output { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_tab_autorita_giudiziaria</para> Chiave Origine: id_autorita_giudiziaria</summary>
     public virtual tab_autorita_giudiziaria tab_autorita_giudiziaria { get; set; }
        ///<summary><para>Relazione: FK_tab_boll_pag_tab_doc_input</para> Chiave Origine: id_tab_doc_output</summary>
     public virtual ICollection<tab_boll_pag> tab_boll_pag { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_tab_contribuente</para> Chiave Origine: id_contribuente</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_tab_procure</para> Chiave Origine: id_procura</summary>
     public virtual tab_procure tab_procure { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_tab_referente</para> Chiave Origine: id_referente</summary>
     public virtual tab_referente tab_referente { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_tab_terzo_debitore</para> Chiave Origine: id_terzo</summary>
     public virtual tab_terzo tab_terzo { get; set; }
        ///<summary><para>Relazione: FK_tab_fascicolo_tab_doc_input</para> Chiave Origine: id_doc_input</summary>
     public virtual ICollection<tab_fascicolo> tab_fascicolo { get; set; }
        ///<summary><para>Relazione: FK_tab_udienze_tab_doc_input</para> Chiave Origine: id_tab_doc_input_udienza</summary>
     public virtual ICollection<tab_udienze> tab_udienze { get; set; }
        ///<summary><para>Relazione: FK_tab_ipoteche_tab_doc_input</para> Chiave Origine: id_tab_doc_input_ipoteca</summary>
     public virtual ICollection<tab_ipoteche> tab_ipoteche { get; set; }
        ///<summary><para>Relazione: FK_join_documenti_pratiche_tab_doc_input</para> Chiave Origine: id_doc_input</summary>
     public virtual ICollection<join_documenti_pratiche> join_documenti_pratiche { get; set; }
        ///<summary><para>Relazione: FK_tab_sentenze_tab_doc_input</para> Chiave Origine: id_tab_appello</summary>
     public virtual ICollection<tab_sentenze> tab_sentenze { get; set; }
        ///<summary><para>Relazione: FK_tab_rimborsi_tab_doc_input</para> Chiave Origine: id_tab_doc_input</summary>
     public virtual ICollection<tab_rimborsi> tab_rimborsi { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrate</summary>
     public virtual tab_tipo_doc_entrate tab_tipo_doc_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_ricorsi_tab_doc_input</para> Chiave Origine: id_tab_doc_input</summary>
     public virtual ICollection<tab_ricorsi> tab_ricorsi { get; set; }
        ///<summary><para>Relazione: FK_tab_ricorsi_tab_doc_input1</para> Chiave Origine: id_tab_doc_input_mediazione</summary>
     public virtual ICollection<tab_ricorsi> tab_ricorsi1 { get; set; }
        ///<summary><para>Relazione: fk_3772A840_8087_43EA_A5F4_6A209A96C1E1</para> Chiave Origine: id_doc_input</summary>
     public virtual ICollection<join_denunce_oggetti> join_denunce_oggetti { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_verifica_tab_doc_input</para> Chiave Origine: id_pratica</summary>
     public virtual ICollection<tab_agevolazioni_verifica> tab_agevolazioni_verifica { get; set; }
        ///<summary><para>Relazione: FK_tab_citazioni_tab_doc_input</para> Chiave Origine: id_tab_doc_citazione</summary>
     public virtual ICollection<tab_citazioni> tab_citazioni { get; set; }
        ///<summary><para>Relazione: FK_tab_citazioni_tab_doc_input1</para> Chiave Origine: id_doc_input_assegnazione</summary>
     public virtual ICollection<tab_citazioni> tab_citazioni1 { get; set; }
        ///<summary><para>Relazione: FK_tab_citazioni_tab_doc_input2</para> Chiave Origine: id_doc_input_estinzione</summary>
     public virtual ICollection<tab_citazioni> tab_citazioni2 { get; set; }
        ///<summary><para>Relazione: FK_tab_citazioni_tab_doc_input3</para> Chiave Origine: id_doc_input_ordinanza_mancata_dichiarazione</summary>
     public virtual ICollection<tab_citazioni> tab_citazioni3 { get; set; }
        ///<summary><para>Relazione: FK_tab_citazioni_tab_doc_input4</para> Chiave Origine: id_doc_input_ultima_ordinanza_rinotifica_citazione</summary>
     public virtual ICollection<tab_citazioni> tab_citazioni4 { get; set; }
        ///<summary><para>Relazione: FK_tab_citazioni_tab_doc_input5</para> Chiave Origine: id_doc_input_ultima_ordinanza_rinvio_udienza</summary>
     public virtual ICollection<tab_citazioni> tab_citazioni5 { get; set; }
        ///<summary><para>Relazione: FK_tab_citazioni_tab_doc_input6</para> Chiave Origine: id_doc_input_ordinanza_fissazione_prima_udienza</summary>
     public virtual ICollection<tab_citazioni> tab_citazioni6 { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_tab_doc_input</para> Chiave Origine: id_tab_doc_input</summary>
     public virtual ICollection<join_tab_avv_pag_tab_doc_input> join_tab_avv_pag_tab_doc_input { get; set; }
        ///<summary><para>Relazione: FK_join_contribuenti_procedure_concorsuali_tab_doc_input</para> Chiave Origine: id_tab_doc_input</summary>
     public virtual ICollection<join_contribuenti_procedure_concorsuali> join_contribuenti_procedure_concorsuali { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
        ///<summary><para>Relazione: FK_tab_registro_assegnazione_pratiche_tab_doc_input</para> Chiave Origine: id_doc_input</summary>
     public virtual ICollection<tab_registro_assegnazione_pratiche> tab_registro_assegnazione_pratiche { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_tab_utenti</para> Chiave Origine: id_utente</summary>
     public virtual tab_utenti tab_utenti { get; set; }
    }
}
