//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_co1142_pf
    {
        public tab_co1142_pf()
        {
            this.tab_co1142_elenco_domicili_fiscali = new HashSet<tab_co1142_elenco_domicili_fiscali>();
        }
    
        public int id_rec { get; set; }
        public Nullable<int> tipo_record { get; set; }
        public string identificativo_ente { get; set; }
        public string codice_fiscale_richiesta { get; set; }
        public string cognome_richiesta { get; set; }
        public string nome_richiesta { get; set; }
        public string sesso_richiesta { get; set; }
        public Nullable<System.DateTime> data_nascita_richiesta { get; set; }
        public string cod_catasto_com_nasc_richiesta { get; set; }
        public string comune_stato_estero_richiesta { get; set; }
        public string prov_nas_richiesta { get; set; }
        public string codice_ritorno { get; set; }
        public string cod_ficale_at { get; set; }
        public string cognome_at { get; set; }
        public string nome_at { get; set; }
        public string sesso_at { get; set; }
        public Nullable<System.DateTime> data_nascita_at { get; set; }
        public string comune_stato_estero_at { get; set; }
        public string provincia_nascita_at { get; set; }
        public string comune_df { get; set; }
        public string provincia_df { get; set; }
        public string cap_df { get; set; }
        public string indirizzo_df { get; set; }
        public string fonte_di_comunicazione { get; set; }
        public Nullable<System.DateTime> data_decorrenza { get; set; }
        public string fonte_decesso { get; set; }
        public Nullable<System.DateTime> data_decesso { get; set; }
    
        ///<summary><para>Relazione: FK_tab_co1142_elenco_domicili_fiscali_tab_co1142_pf</para> Chiave Origine: id_tab_co1142_pf</summary>
     public virtual ICollection<tab_co1142_elenco_domicili_fiscali> tab_co1142_elenco_domicili_fiscali { get; set; }
    }
}
