//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_macroentrate
    {
        public tab_macroentrate()
        {
            this.join_entrate_macroentrate = new HashSet<join_entrate_macroentrate>();
            this.anagrafica_categoria = new HashSet<anagrafica_categoria>();
            this.anagrafica_utilizzo = new HashSet<anagrafica_utilizzo>();
            this.tab_oggetti_contribuzione = new HashSet<tab_oggetti_contribuzione>();
            this.tab_categoria_tariffaria = new HashSet<tab_categoria_tariffaria>();
        }
    
        public int id_tab_macroentrate { get; set; }
        public string descrizione { get; set; }
        public string sigla { get; set; }
        public int ordine { get; set; }
    
        ///<summary><para>Relazione: FK_join_entrate_macroentrate_tab_macroentrate</para> Chiave Origine: id_tab_macroentrate</summary>
     public virtual ICollection<join_entrate_macroentrate> join_entrate_macroentrate { get; set; }
        ///<summary><para>Relazione: FK_anagrafica_categoria_tab_macroentrate</para> Chiave Origine: id_entrata</summary>
     public virtual ICollection<anagrafica_categoria> anagrafica_categoria { get; set; }
        ///<summary><para>Relazione: FK_anagrafica_utilizzo_tab_macroentrate</para> Chiave Origine: id_entrata</summary>
     public virtual ICollection<anagrafica_utilizzo> anagrafica_utilizzo { get; set; }
        ///<summary><para>Relazione: FK_tab_oggetti_contribuzione_tab_macroentrate</para> Chiave Origine: id_entrata</summary>
     public virtual ICollection<tab_oggetti_contribuzione> tab_oggetti_contribuzione { get; set; }
        ///<summary><para>Relazione: FK_tab_categoria_tariffaria_tab_macroentrate</para> Chiave Origine: id_entrata</summary>
     public virtual ICollection<tab_categoria_tariffaria> tab_categoria_tariffaria { get; set; }
    }
}
