//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_file_trasmessi
    {
        public int id_tab_file_trasmessi { get; set; }
        public string nome_file { get; set; }
        public string tipo_file { get; set; }
        public System.DateTime data_trasmissione { get; set; }
        public int id_struttura_trasmissione { get; set; }
        public int id_risorsa_trasmissione { get; set; }
        public string hash_code { get; set; }
        public string identificativo_file { get; set; }
        public bool valido { get; set; }
        public string nome_file_origine { get; set; }
        public int id_lista { get; set; }
        public string tipo_trasferimento { get; set; }
        public Nullable<int> ultima_riga_importata { get; set; }
        public Nullable<bool> flag_esito_importazione { get; set; }
    
        ///<summary><para>Relazione: FK_tab_file_trasmessi_anagrafica_risorse</para> Chiave Origine: id_risorsa_trasmissione</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_file_trasmessi_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_trasmissione</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_tab_file_trasmessi_tab_liste</para> Chiave Origine: id_lista</summary>
     public virtual tab_liste tab_liste { get; set; }
    }
}
