//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_terreni_riserve
    {
        public int id_tab_terreni_riserve { get; set; }
        public int id_tab_terreni { get; set; }
        public string cod_riserva { get; set; }
        public string partita_iscrizione { get; set; }
    
        ///<summary><para>Relazione: fk_tab_terreni_riserve_tab_terreni</para> Chiave Origine: id_tab_terreni</summary>
     public virtual tab_terreni tab_terreni { get; set; }
    }
}
