//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_pianificazione_cicli_enti_gestiti
    {
        public int id_tab_pianificazione_cicli_enti_gestiti { get; set; }
        public int id_pianificazione_ciclo { get; set; }
        public int id_ente { get; set; }
        public int id_ente_gestito { get; set; }
    
        ///<summary><para>Relazione: FK_tab_pianificazione_cicli_enti_gestiti_tab_pianificazione_cicli</para> Chiave Origine: id_pianificazione_ciclo</summary>
     public virtual tab_pianificazione_cicli tab_pianificazione_cicli { get; set; }
        ///<summary><para>Relazione: FK_tab_pianificazione_cicli_enti_gestiti_anagrafica_ente_gestito</para> Chiave Origine: id_ente_gestito</summary>
     public virtual anagrafica_ente_gestito anagrafica_ente_gestito { get; set; }
        ///<summary><para>Relazione: FK_tab_pianificazione_cicli_enti_gestiti_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
    }
}
