//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_fascicolo_doc_output_allegati
    {
        public tab_fascicolo_doc_output_allegati()
        {
            this.join_documenti_fascicolo_doc_output_allegati = new HashSet<join_documenti_fascicolo_doc_output_allegati>();
        }
    
        public int id_fascicolo_doc_output_allegati { get; set; }
        public int id_fascicolo { get; set; }
        public int id_doc_output_rif_documenti { get; set; }
        public int id_tab_sped_not { get; set; }
        public int id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
    
        ///<summary><para>Relazione: FK_tab_fascicolo_doc_output_allegati_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_fascicolo_doc_output_allegati_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_tab_fascicolo_doc_output_allegati_tab_doc_output</para> Chiave Origine: id_doc_output_rif_documenti</summary>
     public virtual tab_doc_output tab_doc_output { get; set; }
        ///<summary><para>Relazione: FK_tab_fascicolo_doc_output_allegati_tab_fascicolo</para> Chiave Origine: id_fascicolo</summary>
     public virtual tab_fascicolo tab_fascicolo { get; set; }
        ///<summary><para>Relazione: FK_tab_fascicolo_doc_output_allegati_tab_sped_not</para> Chiave Origine: id_tab_sped_not</summary>
     public virtual tab_sped_not tab_sped_not { get; set; }
        ///<summary><para>Relazione: FK_join_documenti_fascicolo_allegati_doc_output_tab_fascicolo_doc_output_allegati</para> Chiave Origine: id_fascicolo_doc_output_allegati</summary>
     public virtual ICollection<join_documenti_fascicolo_doc_output_allegati> join_documenti_fascicolo_doc_output_allegati { get; set; }
    }
}
