//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_liste
    {
        public tab_liste()
        {
            this.join_controlli_avvpag_fatt_emissione = new HashSet<join_controlli_avvpag_fatt_emissione>();
            this.tab_avv_pag = new HashSet<tab_avv_pag>();
            this.tab_avv_pag_fatt_emissione = new HashSet<tab_avv_pag_fatt_emissione>();
            this.tab_avv_pag_fatt_rettifica = new HashSet<tab_avv_pag_fatt_rettifica>();
            this.tab_avvisi_anomali_liste_carico = new HashSet<tab_avvisi_anomali_liste_carico>();
            this.tab_controlli_qualita_liste_carico = new HashSet<tab_controlli_qualita_liste_carico>();
            this.tab_rilevazione_acquedotto_smart = new HashSet<tab_rilevazione_acquedotto_smart>();
            this.tab_validazione_approvazione_liste_spedizione = new HashSet<tab_validazione_approvazione_liste_spedizione>();
            this.tab_validazione_approvazione_liste = new HashSet<tab_validazione_approvazione_liste>();
            this.join_lista_voci_contribuzione = new HashSet<join_lista_voci_contribuzione>();
            this.tab_avv_pag1 = new HashSet<tab_avv_pag>();
            this.tab_liste1 = new HashSet<tab_liste>();
            this.tab_dett_lista = new HashSet<tab_dett_lista>();
            this.tab_lista_ente_gestito = new HashSet<tab_lista_ente_gestito>();
            this.tab_file_trasmessi = new HashSet<tab_file_trasmessi>();
            this.tab_ispezioni_coattivo_new = new HashSet<tab_ispezioni_coattivo_new>();
            this.tab_richieste_rivestizione_liste = new HashSet<tab_richieste_rivestizione_liste>();
            this.tab_fatt_info = new HashSet<tab_fatt_info>();
            this.join_lst_emissione_lst_sped_not = new HashSet<join_lst_emissione_lst_sped_not>();
        }
    
        public int id_lista { get; set; }
        public int id_ente { get; set; }
        public int id_entrata { get; set; }
        public int id_tipo_lista { get; set; }
        public int id_tipo_avv_pag { get; set; }
        public string numero_lista { get; set; }
        public System.DateTime data_lista { get; set; }
        public Nullable<int> id_scadenza { get; set; }
        public Nullable<System.DateTime> data_scadenza_prima_rata { get; set; }
        public string num_avvpag { get; set; }
        public Nullable<decimal> imp_tot_lista { get; set; }
        public Nullable<decimal> imp_tot_imponibile { get; set; }
        public Nullable<decimal> imp_tot_iva { get; set; }
        public Nullable<decimal> imp_es_iva { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public Nullable<int> id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public string flag_spedizione_notifica { get; set; }
        public Nullable<int> id_tab_cc_riscossione { get; set; }
        public string descr_lista { get; set; }
        public Nullable<decimal> imp_tot_spese_notifica { get; set; }
        public string anno_rif { get; set; }
        public Nullable<System.DateTime> periodo_rif_da { get; set; }
        public Nullable<System.DateTime> periodo_rif_a { get; set; }
        public string anno_rif1 { get; set; }
        public Nullable<System.DateTime> periodo_rif_da1 { get; set; }
        public Nullable<System.DateTime> periodo_rif_a1 { get; set; }
        public string anno_rif2 { get; set; }
        public Nullable<System.DateTime> periodo_rif_da2 { get; set; }
        public Nullable<System.DateTime> periodo_rif_a2 { get; set; }
        public string anno_rif3 { get; set; }
        public Nullable<System.DateTime> periodo_rif_da3 { get; set; }
        public Nullable<System.DateTime> periodo_rif_a3 { get; set; }
        public string anno_rif4 { get; set; }
        public Nullable<System.DateTime> periodo_rif_da4 { get; set; }
        public Nullable<System.DateTime> periodo_rif_a4 { get; set; }
        public string flag_fognatura { get; set; }
        public string flag_letture { get; set; }
        public string flag_interventi { get; set; }
        public string flag_oggetti_variati { get; set; }
        public string flag_acconto { get; set; }
        public string flag_spese { get; set; }
        public Nullable<System.DateTime> data_ultimo_controllo_validita { get; set; }
        public Nullable<System.DateTime> data_scadenza_rata_unica { get; set; }
        public string parametri_calcolo { get; set; }
        public string identificativo_lista { get; set; }
        public string identificativo_lista_ente { get; set; }
        public Nullable<int> id_struttura_creazione { get; set; }
        public Nullable<int> id_risorsa_creazione { get; set; }
        public Nullable<System.DateTime> data_creazione { get; set; }
        public string checkCode { get; set; }
        public Nullable<int> id_struttura_approvazione { get; set; }
        public Nullable<int> id_risorsa_approvazione { get; set; }
        public Nullable<System.DateTime> data_approvazione { get; set; }
        public string numero_determina_approvazione { get; set; }
        public Nullable<int> id_lista_carico { get; set; }
        public string flag_presa_in_carico { get; set; }
    
        ///<summary><para>Relazione: FK_tab_liste_anagrafica_entrate</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_liste_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_liste_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_tab_liste_anagrafica_tipo_avv_pag</para> Chiave Origine: id_tipo_avv_pag</summary>
     public virtual anagrafica_tipo_avv_pag anagrafica_tipo_avv_pag { get; set; }
        ///<summary><para>Relazione: FK_join_controlli_avvpag_fatt_emissione_tab_liste</para> Chiave Origine: id_lista</summary>
     public virtual ICollection<join_controlli_avvpag_fatt_emissione> join_controlli_avvpag_fatt_emissione { get; set; }
        ///<summary><para>Relazione: FK_tab_avv_pag_tab_liste</para> Chiave Origine: id_lista_emissione</summary>
     public virtual ICollection<tab_avv_pag> tab_avv_pag { get; set; }
        ///<summary><para>Relazione: FK_tab_avv_pag_fatt_emissione_tab_liste</para> Chiave Origine: id_lista_emissione</summary>
     public virtual ICollection<tab_avv_pag_fatt_emissione> tab_avv_pag_fatt_emissione { get; set; }
        ///<summary><para>Relazione: FK_tab_avv_pag_fatt_rettifica_tab_liste</para> Chiave Origine: id_lista_emissione</summary>
     public virtual ICollection<tab_avv_pag_fatt_rettifica> tab_avv_pag_fatt_rettifica { get; set; }
        ///<summary><para>Relazione: FK_tab_avvisi_anomali_liste_carico_tab_liste</para> Chiave Origine: id_lista</summary>
     public virtual ICollection<tab_avvisi_anomali_liste_carico> tab_avvisi_anomali_liste_carico { get; set; }
        ///<summary><para>Relazione: FK_tab_controlli_qualita_liste_carico_tab_liste</para> Chiave Origine: id_lista</summary>
     public virtual ICollection<tab_controlli_qualita_liste_carico> tab_controlli_qualita_liste_carico { get; set; }
        ///<summary><para>Relazione: FK_tab_liste_tab_tipo_lista</para> Chiave Origine: id_tipo_lista</summary>
     public virtual tab_tipo_lista tab_tipo_lista { get; set; }
        ///<summary><para>Relazione: FK_tab_rilevazione_acquedotto_smart_tab_liste</para> Chiave Origine: id_lista</summary>
     public virtual ICollection<tab_rilevazione_acquedotto_smart> tab_rilevazione_acquedotto_smart { get; set; }
        ///<summary><para>Relazione: FK_tab_validazione_approvazione_liste_spedizione_tab_liste</para> Chiave Origine: id_lista</summary>
     public virtual ICollection<tab_validazione_approvazione_liste_spedizione> tab_validazione_approvazione_liste_spedizione { get; set; }
        ///<summary><para>Relazione: FK_tab_validazione_approvazione_liste_tab_liste</para> Chiave Origine: id_lista</summary>
     public virtual ICollection<tab_validazione_approvazione_liste> tab_validazione_approvazione_liste { get; set; }
        ///<summary><para>Relazione: FK_join_lista_voci_contribuzione_tab_liste</para> Chiave Origine: id_lista</summary>
     public virtual ICollection<join_lista_voci_contribuzione> join_lista_voci_contribuzione { get; set; }
        ///<summary><para>Relazione: FK_tab_liste_anagrafica_risorse1</para> Chiave Origine: id_risorsa_creazione</summary>
     public virtual anagrafica_risorse anagrafica_risorse1 { get; set; }
        ///<summary><para>Relazione: FK_tab_liste_anagrafica_risorse2</para> Chiave Origine: id_risorsa_approvazione</summary>
     public virtual anagrafica_risorse anagrafica_risorse2 { get; set; }
        ///<summary><para>Relazione: FK_tab_liste_anagrafica_strutture_aziendali1</para> Chiave Origine: id_struttura_creazione</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali1 { get; set; }
        ///<summary><para>Relazione: FK_tab_liste_anagrafica_strutture_aziendali2</para> Chiave Origine: id_struttura_approvazione</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali2 { get; set; }
        ///<summary><para>Relazione: FK_tab_avv_pag_tab_liste_di_scarico</para> Chiave Origine: id_lista_scarico</summary>
     public virtual ICollection<tab_avv_pag> tab_avv_pag1 { get; set; }
        ///<summary><para>Relazione: FK_tab_liste_tab_liste_carico</para> Chiave Origine: id_lista_carico</summary>
     public virtual ICollection<tab_liste> tab_liste1 { get; set; }
        ///<summary><para>Relazione: FK_tab_liste_tab_liste_carico</para> Chiave Origine: id_lista_carico</summary>
     public virtual tab_liste tab_liste2 { get; set; }
        ///<summary><para>Relazione: FK_tab_dett_lista_tab_liste</para> Chiave Origine: id_lista</summary>
     public virtual ICollection<tab_dett_lista> tab_dett_lista { get; set; }
        ///<summary><para>Relazione: FK_tab_lista_ente_gestito_tab_liste</para> Chiave Origine: id_lista</summary>
     public virtual ICollection<tab_lista_ente_gestito> tab_lista_ente_gestito { get; set; }
        ///<summary><para>Relazione: FK_tab_file_trasmessi_tab_liste</para> Chiave Origine: id_lista</summary>
     public virtual ICollection<tab_file_trasmessi> tab_file_trasmessi { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_new_tab_liste</para> Chiave Origine: id_lista_ispezione</summary>
     public virtual ICollection<tab_ispezioni_coattivo_new> tab_ispezioni_coattivo_new { get; set; }
        ///<summary><para>Relazione: FK_tab_richieste_rivestizione_liste_tab_liste</para> Chiave Origine: id_lista_da_rivestire</summary>
     public virtual ICollection<tab_richieste_rivestizione_liste> tab_richieste_rivestizione_liste { get; set; }
        ///<summary><para>Relazione: FK_tab_fatt_info_tab_liste</para> Chiave Origine: id_lista</summary>
     public virtual ICollection<tab_fatt_info> tab_fatt_info { get; set; }
        ///<summary><para>Relazione: FK_tab_liste_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
        ///<summary><para>Relazione: FK_join_lst_emissione_lst_sped_not_tab_liste1</para> Chiave Origine: id_lista_emissione</summary>
     public virtual ICollection<join_lst_emissione_lst_sped_not> join_lst_emissione_lst_sped_not { get; set; }
    }
}
