//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_prog_avvpag
    {
        public int id_prog_avvpag { get; set; }
        public int id_entrata { get; set; }
        public int id_tipo_avvpag { get; set; }
        public int anno { get; set; }
        public int prog_tipo_avvpag { get; set; }
        public Nullable<int> cronologico_sped_not { get; set; }
    
        ///<summary><para>Relazione: FK_tab_prog_avvpag_anagrafica_entrate</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_prog_avvpag_anagrafica_tipo_avv_pag</para> Chiave Origine: id_tipo_avvpag</summary>
     public virtual anagrafica_tipo_avv_pag anagrafica_tipo_avv_pag { get; set; }
    }
}
