//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_tipo_doc_entrate
    {
        public tab_tipo_doc_entrate()
        {
            this.anagrafica_categoria = new HashSet<anagrafica_categoria>();
            this.anagrafica_tipo_udienza = new HashSet<anagrafica_tipo_udienza>();
            this.join_causale_doc_new = new HashSet<join_causale_doc_new>();
            this.join_risorse_ser_comuni = new HashSet<join_risorse_ser_comuni>();
            this.tab_autorita_giudiziaria = new HashSet<tab_autorita_giudiziaria>();
            this.tab_categoria_tariffaria_ZTL = new HashSet<tab_categoria_tariffaria_ZTL>();
            this.tab_doc_input = new HashSet<tab_doc_input>();
            this.tab_doc_output = new HashSet<tab_doc_output>();
            this.tab_prog_doc = new HashSet<tab_prog_doc>();
            this.tab_lista_sped_notifiche = new HashSet<tab_lista_sped_notifiche>();
            this.tab_denunce_contratti = new HashSet<tab_denunce_contratti>();
            this.join_causali_motivazioni_causali_esito = new HashSet<join_causali_motivazioni_causali_esito>();
            this.tab_modalita_spednot_doc_output = new HashSet<tab_modalita_spednot_doc_output>();
            this.tab_fasce_pignorabilita_beni = new HashSet<tab_fasce_pignorabilita_beni>();
            this.tab_letture = new HashSet<tab_letture>();
            this.tab_registro_assegnazione_pratiche = new HashSet<tab_registro_assegnazione_pratiche>();
            this.tab_pec_configurazioni = new HashSet<tab_pec_configurazioni>();
        }
    
        public int id_tipo_doc_entrate { get; set; }
        public int id_entrata { get; set; }
        public int id_tipo_doc { get; set; }
        public string flag_doc_input_output { get; set; }
        public string descr_doc { get; set; }
        public string tipo_scadenza_pres { get; set; }
        public Nullable<int> id_scadenza_pres { get; set; }
        public Nullable<int> scadenza_gg_pres { get; set; }
        public string tipo_scadenza_risp { get; set; }
        public Nullable<int> id_scadenza_risp { get; set; }
        public Nullable<int> scadenza_gg_risp { get; set; }
        public string flag_pratiche_collegate { get; set; }
        public string flag_doc_allegati { get; set; }
        public string cod_tipo_doc { get; set; }
        public string desc_parte_ricorrente { get; set; }
        public string desc_parte_resistente { get; set; }
        public Nullable<decimal> importo_massimo_mediazione { get; set; }
        public Nullable<int> massimo_gg_mediazione { get; set; }
        public Nullable<int> massimo_gg_costituzione_giudizio_ricorrente { get; set; }
        public Nullable<int> massimo_gg_costituzione_giudizio_resistente { get; set; }
        public Nullable<int> minimo_gg_prima_udienza_italia { get; set; }
        public Nullable<int> minimo_gg_prima_udienza_estero { get; set; }
        public Nullable<int> minimo_gg_presentazione_memorie_ante_prima_udienza { get; set; }
        public Nullable<int> scadenza_gg_impugnazione_sentenza_su_notifica_parte { get; set; }
        public Nullable<int> scadenza_gg_impugnazione_sentenza_su_deposito { get; set; }
    
        ///<summary><para>Relazione: FK_anagrafica_categoria_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrata</summary>
     public virtual ICollection<anagrafica_categoria> anagrafica_categoria { get; set; }
        ///<summary><para>Relazione: FK_tab_tipo_doc_entrate_anagrafica_entrate</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_tipo_doc_entrate_anagrafica_entrate1</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate1 { get; set; }
        ///<summary><para>Relazione: FK_anagrafica_tipo_udienza_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrata</summary>
     public virtual ICollection<anagrafica_tipo_udienza> anagrafica_tipo_udienza { get; set; }
        ///<summary><para>Relazione: FK_join_causale_doc_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrate</summary>
     public virtual ICollection<join_causale_doc_new> join_causale_doc_new { get; set; }
        ///<summary><para>Relazione: FK_join_risorse_ser_comuni_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrate</summary>
     public virtual ICollection<join_risorse_ser_comuni> join_risorse_ser_comuni { get; set; }
        ///<summary><para>Relazione: FK_tab_autorita_giudiziaria_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrata</summary>
     public virtual ICollection<tab_autorita_giudiziaria> tab_autorita_giudiziaria { get; set; }
        ///<summary><para>Relazione: FK_tab_categoria_tariffaria_ZTL_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrata</summary>
     public virtual ICollection<tab_categoria_tariffaria_ZTL> tab_categoria_tariffaria_ZTL { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrate</summary>
     public virtual ICollection<tab_doc_input> tab_doc_input { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_output_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrate</summary>
     public virtual ICollection<tab_doc_output> tab_doc_output { get; set; }
        ///<summary><para>Relazione: FK_tab_prog_doc_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrate</summary>
     public virtual ICollection<tab_prog_doc> tab_prog_doc { get; set; }
        ///<summary><para>Relazione: FK_tab_lista_sped_notifiche_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrata</summary>
     public virtual ICollection<tab_lista_sped_notifiche> tab_lista_sped_notifiche { get; set; }
        ///<summary><para>Relazione: FK_tab_denunce_contratti_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrate</summary>
     public virtual ICollection<tab_denunce_contratti> tab_denunce_contratti { get; set; }
        ///<summary><para>Relazione: FK_join_causali_motivazioni_causali_esito_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrata_ricorso</summary>
     public virtual ICollection<join_causali_motivazioni_causali_esito> join_causali_motivazioni_causali_esito { get; set; }
        ///<summary><para>Relazione: FK_tab_modalita_spednot_doc_output_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrate</summary>
     public virtual ICollection<tab_modalita_spednot_doc_output> tab_modalita_spednot_doc_output { get; set; }
        ///<summary><para>Relazione: FK_tab_fasce_pignorabilita_beni_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrate</summary>
     public virtual ICollection<tab_fasce_pignorabilita_beni> tab_fasce_pignorabilita_beni { get; set; }
        ///<summary><para>Relazione: FK_tab_letture_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrata</summary>
     public virtual ICollection<tab_letture> tab_letture { get; set; }
        ///<summary><para>Relazione: FK_tab_registro_assegnazione_pratiche_tab_tipo_doc_entrate</para> Chiave Origine: tipo_pratica</summary>
     public virtual ICollection<tab_registro_assegnazione_pratiche> tab_registro_assegnazione_pratiche { get; set; }
        ///<summary><para>Relazione: FK_tab_pec_configurazioni_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrate</summary>
     public virtual ICollection<tab_pec_configurazioni> tab_pec_configurazioni { get; set; }
    }
}
