//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_rata_avv_pag_fatt_emissione
    {
        public int id_rata_avv_pag { get; set; }
        public int id_tab_avv_pag { get; set; }
        public int num_rata { get; set; }
        public string bar_code { get; set; }
        public Nullable<System.DateTime> dt_scadenza_rata { get; set; }
        public decimal imp_tot_rata { get; set; }
        public Nullable<decimal> imp_spese_notifica { get; set; }
        public decimal imp_pagato { get; set; }
        public string flag_pagamento { get; set; }
        public Nullable<System.DateTime> dt_pagamento { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public Nullable<decimal> imp_spese_coattive { get; set; }
        public Nullable<int> id_cc_riscossione { get; set; }
        public string Iuv_identificativo_pagamento { get; set; }
    
        ///<summary><para>Relazione: FK_tab_rata_avv_pag_fatt_emissione_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_rata_avv_pag_fatt_emissione_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_tab_rata_avv_pag_fatt_emissione_tab_avv_pag_fatt_emissione</para> Chiave Origine: id_tab_avv_pag</summary>
     public virtual tab_avv_pag_fatt_emissione tab_avv_pag_fatt_emissione { get; set; }
        ///<summary><para>Relazione: FK_tab_rata_avv_pag_fatt_emissione_tab_avv_pag_fatt_rettifica</para> Chiave Origine: id_tab_avv_pag</summary>
     public virtual tab_avv_pag_fatt_rettifica tab_avv_pag_fatt_rettifica { get; set; }
    }
}
