//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_ispezione_coattivo
    {
        public int id_tab_ispezione_coattivo { get; set; }
        public decimal id_contribuente { get; set; }
        public Nullable<int> id_ref { get; set; }
        public decimal tot_morosita { get; set; }
        public System.DateTime data_rilevazione_morosita { get; set; }
        public int id_lista_ispezione { get; set; }
        public string stato_procedure_esecutive { get; set; }
        public int id_ispettore { get; set; }
        public Nullable<System.DateTime> data_assegnazione_ispezione { get; set; }
        public Nullable<System.DateTime> data_fine_ispezione { get; set; }
        public string flag_veicoli_proprieta { get; set; }
        public Nullable<System.DateTime> data_rilevazione_veicolo { get; set; }
        public string flag_immobili { get; set; }
        public Nullable<System.DateTime> data_rilevazione_immobili { get; set; }
        public string flag_terzi { get; set; }
        public Nullable<System.DateTime> data_rilevazione_terzi { get; set; }
        public string flag_mobili { get; set; }
        public Nullable<System.DateTime> data_rilevazione_mobili { get; set; }
        public Nullable<int> id_tipo_avv_pag_da_emettere { get; set; }
        public Nullable<int> id_preavviso_emesso { get; set; }
        public Nullable<int> id_fermo_emesso { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public Nullable<System.DateTime> data_interrogazione { get; set; }
        public Nullable<System.DateTime> data_aggiornamento { get; set; }
        public int id_risorsa_stato { get; set; }
        public string flag_on_off { get; set; }
    
        ///<summary><para>Relazione: FK_tab_ispezione_coattivo_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezione_coattivo_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezione_coattivo_anagrafica_tipo_avv_pag</para> Chiave Origine: id_tipo_avv_pag_da_emettere</summary>
     public virtual anagrafica_tipo_avv_pag anagrafica_tipo_avv_pag { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezione_coattivo_tab_lista_sped_notifiche</para> Chiave Origine: id_lista_ispezione</summary>
     public virtual tab_lista_sped_notifiche tab_lista_sped_notifiche { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezione_coattivo_tab_contribuente</para> Chiave Origine: id_contribuente</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
    }
}
