//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_ispezioni_coattivo_v2
    {
        public int id_tab_ispezione_coattivo { get; set; }
        public int id_ente { get; set; }
        public decimal id_contribuente { get; set; }
        public int id_tipo_contribuente { get; set; }
        public string cfiscale_contribuente { get; set; }
        public string piva_contribuente { get; set; }
        public string cod_stato_contribuente { get; set; }
        public Nullable<int> id_tab_referente { get; set; }
        public string cfiscale_piva_soggetto_ispezione { get; set; }
        public Nullable<decimal> totale_morosita { get; set; }
        public Nullable<System.DateTime> data_rilevazione_morosita { get; set; }
        public string flag_ispezione_veicoli { get; set; }
        public Nullable<int> id_ispettore_veicoli { get; set; }
        public string flag_assegnazione_ispezione_veicoli { get; set; }
        public Nullable<System.DateTime> data_assegnazione_ispezione_veicoli { get; set; }
        public Nullable<System.DateTime> data_fine_ispezione_veicoli { get; set; }
        public string flag_esito_ispezione_veicoli { get; set; }
        public string flag_fine_ispezione_veicoli { get; set; }
        public string flag_ispezione_terzi { get; set; }
        public Nullable<int> id_ispettore_terzi { get; set; }
        public Nullable<int> id_risorsa_supervisione { get; set; }
        public string flag_assegnazione_ispezione_terzi { get; set; }
        public Nullable<System.DateTime> data_assegnazione_ispezione_terzi { get; set; }
        public Nullable<System.DateTime> data_fine_ispezione_terzi { get; set; }
        public string flag_esito_ispezione_terzi { get; set; }
        public string flag_fine_ispezione_terzi { get; set; }
        public string flag_ispezione_immobili { get; set; }
        public Nullable<int> id_ispettore_immobili { get; set; }
        public string flag_assegnazione_ispezione_immobili { get; set; }
        public Nullable<System.DateTime> data_assegnazione_ispezione_immobili { get; set; }
        public Nullable<System.DateTime> data_fine_ispezione_immobili { get; set; }
        public string flag_esito_ispezione_immobili { get; set; }
        public string flag_fine_ispezione_immobili { get; set; }
        public string flag_ispezione_mobili { get; set; }
        public Nullable<int> id_ispettore_mobili { get; set; }
        public string flag_assegnazione_ispezione_mobili { get; set; }
        public Nullable<System.DateTime> data_assegnazione_ispezione_mobili { get; set; }
        public Nullable<System.DateTime> data_fine_ispezione_mobili { get; set; }
        public string flag_esito_ispezione_mobili { get; set; }
        public string flag_fine_ispezione_mobili { get; set; }
        public Nullable<System.DateTime> data_fine_ispezione_totale { get; set; }
        public string flag_fine_ispezione_totale { get; set; }
        public string flag_esito_ispezione_totale { get; set; }
        public string flag_supervisione_finale { get; set; }
        public string flag_emissione_avviso_coattivo { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
    
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_v2_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_v2_anagrafica_risorse1</para> Chiave Origine: id_risorsa_supervisione</summary>
     public virtual anagrafica_risorse anagrafica_risorse1 { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_v2_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_v2_tab_contribuente</para> Chiave Origine: id_contribuente</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_v2_tab_referente</para> Chiave Origine: id_tab_referente</summary>
     public virtual tab_referente tab_referente { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_v2_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
    }
}
