//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_agevolazioni
    {
        public tab_agevolazioni()
        {
            this.join_oggetto_agevolazioni = new HashSet<join_oggetto_agevolazioni>();
            this.tab_agevolazioni_verifica = new HashSet<tab_agevolazioni_verifica>();
            this.tab_unita_contribuzione_fatt_rettifica = new HashSet<tab_unita_contribuzione_fatt_rettifica>();
            this.tab_unita_contribuzione_fatt_rettifica1 = new HashSet<tab_unita_contribuzione_fatt_rettifica>();
            this.tab_unita_contribuzione_fatt_rettifica2 = new HashSet<tab_unita_contribuzione_fatt_rettifica>();
            this.tab_unita_contribuzione_fatt_rettifica3 = new HashSet<tab_unita_contribuzione_fatt_rettifica>();
            this.tab_fatt_info = new HashSet<tab_fatt_info>();
            this.tab_unita_contribuzione_fatt_emissione = new HashSet<tab_unita_contribuzione_fatt_emissione>();
            this.tab_unita_contribuzione_fatt_emissione1 = new HashSet<tab_unita_contribuzione_fatt_emissione>();
            this.tab_unita_contribuzione_fatt_emissione2 = new HashSet<tab_unita_contribuzione_fatt_emissione>();
            this.tab_unita_contribuzione_fatt_emissione3 = new HashSet<tab_unita_contribuzione_fatt_emissione>();
            this.tab_unita_contribuzione = new HashSet<tab_unita_contribuzione>();
            this.tab_unita_contribuzione1 = new HashSet<tab_unita_contribuzione>();
            this.tab_unita_contribuzione2 = new HashSet<tab_unita_contribuzione>();
            this.tab_unita_contribuzione3 = new HashSet<tab_unita_contribuzione>();
        }
    
        public int id_tab_agevolazioni { get; set; }
        public Nullable<int> id_entrata { get; set; }
        public Nullable<int> id_anagrafica_agevolazione { get; set; }
        public Nullable<decimal> quantita_agevolazione { get; set; }
        public Nullable<System.DateTime> data_inizio_validita { get; set; }
        public Nullable<System.DateTime> data_fine_validita { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public Nullable<System.DateTime> data_stato { get; set; }
        public Nullable<int> id_struttura_stato { get; set; }
        public Nullable<int> id_risorsa_stato { get; set; }
    
        ///<summary><para>Relazione: FK_tab_agevolazioni_anagrafica_agevolazione</para> Chiave Origine: id_anagrafica_agevolazione</summary>
     public virtual anagrafica_agevolazione anagrafica_agevolazione { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_anagrafica_entrate</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_anagrafica_stato_agevolazione</para> Chiave Origine: id_stato</summary>
     public virtual anagrafica_stato_agevolazione anagrafica_stato_agevolazione { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_anagrafica_strutture_aziendali1</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_join_oggetto_agevolazioni_tab_agevolazioni</para> Chiave Origine: id_tab_agevolazioni</summary>
     public virtual ICollection<join_oggetto_agevolazioni> join_oggetto_agevolazioni { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_verifica_tab_agevolazioni</para> Chiave Origine: id_tab_agevolazioni</summary>
     public virtual ICollection<tab_agevolazioni_verifica> tab_agevolazioni_verifica { get; set; }
        ///<summary><para>Relazione: FK_tab_unita_contribuzione_fatt_rettifica_tab_agevolazioni</para> Chiave Origine: id_agevolazione1</summary>
     public virtual ICollection<tab_unita_contribuzione_fatt_rettifica> tab_unita_contribuzione_fatt_rettifica { get; set; }
        ///<summary><para>Relazione: FK_tab_unita_contribuzione_fatt_rettifica_tab_agevolazioni1</para> Chiave Origine: id_agevolazione2</summary>
     public virtual ICollection<tab_unita_contribuzione_fatt_rettifica> tab_unita_contribuzione_fatt_rettifica1 { get; set; }
        ///<summary><para>Relazione: FK_tab_unita_contribuzione_fatt_rettifica_tab_agevolazioni2</para> Chiave Origine: id_agevolazione3</summary>
     public virtual ICollection<tab_unita_contribuzione_fatt_rettifica> tab_unita_contribuzione_fatt_rettifica2 { get; set; }
        ///<summary><para>Relazione: FK_tab_unita_contribuzione_fatt_rettifica_tab_agevolazioni3</para> Chiave Origine: id_agevolazione4</summary>
     public virtual ICollection<tab_unita_contribuzione_fatt_rettifica> tab_unita_contribuzione_fatt_rettifica3 { get; set; }
        ///<summary><para>Relazione: FK_tab_fatt_info_tab_agevolazioni</para> Chiave Origine: id_bonus</summary>
     public virtual ICollection<tab_fatt_info> tab_fatt_info { get; set; }
        ///<summary><para>Relazione: FK_tab_unita_contribuzione_fatt_emissione_tab_agevolazioni</para> Chiave Origine: id_agevolazione1</summary>
     public virtual ICollection<tab_unita_contribuzione_fatt_emissione> tab_unita_contribuzione_fatt_emissione { get; set; }
        ///<summary><para>Relazione: FK_tab_unita_contribuzione_fatt_emissione_tab_agevolazioni1</para> Chiave Origine: id_agevolazione2</summary>
     public virtual ICollection<tab_unita_contribuzione_fatt_emissione> tab_unita_contribuzione_fatt_emissione1 { get; set; }
        ///<summary><para>Relazione: FK_tab_unita_contribuzione_fatt_emissione_tab_agevolazioni2</para> Chiave Origine: id_agevolazione3</summary>
     public virtual ICollection<tab_unita_contribuzione_fatt_emissione> tab_unita_contribuzione_fatt_emissione2 { get; set; }
        ///<summary><para>Relazione: FK_tab_unita_contribuzione_fatt_emissione_tab_agevolazioni3</para> Chiave Origine: id_agevolazione4</summary>
     public virtual ICollection<tab_unita_contribuzione_fatt_emissione> tab_unita_contribuzione_fatt_emissione3 { get; set; }
        ///<summary><para>Relazione: FK_tab_unita_contribuzione_tab_agevolazioni</para> Chiave Origine: id_agevolazione1</summary>
     public virtual ICollection<tab_unita_contribuzione> tab_unita_contribuzione { get; set; }
        ///<summary><para>Relazione: FK_tab_unita_contribuzione_tab_agevolazioni1</para> Chiave Origine: id_agevolazione2</summary>
     public virtual ICollection<tab_unita_contribuzione> tab_unita_contribuzione1 { get; set; }
        ///<summary><para>Relazione: FK_tab_unita_contribuzione_tab_agevolazioni2</para> Chiave Origine: id_agevolazione3</summary>
     public virtual ICollection<tab_unita_contribuzione> tab_unita_contribuzione2 { get; set; }
        ///<summary><para>Relazione: FK_tab_unita_contribuzione_tab_agevolazioni3</para> Chiave Origine: id_agevolazione4</summary>
     public virtual ICollection<tab_unita_contribuzione> tab_unita_contribuzione3 { get; set; }
    }
}
