//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_registro_giornaliero_riscossioni
    {
        public decimal id_registro_giornaliero { get; set; }
        public int prog_registro { get; set; }
        public string contribuente { get; set; }
        public int id_entrata { get; set; }
        public int id_tab_cc_riscossione { get; set; }
        public int id_tab_mov_pag { get; set; }
        public string flag_tipo_oggetto { get; set; }
        public Nullable<int> id_tipo_pagamento { get; set; }
        public Nullable<int> anno_riferimento { get; set; }
        public Nullable<System.DateTime> data_pagamento { get; set; }
        public Nullable<System.DateTime> data_accredito { get; set; }
        public string dettaglio_pagamento { get; set; }
        public string dettaglio_bolletta { get; set; }
        public string annotazioni { get; set; }
        public int id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
    
        ///<summary><para>Relazione: FK_tab_registro_giornaliero_riscossioni_anagrafica_entrate</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_registro_giornaliero_riscossioni_anagrafica_tipo_pagamento</para> Chiave Origine: id_tipo_pagamento</summary>
     public virtual anagrafica_tipo_pagamento anagrafica_tipo_pagamento { get; set; }
        ///<summary><para>Relazione: FK_tab_registro_giornaliero_riscossioni_tab_cc_riscossione</para> Chiave Origine: id_tab_cc_riscossione</summary>
     public virtual tab_cc_riscossione tab_cc_riscossione { get; set; }
        ///<summary><para>Relazione: FK_tab_registro_giornaliero_riscossioni_tab_mov_pag</para> Chiave Origine: id_tab_mov_pag</summary>
     public virtual tab_mov_pag tab_mov_pag { get; set; }
    }
}
