//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_domicilio
    {
        public tab_domicilio()
        {
            this.join_documenti_domiciliazioni = new HashSet<join_documenti_domiciliazioni>();
            this.tab_sped_not_fatt_emissione = new HashSet<tab_sped_not_fatt_emissione>();
            this.tab_sped_not = new HashSet<tab_sped_not>();
        }
    
        public int id_tab_domicilio { get; set; }
        public Nullable<decimal> id_anag_contribuente { get; set; }
        public Nullable<int> id_tab_referente { get; set; }
        public Nullable<int> id_utente { get; set; }
        public string cognome { get; set; }
        public string nome { get; set; }
        public string rag_sociale { get; set; }
        public string cod_fiscale { get; set; }
        public string p_iva { get; set; }
        public string casella_postale { get; set; }
        public Nullable<int> id_toponimo { get; set; }
        public string indirizzo { get; set; }
        public string edificio { get; set; }
        public Nullable<int> nr_civico { get; set; }
        public string sigla_civico { get; set; }
        public string scala { get; set; }
        public string piano { get; set; }
        public string interno { get; set; }
        public string condominio { get; set; }
        public string frazione { get; set; }
        public string stato { get; set; }
        public string citta { get; set; }
        public Nullable<int> cod_citta { get; set; }
        public string cap { get; set; }
        public string prov { get; set; }
        public Nullable<int> id_tipo { get; set; }
        public System.DateTime data_inizio { get; set; }
        public Nullable<System.DateTime> data_fine { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public string cod_stato { get; set; }
        public Nullable<decimal> km { get; set; }
        public Nullable<int> id_strada_db_poste { get; set; }
        public string colore { get; set; }
    
        ///<summary><para>Relazione: FK_tab_domicilio_anagrafica_tipo_contribuente</para> Chiave Origine: id_tipo</summary>
     public virtual anagrafica_tipo_contribuente anagrafica_tipo_contribuente { get; set; }
        ///<summary><para>Relazione: FK_join_doc_presentati_domiciliazioni_tab_domicilio</para> Chiave Origine: id_tab_domiciliazione</summary>
     public virtual ICollection<join_documenti_domiciliazioni> join_documenti_domiciliazioni { get; set; }
        ///<summary><para>Relazione: FK_tab_domicilio_tab_toponimi</para> Chiave Origine: id_toponimo</summary>
     public virtual tab_toponimi tab_toponimi { get; set; }
        ///<summary><para>Relazione: FK_tab_sped_not_fatt_emissione_tab_domicilio</para> Chiave Origine: id_domicilio</summary>
     public virtual ICollection<tab_sped_not_fatt_emissione> tab_sped_not_fatt_emissione { get; set; }
        ///<summary><para>Relazione: FK_tab_sped_not_tab_domicilio</para> Chiave Origine: id_domicilio</summary>
     public virtual ICollection<tab_sped_not> tab_sped_not { get; set; }
        ///<summary><para>Relazione: FK_tab_domicilio_tab_poste_strada</para> Chiave Origine: id_strada_db_poste</summary>
     public virtual tab_poste_strada tab_poste_strada { get; set; }
        ///<summary><para>Relazione: FK_tab_domicilio_tab_contribuente</para> Chiave Origine: id_anag_contribuente</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
        ///<summary><para>Relazione: FK_tab_domicilio_tab_referente</para> Chiave Origine: id_tab_referente</summary>
     public virtual tab_referente tab_referente { get; set; }
        ///<summary><para>Relazione: FK_tab_domicilio_tab_utenti</para> Chiave Origine: id_utente</summary>
     public virtual tab_utenti tab_utenti { get; set; }
    }
}
