//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_locazione_soggetto
    {
        public int id_locazione_propr_inquilino { get; set; }
        public int id_locazione_contratto { get; set; }
        public Nullable<System.DateTime> data_file { get; set; }
        public string ufficio { get; set; }
        public Nullable<int> anno { get; set; }
        public string serie { get; set; }
        public Nullable<int> numero_reg { get; set; }
        public Nullable<int> sottonumero_reg { get; set; }
        public Nullable<int> progr_negozio { get; set; }
        public Nullable<int> progr_soggetto { get; set; }
        public string tipo_soggetto { get; set; }
        public string codice_fiscale { get; set; }
        public string sesso { get; set; }
        public string citta_nas { get; set; }
        public string prov_nas { get; set; }
        public Nullable<System.DateTime> data_nas { get; set; }
        public string citta_res { get; set; }
        public string prov_res { get; set; }
        public string indirizzo_res { get; set; }
        public string nr_civico { get; set; }
        public Nullable<System.DateTime> data_subentro { get; set; }
        public Nullable<System.DateTime> data_cessione { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
    
        ///<summary><para>Relazione: FK_tab_locazione_soggetto_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_locazione_soggetto_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_tab_locazione_soggetto_tab_locazione_contratto</para> Chiave Origine: id_locazione_contratto</summary>
     public virtual tab_locazione_contratto tab_locazione_contratto { get; set; }
    }
}
