//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_fermi_azioni_manuali
    {
        public int id_fermi_azioni_manuali { get; set; }
        public string w_user_name { get; set; }
        public string w_user_last_action { get; set; }
        public string cf_piva { get; set; }
        public string targa { get; set; }
        public string cf_piva_nuovo_proprietario { get; set; }
        public string tipo_veicolo_AMR { get; set; }
        public string tipo_pratica { get; set; }
        public string procedura { get; set; }
        public string codice_formalita { get; set; }
        public string tipo_provvedimento { get; set; }
        public string vincolo_isc_rp_formalita_trascrizione { get; set; }
        public string vincolo_isc_data_vincolo { get; set; }
        public string vincolo_isc_data_formalita_trascrizione { get; set; }
        public string vincolo_ufficio_pra_competente { get; set; }
        public string vincolo_isc_provincia_rp_formalita_trascrizione { get; set; }
        public string crea_pratica_codice_di_ritorno { get; set; }
        public string crea_pratica_id_pratica { get; set; }
        public string presenta_formalita_numero_protocollo { get; set; }
        public string leggi_pratica_codice_stato { get; set; }
        public string leggi_pratica_descrizione_stato { get; set; }
        public string errori { get; set; }
        public Nullable<System.DateTime> data_stato { get; set; }
    }
}
