//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_ispezioni_coattivo_new
    {
        public tab_ispezioni_coattivo_new()
        {
            this.join_ispezioni_ingiunzioni = new HashSet<join_ispezioni_ingiunzioni>();
            this.join_tab_ispezioni_coattivo_tipo_ispezione = new HashSet<join_tab_ispezioni_coattivo_tipo_ispezione>();
            this.tab_profilo_contribuente_new = new HashSet<tab_profilo_contribuente_new>();
            this.TAB_SUPERVISIONE_FINALE_V2 = new HashSet<TAB_SUPERVISIONE_FINALE_V2>();
        }
    
        public int id_tab_ispezione_coattivo { get; set; }
        public int id_ente { get; set; }
        public decimal id_contribuente { get; set; }
        public int id_tipo_contribuente { get; set; }
        public string cfiscale_contribuente { get; set; }
        public string piva_contribuente { get; set; }
        public string cod_stato_contribuente { get; set; }
        public Nullable<int> id_tab_referente { get; set; }
        public string cfiscale_piva_soggetto_ispezione { get; set; }
        public Nullable<decimal> totale_morosita { get; set; }
        public Nullable<System.DateTime> data_rilevazione_morosita { get; set; }
        public Nullable<decimal> percentuale_morosita_coobbligato { get; set; }
        public Nullable<decimal> totale_morosita_soggetto_ispezione { get; set; }
        public Nullable<System.DateTime> data_fine_ispezione_totale { get; set; }
        public string flag_fine_ispezione_totale { get; set; }
        public string flag_esito_ispezione_totale { get; set; }
        public Nullable<int> id_risorsa_supervisione { get; set; }
        public string flag_supervisione_finale { get; set; }
        public string flag_emissione_avviso_coattivo { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public Nullable<int> id_lista_ispezione { get; set; }
        public Nullable<decimal> importo_morosita_atti_esecutivi { get; set; }
        public Nullable<int> id_tab_ispezione_coattivo_soggetto_supervisione { get; set; }
        public Nullable<int> id_tab_supervisione { get; set; }
        public Nullable<decimal> totale_morosita_assoggettabile_preavviso_fermo { get; set; }
        public Nullable<decimal> totale_morosita_assoggettabile_preavviso_ipoteca { get; set; }
        public Nullable<decimal> totale_morosita_assoggettabile_atti_esecutivi { get; set; }
    
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_new_anagrafica_risorse</para> Chiave Origine: id_risorsa_supervisione</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_new_anagrafica_risorse1</para> Chiave Origine: id_risorsa_supervisione</summary>
     public virtual anagrafica_risorse anagrafica_risorse1 { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_new_anagrafica_tipo_contribuente</para> Chiave Origine: id_tipo_contribuente</summary>
     public virtual anagrafica_tipo_contribuente anagrafica_tipo_contribuente { get; set; }
        ///<summary><para>Relazione: FK_join_ispezioni_ingiunzioni_tab_ispezioni_coattivo_new</para> Chiave Origine: id_tab_ispezione_coattivo</summary>
     public virtual ICollection<join_ispezioni_ingiunzioni> join_ispezioni_ingiunzioni { get; set; }
        ///<summary><para>Relazione: FK_join_tab_ispezioni_coattivo_tipo_ispezione_tab_ispezioni_coattivo_new</para> Chiave Origine: id_tab_ispezione_coattivo</summary>
     public virtual ICollection<join_tab_ispezioni_coattivo_tipo_ispezione> join_tab_ispezioni_coattivo_tipo_ispezione { get; set; }
        ///<summary><para>Relazione: FK_tab_profilo_contribuente_new_tab_ispezioni_coattivo_new</para> Chiave Origine: id_tab_ispezione_coattivo</summary>
     public virtual ICollection<tab_profilo_contribuente_new> tab_profilo_contribuente_new { get; set; }
        ///<summary><para>Relazione: FK_TAB_SUPERVISIONE_FINALE_V2_tab_ispezioni_coattivo_new</para> Chiave Origine: ID_TAB_ISPEZIONE_COATTIVO</summary>
     public virtual ICollection<TAB_SUPERVISIONE_FINALE_V2> TAB_SUPERVISIONE_FINALE_V2 { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_new_tab_liste</para> Chiave Origine: id_lista_ispezione</summary>
     public virtual tab_liste tab_liste { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_new_TAB_SUPERVISIONE_FINALE_V2</para> Chiave Origine: id_tab_supervisione</summary>
     public virtual TAB_SUPERVISIONE_FINALE_V2 TAB_SUPERVISIONE_FINALE_V21 { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_new_tab_contribuente</para> Chiave Origine: id_contribuente</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_new_tab_referente</para> Chiave Origine: id_tab_referente</summary>
     public virtual tab_referente tab_referente { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezioni_coattivo_new_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
    }
}
