//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_tipo_bene
    {
        public tab_tipo_bene()
        {
            this.tab_profilo_contribuente_new = new HashSet<tab_profilo_contribuente_new>();
            this.tab_terzo_debitore = new HashSet<tab_terzo_debitore>();
            this.tab_terzo = new HashSet<tab_terzo>();
            this.tab_fasce_pignorabilita_beni = new HashSet<tab_fasce_pignorabilita_beni>();
            this.tab_citazioni = new HashSet<tab_citazioni>();
            this.join_tab_avv_pag_tab_doc_input = new HashSet<join_tab_avv_pag_tab_doc_input>();
        }
    
        public int id_tipo_bene { get; set; }
        public string descrizione { get; set; }
        public string codice_bene { get; set; }
        public int id_tab_tipo_ispezione { get; set; }
        public int giorni_validita_bene { get; set; }
    
        ///<summary><para>Relazione: FK_tab_profilo_contribuente_new_tab_tipo_bene</para> Chiave Origine: id_tipo_bene</summary>
     public virtual ICollection<tab_profilo_contribuente_new> tab_profilo_contribuente_new { get; set; }
        ///<summary><para>Relazione: FK_tab_terzo_debitore_tab_tipo_bene</para> Chiave Origine: id_tipo_bene</summary>
     public virtual ICollection<tab_terzo_debitore> tab_terzo_debitore { get; set; }
        ///<summary><para>Relazione: FK_tab_tipo_bene_tab_tipo_ispezione</para> Chiave Origine: id_tab_tipo_ispezione</summary>
     public virtual tab_tipo_ispezione tab_tipo_ispezione { get; set; }
        ///<summary><para>Relazione: FK_tab_terzo_tab_tipo_bene</para> Chiave Origine: id_tipo_bene_riferimento</summary>
     public virtual ICollection<tab_terzo> tab_terzo { get; set; }
        ///<summary><para>Relazione: FK_tab_fasce_pignorabilita_beni_tab_tipo_bene</para> Chiave Origine: id_tipo_bene</summary>
     public virtual ICollection<tab_fasce_pignorabilita_beni> tab_fasce_pignorabilita_beni { get; set; }
        ///<summary><para>Relazione: FK_tab_citazioni_tab_tipo_bene</para> Chiave Origine: id_tipo_bene</summary>
     public virtual ICollection<tab_citazioni> tab_citazioni { get; set; }
        ///<summary><para>Relazione: FK_join_tab_avv_pag_tab_doc_input_tab_tipo_bene</para> Chiave Origine: id_tipo_bene</summary>
     public virtual ICollection<join_tab_avv_pag_tab_doc_input> join_tab_avv_pag_tab_doc_input { get; set; }
    }
}
