//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_parametri_portale
    {
        public int id_tab_parametri_portale { get; set; }
        public string mode { get; set; }
        public string icona_procedura { get; set; }
        public string icona_funzionalita { get; set; }
        public string icona_applicazione { get; set; }
        public int id_struttura_aziendale { get; set; }
        public int id_risorsa { get; set; }
        public string path_upload_file { get; set; }
        public string url_img { get; set; }
        public string url_img_anagrafica { get; set; }
        public string path_notifiche { get; set; }
        public string path_bollettini { get; set; }
        public string path_avvisi { get; set; }
        public string path_icp { get; set; }
        public string path_tosap { get; set; }
        public string path_cosap { get; set; }
        public string path_allegati { get; set; }
        public string path_rendiconti { get; set; }
        public string path_tabdocinput { get; set; }
        public string path_esito { get; set; }
        public string path_file_trasmessi { get; set; }
        public string path_fascicoli { get; set; }
        public string path_esito_pec { get; set; }
        public string url_img_pagopa { get; set; }
    
        ///<summary><para>Relazione: FK_tab_parametri_portale_anagrafica_risorse</para> Chiave Origine: id_risorsa</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_parametri_portale_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_aziendale</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
    }
}
