//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_autorita_giudiziaria
    {
        public tab_autorita_giudiziaria()
        {
            this.tab_generale_udienze = new HashSet<tab_generale_udienze>();
            this.tab_doc_input = new HashSet<tab_doc_input>();
            this.tab_ipoteche = new HashSet<tab_ipoteche>();
            this.tab_spese_giudizio = new HashSet<tab_spese_giudizio>();
            this.tab_ricorsi = new HashSet<tab_ricorsi>();
            this.tab_citazioni = new HashSet<tab_citazioni>();
            this.tab_procedure_concorsuali = new HashSet<tab_procedure_concorsuali>();
            this.tab_registro_assegnazione_pratiche = new HashSet<tab_registro_assegnazione_pratiche>();
        }
    
        public int id_tab_autorita_giudiziaria { get; set; }
        public Nullable<int> id_tipo_doc_entrata { get; set; }
        public string sigla_autorita { get; set; }
        public string descrizione_autorita { get; set; }
        public string territorio_competenza { get; set; }
        public string comune_ubicazione { get; set; }
        public string cap_ubicazione { get; set; }
        public string indirizzo_ubicazione { get; set; }
        public string pec_cancelleria_autorita { get; set; }
        public Nullable<int> codice_tribunale { get; set; }
        public Nullable<int> cod_comune { get; set; }
    
        ///<summary><para>Relazione: FK_tab_autorita_giudiziaria_ser_comuni</para> Chiave Origine: cod_comune</summary>
     public virtual ser_comuni ser_comuni { get; set; }
        ///<summary><para>Relazione: FK_tab_generale_udienze_tab_autorita_giudiziaria</para> Chiave Origine: id_autorita_giudiziaria</summary>
     public virtual ICollection<tab_generale_udienze> tab_generale_udienze { get; set; }
        ///<summary><para>Relazione: FK_tab_doc_input_tab_autorita_giudiziaria</para> Chiave Origine: id_autorita_giudiziaria</summary>
     public virtual ICollection<tab_doc_input> tab_doc_input { get; set; }
        ///<summary><para>Relazione: FK_tab_ipoteche_tab_autorita_giudiziaria</para> Chiave Origine: id_autorita_giudiziaria</summary>
     public virtual ICollection<tab_ipoteche> tab_ipoteche { get; set; }
        ///<summary><para>Relazione: FK_tab_spese_giudizio_tab_autorita_giudiziaria</para> Chiave Origine: id_autorita_giudiziaria</summary>
     public virtual ICollection<tab_spese_giudizio> tab_spese_giudizio { get; set; }
        ///<summary><para>Relazione: FK_tab_autorita_giudiziaria_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrata</summary>
     public virtual tab_tipo_doc_entrate tab_tipo_doc_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_ricorsi_tab_autorita_giudiziaria</para> Chiave Origine: id_tab_autorita_giudiziaria_ricorso</summary>
     public virtual ICollection<tab_ricorsi> tab_ricorsi { get; set; }
        ///<summary><para>Relazione: FK_tab_citazioni_tab_autorita_giudiziaria</para> Chiave Origine: id_tab_autorita_giudiziaria</summary>
     public virtual ICollection<tab_citazioni> tab_citazioni { get; set; }
        ///<summary><para>Relazione: FK_tab_procedure_concorsuali_tab_autorita_giudiziaria</para> Chiave Origine: id_tab_autorita_giudiziaria</summary>
     public virtual ICollection<tab_procedure_concorsuali> tab_procedure_concorsuali { get; set; }
        ///<summary><para>Relazione: FK_tab_registro_assegnazione_pratiche_tab_autorita_giudiziaria</para> Chiave Origine: id_autorita_giudiziaria</summary>
     public virtual ICollection<tab_registro_assegnazione_pratiche> tab_registro_assegnazione_pratiche { get; set; }
    }
}
