//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_f24_z1
    {
        public int id_z1 { get; set; }
        public int id_tab_f24_a1 { get; set; }
        public string tipo_record { get; set; }
        public System.DateTime data_fornitura { get; set; }
        public int progressivo_fornitura { get; set; }
        public Nullable<int> numero_trasmissione { get; set; }
        public string codice_valuta { get; set; }
        public string codice_ente_comunale { get; set; }
        public Nullable<int> codice_intermediario { get; set; }
        public string identificativo_file { get; set; }
        public Nullable<int> numero_record_g1 { get; set; }
        public Nullable<int> numero_record_g2 { get; set; }
        public Nullable<int> numero_record_g3 { get; set; }
        public Nullable<int> numero_record_g4 { get; set; }
        public Nullable<int> numero_record_g5 { get; set; }
        public Nullable<int> numero_record_g9 { get; set; }
        public Nullable<int> numero_record_totale { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public Nullable<int> id_struttura_stato { get; set; }
        public Nullable<int> id_risorsa_stato { get; set; }
    }
}
