//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_delibere_determine_tariffarie
    {
        public tab_delibere_determine_tariffarie()
        {
            this.join_tipo_avvpag_voci_contrib_new = new HashSet<join_tipo_avvpag_voci_contrib_new>();
            this.tab_calcolo_tipo_voci_contribuzione = new HashSet<tab_calcolo_tipo_voci_contribuzione>();
            this.tab_rateizzazioni = new HashSet<tab_rateizzazioni>();
        }
    
        public int id_delibera_determina { get; set; }
        public int id_ente { get; set; }
        public int id_ente_gestito { get; set; }
        public string tipo_delibera_determina { get; set; }
        public string numero { get; set; }
        public string descrizione { get; set; }
        public string nominativo_determina { get; set; }
        public int id_ruolo_mansione { get; set; }
        public System.DateTime data_emissione { get; set; }
        public System.DateTime data_inizio_validita { get; set; }
        public System.DateTime data_fine_validita { get; set; }
    
        ///<summary><para>Relazione: FK_tab_delibere_determine_tariffarie_anagrafica_ente_gestito</para> Chiave Origine: id_ente_gestito</summary>
     public virtual anagrafica_ente_gestito anagrafica_ente_gestito { get; set; }
        ///<summary><para>Relazione: FK_tab_delibere_determine_tariffarie_anagrafica_ruolo_mansione</para> Chiave Origine: id_ruolo_mansione</summary>
     public virtual anagrafica_ruolo_mansione anagrafica_ruolo_mansione { get; set; }
        ///<summary><para>Relazione: FK_join_tipo_avvpag_voci_contrib_new_tab_delibere_determine_tariffarie</para> Chiave Origine: id_delibera_determina</summary>
     public virtual ICollection<join_tipo_avvpag_voci_contrib_new> join_tipo_avvpag_voci_contrib_new { get; set; }
        ///<summary><para>Relazione: FK_tab_calcolo_tipo_voci_contribuzione_tab_delibere_determine_tariffarie</para> Chiave Origine: id_delibera_determina</summary>
     public virtual ICollection<tab_calcolo_tipo_voci_contribuzione> tab_calcolo_tipo_voci_contribuzione { get; set; }
        ///<summary><para>Relazione: FK_tab_rateizzazioni_tab_delibere_determine_tariffarie</para> Chiave Origine: id_delibera_determina</summary>
     public virtual ICollection<tab_rateizzazioni> tab_rateizzazioni { get; set; }
        ///<summary><para>Relazione: FK_tab_delibere_determine_tariffarie_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
    }
}
