//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_dati_metrici_dichiarati
    {
        public tab_dati_metrici_dichiarati()
        {
            this.join_denunce_doc_input = new HashSet<join_denunce_doc_input>();
            this.join_oggetto_dati_metrici = new HashSet<join_oggetto_dati_metrici>();
        }
    
        public int id_tab_dati_metrici_dichiarati { get; set; }
        public Nullable<int> id_categoria_catastale { get; set; }
        public Nullable<int> id_immobile_catastale { get; set; }
        public string foglio { get; set; }
        public string numero { get; set; }
        public string particella { get; set; }
        public string subalterno { get; set; }
        public string num_protocollo_imm_non_accastato { get; set; }
        public Nullable<System.DateTime> data_protocollo_imm_non_accastato { get; set; }
        public Nullable<decimal> valore_rendita_provvisoria { get; set; }
        public string num_protocollo_ute_rendita_definitiva { get; set; }
        public Nullable<System.DateTime> data_protocollo_ute_rendita_definitiva { get; set; }
        public Nullable<System.DateTime> data_efficiacia_rendita_definitiva { get; set; }
        public Nullable<decimal> valore_rendita_definitiva { get; set; }
        public Nullable<int> id_tipologia_1 { get; set; }
        public Nullable<decimal> superfice_dichiarata_tipologia_1 { get; set; }
        public Nullable<int> id_tipologia_2 { get; set; }
        public Nullable<decimal> superfice_dichiarata_tipologia_2 { get; set; }
        public Nullable<int> id_tipologia_3 { get; set; }
        public Nullable<decimal> superfice_dichiarata_tipologia_3 { get; set; }
        public Nullable<int> id_tipologia_4 { get; set; }
        public Nullable<decimal> superfice_dichiarata_tipologia_4 { get; set; }
        public Nullable<int> id_tipologia_5 { get; set; }
        public Nullable<decimal> superfice_dichiarata_tipologia_5 { get; set; }
        public Nullable<int> id_tipologia_6 { get; set; }
        public Nullable<decimal> superfice_dichiarata_tipologia_6 { get; set; }
        public Nullable<int> id_tipologia_7 { get; set; }
        public Nullable<decimal> superfice_dichiarata_tipologia_7 { get; set; }
        public Nullable<int> id_tipologia_8 { get; set; }
        public Nullable<decimal> superfice_dichiarata_tipologia_8 { get; set; }
        public Nullable<int> id_tipologia_9 { get; set; }
        public Nullable<decimal> superfice_dichiarata_tipologia_9 { get; set; }
        public Nullable<int> id_tipologia_10 { get; set; }
        public Nullable<decimal> superfice_dichiarata_tipologia_10 { get; set; }
        public Nullable<decimal> superficie_min_tarsu { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
    
        ///<summary><para>Relazione: FK_tab_dati_metrici_dichiarati_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_dati_metrici_dichiarati_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_join_denunce_doc_input_tab_dati_metrici_dichiarati</para> Chiave Origine: id_dati_catastali</summary>
     public virtual ICollection<join_denunce_doc_input> join_denunce_doc_input { get; set; }
        ///<summary><para>Relazione: FK_join_oggetto_dati_metrici_tab_dati_metrici_dichiarati</para> Chiave Origine: id_dati_metrici_dichiarati</summary>
     public virtual ICollection<join_oggetto_dati_metrici> join_oggetto_dati_metrici { get; set; }
    }
}
