//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_qualita_terreno
    {
        public tab_qualita_terreno()
        {
            this.tab_terreni = new HashSet<tab_terreni>();
            this.tab_immobili_coattivo = new HashSet<tab_immobili_coattivo>();
        }
    
        public int id_tab_qualita_terreno { get; set; }
        public string codice { get; set; }
        public string descrizione { get; set; }
        public int id_utilizzo_ente_imu { get; set; }
        public int id_utilizzo_ente_ici { get; set; }
    
        ///<summary><para>Relazione: FK_tab_qualita_terreno_anagrafica_utilizzo_ici</para> Chiave Origine: id_utilizzo_ente_ici</summary>
     public virtual anagrafica_utilizzo anagrafica_utilizzo { get; set; }
        ///<summary><para>Relazione: FK_tab_qualita_terreno_anagrafica_utilizzo_imu</para> Chiave Origine: id_utilizzo_ente_imu</summary>
     public virtual anagrafica_utilizzo anagrafica_utilizzo1 { get; set; }
        ///<summary><para>Relazione: FK_tab_terreni_tab_qualita_terreno</para> Chiave Origine: id_tab_qualita_terreno</summary>
     public virtual ICollection<tab_terreni> tab_terreni { get; set; }
        ///<summary><para>Relazione: FK_tab_immobili_coattivo_tab_qualita_terreno</para> Chiave Origine: id_tab_qualita_terreno</summary>
     public virtual ICollection<tab_immobili_coattivo> tab_immobili_coattivo { get; set; }
    }
}
