//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_rilevazione_acquedotto_smart
    {
        public int id_tab_rilevazione_acquedotto_smart { get; set; }
        public Nullable<int> id_rilevatore { get; set; }
        public string flag_utenza_nuova_abusiva { get; set; }
        public Nullable<decimal> id_tab_rilevazione_acquedotto { get; set; }
        public Nullable<decimal> id_tab_rilevazione_acquedotto_dettaglio { get; set; }
        public int id_ente { get; set; }
        public string descrizione_ente { get; set; }
        public int id_ente_gestito { get; set; }
        public string descrizione_ente_gestito { get; set; }
        public Nullable<int> id_lista { get; set; }
        public string cod_lista { get; set; }
        public Nullable<int> anno_lista { get; set; }
        public string numero_lista { get; set; }
        public string descrizione_lista { get; set; }
        public Nullable<int> numero_rilevazione { get; set; }
        public Nullable<int> cod_comune { get; set; }
        public int id_zona { get; set; }
        public string descrizione_zona { get; set; }
        public int id_area { get; set; }
        public int id_tipo_toponimo { get; set; }
        public string descrizione_tipo_toponimo { get; set; }
        public int id_toponimo { get; set; }
        public string descrizione_toponimo { get; set; }
        public Nullable<int> num_civico_da_ubi_utenza { get; set; }
        public string sigla_civico_da_ubi_utenza { get; set; }
        public Nullable<int> num_civico_a_ubi_utenza { get; set; }
        public string sigla_civico_a_ubi_utenza { get; set; }
        public string scala_ubi_utenza { get; set; }
        public string piano_ubi_utenza { get; set; }
        public string interno_ubi_utenza { get; set; }
        public string edificio_ubi_utenza { get; set; }
        public string condominio_ubi_utenza { get; set; }
        public string frazione_ubi_utenza { get; set; }
        public string comune_ubi_utenza { get; set; }
        public string codice_utenza { get; set; }
        public string descrizione_tipo_utenza { get; set; }
        public string descrizione_categoria_tariffaria_utenza { get; set; }
        public string catasto_foglio_utenza { get; set; }
        public string catasto_numero_utenza { get; set; }
        public string catasto_particella_utenza { get; set; }
        public string catasto_sub_utenza { get; set; }
        public string matricola_contatore { get; set; }
        public string priorita { get; set; }
        public string flag_ubicazione_contatore { get; set; }
        public string descrizione_ubicazione_contatore { get; set; }
        public string descrizione_ubicazione_contatore_aggiuntiva { get; set; }
        public Nullable<decimal> ultima_lettura { get; set; }
        public Nullable<System.DateTime> data_ultima_lettura { get; set; }
        public Nullable<decimal> prodie_ultimo_addebito { get; set; }
        public Nullable<decimal> prodie_totale { get; set; }
        public string cod_stato_contatore { get; set; }
        public string descrizione_stato_contatore { get; set; }
        public string flag_singolo_generale { get; set; }
        public string flag_num_lancetta { get; set; }
        public string tipo { get; set; }
        public string diametro { get; set; }
        public string num_cifre_quadrante { get; set; }
        public string flag_giro_completo { get; set; }
        public string flag_autoclave { get; set; }
        public string flag_utenza_censita_non_contrattualizzata { get; set; }
        public string tipo_contribuente_intestatario { get; set; }
        public string rag_sociale_intestatario { get; set; }
        public string cognome_intestatario { get; set; }
        public string nome_intestatario { get; set; }
        public string cod_fiscale_intestatario { get; set; }
        public string p_iva_intestatario { get; set; }
        public string flag_morosita { get; set; }
        public string tipo_indirizzo_intestatario { get; set; }
        public string indirizzo_intestatario { get; set; }
        public string edificio_intestatario { get; set; }
        public Nullable<int> num_civico_intestatario { get; set; }
        public string sigla_civico_intestatario { get; set; }
        public string scala_intestatario { get; set; }
        public string piano_intestatario { get; set; }
        public string interno_intestatario { get; set; }
        public string condominio_intestatario { get; set; }
        public string frazione_intestatario { get; set; }
        public string stato_intestatario { get; set; }
        public string citta_intestatario { get; set; }
        public Nullable<int> cod_citta_intestatario { get; set; }
        public string cap_intestatario { get; set; }
        public string prov_intestatario { get; set; }
        public string coabitante_1_intestatario { get; set; }
        public string coabitante_2_intestatario { get; set; }
        public string coabitante_3_intestatario { get; set; }
        public string flag_intestatario_occupante { get; set; }
        public string tipo_occupante_non_intestatario { get; set; }
        public string cognome_occupante_non_intestataio { get; set; }
        public string nome_occupante_non_intestatario { get; set; }
        public string ragione_sociale_occupante_non_intestatario { get; set; }
        public string ril_intestatario_occupante { get; set; }
        public string ril_verifica_occupante { get; set; }
        public string ril_occupante_sconosciuto { get; set; }
        public string ril_occupante_deceduto { get; set; }
        public string ril_occupante_trasferito { get; set; }
        public string ril_tipo_occupante_non_intestatario { get; set; }
        public string ril_cognome_occupante_non_intestatario { get; set; }
        public string ril_nome_occupante_non_intestatario { get; set; }
        public string ril_ragione_sociale_occupante_non_intestatario { get; set; }
        public string ril_matric_contat_inesist_ad_indirizzo_utenza { get; set; }
        public Nullable<int> ril_var_num_civico_da_ubi_utenza { get; set; }
        public string ril_var_sigla_civico_da_ubi_utenza { get; set; }
        public Nullable<int> ril_var_num_civico_a_ubi_utenza { get; set; }
        public string ril_var_sigla_civico_a_ubi_utenza { get; set; }
        public string ril_var_scala_ubi_utenza { get; set; }
        public string ril_var_piano_ubi_utenza { get; set; }
        public string ril_var_interno_ubi_utenza { get; set; }
        public string ril_var_edificio_ubi_utenza { get; set; }
        public string ril_var_condominio_ubi_utenza { get; set; }
        public string ril_var_frazione_ubi_utenza { get; set; }
        public string ril_var_descrizione_tipo_utenza { get; set; }
        public string ril_var_descrizione_categoria_tariffaria_utenza { get; set; }
        public string ril_var_catasto_foglio_utenza { get; set; }
        public string ril_var_catasto_numero_utenza { get; set; }
        public string ril_var_catasto_particella_utenza { get; set; }
        public string ril_var_catasto_sub_utenza { get; set; }
        public string ril_flag_ubicazione_contatore { get; set; }
        public string ril_ubicazione_contatore { get; set; }
        public string ril_ubicazione_contatore_aggiuntiva { get; set; }
        public string ril_latitudine { get; set; }
        public string ril_longitudine { get; set; }
        public string ril_tipo_lettura { get; set; }
        public Nullable<decimal> ril_nuova_lettura { get; set; }
        public Nullable<System.DateTime> ril_data_nuova_lettura { get; set; }
        public Nullable<decimal> ril_nuovo_pro_die { get; set; }
        public string ril_flag_pro_die_anomalo { get; set; }
        public string ril_flag_anomalie { get; set; }
        public string ril_contatore_matricola_inesistente { get; set; }
        public string ril_contatore_giro_completo_cifre { get; set; }
        public string ril_contatore_guasto { get; set; }
        public string ril_contatore_manomesso { get; set; }
        public string ril_contatore_quadrante_illeggibile { get; set; }
        public string ril_contatore_inaccessibilita { get; set; }
        public string ril_contatore_non_sigillato { get; set; }
        public string ril_contatore_matricola_illeggibile { get; set; }
        public string ril_contatore_montaggio_errato { get; set; }
        public string ril_perdita_da_risolvere { get; set; }
        public string ril_perdita_risolta { get; set; }
        public string ril_consumo_extra { get; set; }
        public string ril_motivo_consumo_extra { get; set; }
        public Nullable<decimal> ril_nuovo_contatore_censito { get; set; }
        public string ril_flag_cambio_contatore { get; set; }
        public Nullable<decimal> ril_lettura_nuovo_contatore { get; set; }
        public Nullable<System.DateTime> ril_data_lettura_nuovo_contatore { get; set; }
        public string ril_contatore_singolo_generale { get; set; }
        public string ril_contatore_num_lancetta { get; set; }
        public string ril_tipo_contatore { get; set; }
        public string ril_contatore_diametro { get; set; }
        public string ril_contator_num_cifre_quadrante { get; set; }
        public string ril_flag_interventi { get; set; }
        public string ril_flag_nuovo_contatore_censito { get; set; }
        public string ril_matricola_nuovo_contatore { get; set; }
        public string ril_var_flag_toponimo { get; set; }
        public string ril_var_nuova_denom_toponimo { get; set; }
        public Nullable<int> id_causale_intervento_richiesto { get; set; }
        public string flag_urgenza_intervento { get; set; }
        public string flag_rilascio_modulo_autolettura { get; set; }
        public string flag_autolettura_comunicata { get; set; }
        public Nullable<System.DateTime> data_rilascio_modulo_autolettura { get; set; }
        public Nullable<int> ora_min_rilascio_modulo_autolettura { get; set; }
        public string nominativo_firmatario_ricevuta { get; set; }
        public Nullable<int> num_foto_scattate { get; set; }
        public string descrizione_tipo_lettura { get; set; }
        public string note_accessibilita { get; set; }
        public string causale_intervento { get; set; }
        public Nullable<int> id_intervento_generato { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public Nullable<System.DateTime> data_stato { get; set; }
        public Nullable<int> id_struttura_stato { get; set; }
        public Nullable<int> id_risorsa_stato { get; set; }
        public string flag_prelavorazione { get; set; }
    
        ///<summary><para>Relazione: FK_tab_rilevazione_acquedotto_smart_tab_aree</para> Chiave Origine: id_area</summary>
     public virtual tab_aree tab_aree { get; set; }
        ///<summary><para>Relazione: FK_tab_rilevazione_acquedotto_smart_tab_rilevatore</para> Chiave Origine: id_rilevatore</summary>
     public virtual tab_rilevatore tab_rilevatore { get; set; }
        ///<summary><para>Relazione: FK_tab_rilevazione_acquedotto_smart_tab_rilevazione_acquedotto</para> Chiave Origine: id_tab_rilevazione_acquedotto</summary>
     public virtual tab_rilevazione_acquedotto tab_rilevazione_acquedotto { get; set; }
        ///<summary><para>Relazione: FK_tab_rilevazione_acquedotto_smart_tab_rilevazione_acquedotto_dettaglio</para> Chiave Origine: id_tab_rilevazione_acquedotto_dettaglio</summary>
     public virtual tab_rilevazione_acquedotto_dettaglio tab_rilevazione_acquedotto_dettaglio { get; set; }
        ///<summary><para>Relazione: FK_tab_rilevazione_acquedotto_smart_tab_tipo_toponimo</para> Chiave Origine: id_tipo_toponimo</summary>
     public virtual tab_tipo_toponimo tab_tipo_toponimo { get; set; }
        ///<summary><para>Relazione: FK_tab_rilevazione_acquedotto_smart_tab_toponimi</para> Chiave Origine: id_toponimo</summary>
     public virtual tab_toponimi tab_toponimi { get; set; }
        ///<summary><para>Relazione: FK_tab_rilevazione_acquedotto_smart_tab_zone</para> Chiave Origine: id_zona</summary>
     public virtual tab_zone tab_zone { get; set; }
        ///<summary><para>Relazione: FK_tab_rilevazione_acquedotto_smart_anagrafica_ente_gestito</para> Chiave Origine: id_ente_gestito</summary>
     public virtual anagrafica_ente_gestito anagrafica_ente_gestito { get; set; }
        ///<summary><para>Relazione: FK_tab_rilevazione_acquedotto_smart_tab_liste</para> Chiave Origine: id_lista</summary>
     public virtual tab_liste tab_liste { get; set; }
        ///<summary><para>Relazione: FK_tab_rilevazione_acquedotto_smart_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
    }
}
