//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_modalita_spednot_doc_output
    {
        public int id_tab_modalita_spednot_doc_output { get; set; }
        public Nullable<int> id_ente { get; set; }
        public Nullable<int> id_tipo_doc_entrate { get; set; }
        public string flag_estero { get; set; }
        public Nullable<int> id_anagrafica_tipo_spedizione { get; set; }
        public Nullable<System.DateTime> data_inizio_validita { get; set; }
        public Nullable<System.DateTime> data_fine_validita { get; set; }
        public Nullable<int> num_gg_scadenza { get; set; }
        public Nullable<int> id_risorsa_firma { get; set; }
    
        ///<summary><para>Relazione: FK_tab_modalita_spednot_doc_output_anagrafica_tipo_spedizione_notifica</para> Chiave Origine: id_anagrafica_tipo_spedizione</summary>
     public virtual anagrafica_tipo_spedizione_notifica anagrafica_tipo_spedizione_notifica { get; set; }
        ///<summary><para>Relazione: FK_tab_modalita_spednot_doc_output_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrate</summary>
     public virtual tab_tipo_doc_entrate tab_tipo_doc_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_modalita_spednot_doc_output_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
        ///<summary><para>Relazione: FK_tab_modalita_spednot_doc_output_anagrafica_risorse</para> Chiave Origine: id_risorsa_firma</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
    }
}
