//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_tassonomia_pagopa
    {
        public int Id_tassonomia { get; set; }
        public Nullable<int> Id_tipo_ente { get; set; }
        public Nullable<int> Id_entrata { get; set; }
        public string Codice_tassonomia_pagopa { get; set; }
        public Nullable<System.DateTime> Data_inizio_validita { get; set; }
        public Nullable<System.DateTime> Data_fine_validita { get; set; }
    }
}
