//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_lista_letture
    {
        public tab_lista_letture()
        {
            this.tab_rilevazione_acquedotto = new HashSet<tab_rilevazione_acquedotto>();
            this.tab_assegnazione_rilevazioni = new HashSet<tab_assegnazione_rilevazioni>();
            this.tab_letture = new HashSet<tab_letture>();
        }
    
        public int id_lista { get; set; }
        public int id_ente { get; set; }
        public Nullable<int> id_ente_gestito { get; set; }
        public int id_entrata { get; set; }
        public int id_tipo_lista { get; set; }
        public int anno_lista { get; set; }
        public string numero_lista { get; set; }
        public System.DateTime data_lista { get; set; }
        public string desc_aggiuntiva_lista { get; set; }
        public Nullable<int> id_scadenza { get; set; }
        public decimal num_letture_da_effettuare { get; set; }
        public decimal num_letture_effettuate { get; set; }
        public int id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
    
        ///<summary><para>Relazione: FK_tab_lista_letture_anagrafica_entrate</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_lista_letture_tab_tipo_lista</para> Chiave Origine: id_tipo_lista</summary>
     public virtual tab_tipo_lista tab_tipo_lista { get; set; }
        ///<summary><para>Relazione: FK_tab_rilevazione_acquedotto_tab_lista_letture</para> Chiave Origine: id_lista</summary>
     public virtual ICollection<tab_rilevazione_acquedotto> tab_rilevazione_acquedotto { get; set; }
        ///<summary><para>Relazione: FK_tab_assegnazione_rilevazioni_tab_lista_letture</para> Chiave Origine: id_lista_letture</summary>
     public virtual ICollection<tab_assegnazione_rilevazioni> tab_assegnazione_rilevazioni { get; set; }
        ///<summary><para>Relazione: FK_tab_lista_letture_anagrafica_ente_gestito</para> Chiave Origine: id_ente_gestito</summary>
     public virtual anagrafica_ente_gestito anagrafica_ente_gestito { get; set; }
        ///<summary><para>Relazione: FK_tab_letture_tab_lista_letture</para> Chiave Origine: id_lista_rilevazione</summary>
     public virtual ICollection<tab_letture> tab_letture { get; set; }
        ///<summary><para>Relazione: FK_tab_lista_letture_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
    }
}
