//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_controlli_qualita_liste_carico
    {
        public int id_tab_controlli_qualita_liste_carico { get; set; }
        public int id_ente { get; set; }
        public int id_lista { get; set; }
        public int id_anagrafica_controllo { get; set; }
        public Nullable<int> num_avvpag_controllati { get; set; }
        public Nullable<int> num_avvpag_annullati { get; set; }
        public Nullable<decimal> imp_avvpag_annullati { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public Nullable<decimal> imp_avvpag_controllati { get; set; }
    
        ///<summary><para>Relazione: FK_tab_controlli_qualita_liste_carico_anagrafica_cod_stato_base</para> Chiave Origine: cod_stato</summary>
     public virtual anagrafica_cod_stato_base anagrafica_cod_stato_base { get; set; }
        ///<summary><para>Relazione: FK_tab_controlli_qualita_liste_carico_anagrafica_controlli_qualita_emissione_avvpag</para> Chiave Origine: id_anagrafica_controllo</summary>
     public virtual anagrafica_controlli_qualita_emissione_avvpag anagrafica_controlli_qualita_emissione_avvpag { get; set; }
        ///<summary><para>Relazione: FK_tab_controlli_qualita_liste_carico_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_controlli_qualita_liste_carico_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_tab_controlli_qualita_liste_carico_tab_liste</para> Chiave Origine: id_lista</summary>
     public virtual tab_liste tab_liste { get; set; }
    }
}
