//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_contribuzione
    {
        public int id_tab_contribuzione { get; set; }
        public int id_ente { get; set; }
        public int id_ente_gestito { get; set; }
        public int id_entrata { get; set; }
        public decimal id_contribuente { get; set; }
        public int id_avv_pag { get; set; }
        public Nullable<int> id_avv_pag_iniziale { get; set; }
        public Nullable<int> id_avv_pag_collegato { get; set; }
        public Nullable<int> id_avv_pag_intermedio { get; set; }
        public string anno_rif { get; set; }
        public int id_tipo_voce_contribuzione { get; set; }
        public string flag_fonte { get; set; }
        public Nullable<int> priorita_pagamento { get; set; }
        public decimal aliquota_iva { get; set; }
        public decimal importo_residuo { get; set; }
        public decimal importo_pagato { get; set; }
        public decimal importo_da_pagare { get; set; }
        public decimal importo_ridotto { get; set; }
        public string flag_segno { get; set; }
        public int id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public Nullable<int> id_avv_pag_intermedio_1 { get; set; }
        public Nullable<int> id_avv_pag_intermedio_2 { get; set; }
        public Nullable<int> id_avv_pag_intermedio_3 { get; set; }
        public Nullable<int> id_avv_pag_intermedio_4 { get; set; }
        public Nullable<int> id_avv_pag_intermedio_5 { get; set; }
        public Nullable<int> anno_origine { get; set; }
        public Nullable<int> priorita_pagamento_true { get; set; }
        public string numero_accertamento_contabile { get; set; }
        public Nullable<System.DateTime> data_accertamento_contabile { get; set; }
        public Nullable<int> id_tipo_avvpag_origine { get; set; }
        public string descr_tipo_avvpag_origine { get; set; }
        public string identificativo_avvpag_origine { get; set; }
        public Nullable<System.DateTime> data_notifica_avvpag_origine { get; set; }
        public Nullable<System.DateTime> periodo_inizio_contribuzione { get; set; }
        public Nullable<System.DateTime> periodo_fine_contribuzione { get; set; }
        public Nullable<int> id_avv_pag_riferimento_voce { get; set; }
        public Nullable<int> id_unita_contribuzione_riferimento { get; set; }
        public Nullable<int> id_tipo_avv_pag_riscosso { get; set; }
        public Nullable<int> id_tipo_avv_pag_iniziale { get; set; }
        public Nullable<int> id_tipo_avv_pag_collegato { get; set; }
        public Nullable<int> id_tipo_avv_pag_intermedio { get; set; }
        public string flag_doppio_aggio_avv_pag_riscosso { get; set; }
        public string flag_doppio_aggio_avv_pag_iniziale { get; set; }
        public string flag_doppio_aggio_avv_pag_collegato { get; set; }
        public string flag_doppio_aggio_avv_pag_intermedio { get; set; }
    
        ///<summary><para>Relazione: FK_tab_contribuzione_anagrafica_ente_gestito</para> Chiave Origine: id_ente_gestito</summary>
     public virtual anagrafica_ente_gestito anagrafica_ente_gestito { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_anagrafica_entrate</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_anagrafica_tipo_avv_pag</para> Chiave Origine: id_tipo_avvpag_origine</summary>
     public virtual anagrafica_tipo_avv_pag anagrafica_tipo_avv_pag { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_anagrafica_tipo_avv_pag1</para> Chiave Origine: id_tipo_avv_pag_riscosso</summary>
     public virtual anagrafica_tipo_avv_pag anagrafica_tipo_avv_pag1 { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_anagrafica_tipo_avv_pag2</para> Chiave Origine: id_tipo_avv_pag_iniziale</summary>
     public virtual anagrafica_tipo_avv_pag anagrafica_tipo_avv_pag2 { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_anagrafica_tipo_avv_pag3</para> Chiave Origine: id_tipo_avv_pag_collegato</summary>
     public virtual anagrafica_tipo_avv_pag anagrafica_tipo_avv_pag3 { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_anagrafica_tipo_avv_pag4</para> Chiave Origine: id_tipo_avv_pag_intermedio</summary>
     public virtual anagrafica_tipo_avv_pag anagrafica_tipo_avv_pag4 { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_tab_avv_pag</para> Chiave Origine: id_avv_pag</summary>
     public virtual tab_avv_pag tab_avv_pag { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_tab_avv_pag1</para> Chiave Origine: id_avv_pag_iniziale</summary>
     public virtual tab_avv_pag tab_avv_pag1 { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_tab_avv_pag2</para> Chiave Origine: id_avv_pag_collegato</summary>
     public virtual tab_avv_pag tab_avv_pag2 { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_tab_avv_pag3</para> Chiave Origine: id_avv_pag_intermedio</summary>
     public virtual tab_avv_pag tab_avv_pag3 { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_tab_avv_pag4</para> Chiave Origine: id_avv_pag_intermedio_1</summary>
     public virtual tab_avv_pag tab_avv_pag4 { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_tab_avv_pag5</para> Chiave Origine: id_avv_pag_intermedio_2</summary>
     public virtual tab_avv_pag tab_avv_pag5 { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_tab_avv_pag6</para> Chiave Origine: id_avv_pag_intermedio_3</summary>
     public virtual tab_avv_pag tab_avv_pag6 { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_tab_avv_pag7</para> Chiave Origine: id_avv_pag_intermedio_4</summary>
     public virtual tab_avv_pag tab_avv_pag7 { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_tab_avv_pag8</para> Chiave Origine: id_avv_pag_intermedio_5</summary>
     public virtual tab_avv_pag tab_avv_pag8 { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_tab_avv_pag9</para> Chiave Origine: id_avv_pag_riferimento_voce</summary>
     public virtual tab_avv_pag tab_avv_pag9 { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_tab_contribuente</para> Chiave Origine: id_contribuente</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_tab_tipo_voce_contribuzione</para> Chiave Origine: id_tipo_voce_contribuzione</summary>
     public virtual tab_tipo_voce_contribuzione tab_tipo_voce_contribuzione { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_tab_unita_riferimento</para> Chiave Origine: id_unita_contribuzione_riferimento</summary>
     public virtual tab_unita_contribuzione tab_unita_contribuzione { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuzione_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
    }
}
