//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_funzioni
    {
        public tab_funzioni()
        {
            this.join_denunce_doc_input = new HashSet<join_denunce_doc_input>();
            this.tab_stru_ris = new HashSet<tab_stru_ris>();
            this.join_causale_doc_new = new HashSet<join_causale_doc_new>();
        }
    
        public int id_funzione { get; set; }
        public string cod_funzione { get; set; }
        public string descr_funzione { get; set; }
        public string tipo_funzione { get; set; }
        public string flag_tipo_input { get; set; }
        public string flag_tipo_output { get; set; }
        public string flag_tipo_operazione { get; set; }
        public string modalita_esecuzione { get; set; }
        public Nullable<int> livello_autorizzazione { get; set; }
        public Nullable<int> id_entrata { get; set; }
        public string flag_di_sequenza { get; set; }
        public Nullable<int> sequenza_attivita { get; set; }
        public Nullable<int> periodicita_attivita { get; set; }
        public string flag_on_off { get; set; }
        public string livellopubblico { get; set; }
        public string url { get; set; }
        public Nullable<int> idrisorsaabilitazioni { get; set; }
    
        ///<summary><para>Relazione: FK_tab_funzioni_anagrafica_entrate</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_funzioni_anagrafica_risorse</para> Chiave Origine: idrisorsaabilitazioni</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_join_denunce_doc_input_tab_funzioni</para> Chiave Origine: id_funzione</summary>
     public virtual ICollection<join_denunce_doc_input> join_denunce_doc_input { get; set; }
        ///<summary><para>Relazione: FK_tab_stru_ris_tab_funzioni</para> Chiave Origine: id_funzione</summary>
     public virtual ICollection<tab_stru_ris> tab_stru_ris { get; set; }
        ///<summary><para>Relazione: FK_join_causale_doc_tab_funzioni</para> Chiave Origine: id_funzione</summary>
     public virtual ICollection<join_causale_doc_new> join_causale_doc_new { get; set; }
    }
}
