//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_tipi_toponimo_catasto
    {
        public tab_tipi_toponimo_catasto()
        {
            this.tab_toponimi_catasto = new HashSet<tab_toponimi_catasto>();
        }
    
        public int id_tab_tipi_toponimo_catasto { get; set; }
        public string tipo_toponimo { get; set; }
    
        ///<summary><para>Relazione: fk_tab_toponimi_catasto_tab_tipi_toponimo_catasto</para> Chiave Origine: id_tab_tipi_toponimo_catasto</summary>
     public virtual ICollection<tab_toponimi_catasto> tab_toponimi_catasto { get; set; }
    }
}
