//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_f24_tipo_r1_regione
    {
        public int id_r1 { get; set; }
        public int id_aa { get; set; }
        public string tipo_record { get; set; }
        public string codice_regione { get; set; }
        public Nullable<System.DateTime> data_ripartizione { get; set; }
        public Nullable<int> progressivo_ripartizione { get; set; }
        public Nullable<System.DateTime> data_bonifico_principale { get; set; }
        public Nullable<int> progressivo_delega { get; set; }
        public Nullable<int> progressivo_riga { get; set; }
        public string codice_fiscale { get; set; }
        public string flag_errore_cf { get; set; }
        public string flag_multiimpianto { get; set; }
        public string codice_ente { get; set; }
        public string cab { get; set; }
        public Nullable<System.DateTime> data_riscossione { get; set; }
        public string codice_divisa { get; set; }
        public string codice_tributo { get; set; }
        public Nullable<int> anno_riferimento { get; set; }
        public string rateazione { get; set; }
        public string flag_errore_tributo { get; set; }
        public string flag_riferimento_tributo { get; set; }
        public string segno_importo_pagamento { get; set; }
        public Nullable<decimal> importo_pagamento { get; set; }
        public string segno_importo_compensazioni { get; set; }
        public Nullable<decimal> importo_compensazioni { get; set; }
        public string denominazione { get; set; }
        public string nome { get; set; }
        public string sesso { get; set; }
        public Nullable<System.DateTime> data_nascita { get; set; }
        public string comune_o_stato_estero { get; set; }
        public string provincia { get; set; }
        public string codice_regione_multimpianto { get; set; }
        public string percentuale_multimpianto_regionale { get; set; }
        public string sigla_provincia { get; set; }
        public string tipo_imposta { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public Nullable<int> id_struttura_stato { get; set; }
        public Nullable<int> id_risorsa_stato { get; set; }
    
        ///<summary><para>Relazione: FK_tab_f24_tipo_r1_regione_tab_f24_tipo_aa_regione</para> Chiave Origine: id_aa</summary>
     public virtual tab_f24_tipo_aa_regione tab_f24_tipo_aa_regione { get; set; }
    }
}
