//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_tipo_pagamento
    {
        public tab_tipo_pagamento()
        {
            this.tab_mov_pag_ici = new HashSet<tab_mov_pag_ici>();
            this.tab_mov_pag_fatt_emissione = new HashSet<tab_mov_pag_fatt_emissione>();
            this.tab_mov_pag = new HashSet<tab_mov_pag>();
        }
    
        public int id_tipo_pag { get; set; }
        public string codice_pag { get; set; }
        public string descrizione_pag { get; set; }
        public Nullable<decimal> importo_massimo { get; set; }
        public Nullable<int> id_anagrafica_tipo_pagamento { get; set; }
    
        ///<summary><para>Relazione: FK_tab_tipo_pagamento_anagrafica_tipo_pagamento</para> Chiave Origine: id_anagrafica_tipo_pagamento</summary>
     public virtual anagrafica_tipo_pagamento anagrafica_tipo_pagamento { get; set; }
        ///<summary><para>Relazione: FK_tab_mov_pag_ici_tab_tipo_pagamento</para> Chiave Origine: id_tipo_pagamento</summary>
     public virtual ICollection<tab_mov_pag_ici> tab_mov_pag_ici { get; set; }
        ///<summary><para>Relazione: FK_tab_mov_pag_fatt_emissione_tab_tipo_pagamento</para> Chiave Origine: id_tipo_pagamento</summary>
     public virtual ICollection<tab_mov_pag_fatt_emissione> tab_mov_pag_fatt_emissione { get; set; }
        ///<summary><para>Relazione: FK_tab_mov_pag_tab_tipo_pagamento</para> Chiave Origine: id_tipo_pagamento</summary>
     public virtual ICollection<tab_mov_pag> tab_mov_pag { get; set; }
    }
}
