//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_lista_sped_notifiche
    {
        public tab_lista_sped_notifiche()
        {
            this.tab_sped_not_fatt_emissione = new HashSet<tab_sped_not_fatt_emissione>();
            this.tab_sped_not_fatt_emissione1 = new HashSet<tab_sped_not_fatt_emissione>();
            this.tab_sped_not_fatt_emissione2 = new HashSet<tab_sped_not_fatt_emissione>();
            this.tab_sped_not = new HashSet<tab_sped_not>();
            this.tab_sped_not1 = new HashSet<tab_sped_not>();
            this.tab_sped_not2 = new HashSet<tab_sped_not>();
            this.tab_dett_lista_sped_not = new HashSet<tab_dett_lista_sped_not>();
            this.tab_ispezione_coattivo = new HashSet<tab_ispezione_coattivo>();
            this.join_lst_emissione_lst_sped_not = new HashSet<join_lst_emissione_lst_sped_not>();
        }
    
        public int id_lista { get; set; }
        public int id_ente { get; set; }
        public Nullable<int> id_entrata { get; set; }
        public int id_tipo_lista { get; set; }
        public int anno { get; set; }
        public string numero_lista { get; set; }
        public Nullable<System.DateTime> data_lista { get; set; }
        public Nullable<System.DateTime> data_spedizione { get; set; }
        public Nullable<int> id_scadenza { get; set; }
        public Nullable<System.DateTime> data_scadenza_prima_rata { get; set; }
        public Nullable<int> id_tipo_avv_pag { get; set; }
        public Nullable<int> id_tipo_doc_entrata { get; set; }
        public string flag_spedizione_notifica { get; set; }
        public string cod_tipo_avv_pag { get; set; }
        public Nullable<decimal> num_sped_not { get; set; }
        public Nullable<decimal> num_sped_not_ok { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public Nullable<int> id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public Nullable<int> id_tipo_spedizione_notifica { get; set; }
    
        ///<summary><para>Relazione: FK_tab_lista_sped_notifiche_anagrafica_entrate</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_lista_sped_notifiche_anagrafica_risorse</para> Chiave Origine: id_risorsa_stato</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_lista_sped_notifiche_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_stato</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_tab_lista_sped_notifiche_anagrafica_tipo_avv_pag</para> Chiave Origine: id_tipo_avv_pag</summary>
     public virtual anagrafica_tipo_avv_pag anagrafica_tipo_avv_pag { get; set; }
        ///<summary><para>Relazione: FK_tab_lista_sped_notifiche_anagrafica_tipo_spedizione_notifica</para> Chiave Origine: id_tipo_spedizione_notifica</summary>
     public virtual anagrafica_tipo_spedizione_notifica anagrafica_tipo_spedizione_notifica { get; set; }
        ///<summary><para>Relazione: FK_tab_lista_sped_notifiche_tab_tipo_lista</para> Chiave Origine: id_tipo_lista</summary>
     public virtual tab_tipo_lista tab_tipo_lista { get; set; }
        ///<summary><para>Relazione: FK_tab_sped_not_fatt_emissione_tab_lista_sped_notifiche</para> Chiave Origine: id_lista_sped_not</summary>
     public virtual ICollection<tab_sped_not_fatt_emissione> tab_sped_not_fatt_emissione { get; set; }
        ///<summary><para>Relazione: FK_tab_sped_not_fatt_emissione_tab_lista_sped_notifiche1</para> Chiave Origine: id_lista_affissione_ap</summary>
     public virtual ICollection<tab_sped_not_fatt_emissione> tab_sped_not_fatt_emissione1 { get; set; }
        ///<summary><para>Relazione: FK_tab_sped_not_fatt_emissione_tab_lista_sped_notifiche2</para> Chiave Origine: id_lista_invio_avvdep</summary>
     public virtual ICollection<tab_sped_not_fatt_emissione> tab_sped_not_fatt_emissione2 { get; set; }
        ///<summary><para>Relazione: FK_tab_sped_not_tab_lista_sped_notifiche</para> Chiave Origine: id_lista_sped_not</summary>
     public virtual ICollection<tab_sped_not> tab_sped_not { get; set; }
        ///<summary><para>Relazione: FK_tab_sped_not_tab_lista_sped_notifiche1</para> Chiave Origine: id_lista_affissione_ap</summary>
     public virtual ICollection<tab_sped_not> tab_sped_not1 { get; set; }
        ///<summary><para>Relazione: FK_tab_sped_not_tab_lista_sped_notifiche2</para> Chiave Origine: id_lista_invio_avvdep</summary>
     public virtual ICollection<tab_sped_not> tab_sped_not2 { get; set; }
        ///<summary><para>Relazione: FK_tab_dett_lista_sped_not_tab_lista_sped_notifiche</para> Chiave Origine: id_lista_sped_not</summary>
     public virtual ICollection<tab_dett_lista_sped_not> tab_dett_lista_sped_not { get; set; }
        ///<summary><para>Relazione: FK_tab_ispezione_coattivo_tab_lista_sped_notifiche</para> Chiave Origine: id_lista_ispezione</summary>
     public virtual ICollection<tab_ispezione_coattivo> tab_ispezione_coattivo { get; set; }
        ///<summary><para>Relazione: FK_tab_lista_sped_notifiche_tab_tipo_doc_entrate</para> Chiave Origine: id_tipo_doc_entrata</summary>
     public virtual tab_tipo_doc_entrate tab_tipo_doc_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_lista_sped_notifiche_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
        ///<summary><para>Relazione: FK_join_lst_emissione_lst_sped_not_tab_lista_sped_notifiche1</para> Chiave Origine: id_lista_sped_not</summary>
     public virtual ICollection<join_lst_emissione_lst_sped_not> join_lst_emissione_lst_sped_not { get; set; }
    }
}
