//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_contribuente_sto
    {
        public decimal id_anag_contribuente_sto { get; set; }
        public decimal id_anag_contribuente { get; set; }
        public int id_ente { get; set; }
        public int id_ente_gestito { get; set; }
        public int id_entrata { get; set; }
        public string cod_fonte { get; set; }
        public string tri_ana_utente { get; set; }
        public string rag_sociale { get; set; }
        public string denominazione_commerciale { get; set; }
        public string cognome { get; set; }
        public string nome { get; set; }
        public string c_a { get; set; }
        public string id_stato_contribuente { get; set; }
        public string cod_stato_contribuente { get; set; }
        public string data_inizio_stato { get; set; }
        public string data_fine_stato { get; set; }
        public string id_tipo_contribuente { get; set; }
        public string id_nucleo_familiare { get; set; }
        public string id_anagrafe_comunale { get; set; }
        public string num_scheda_anagrafe_comunale { get; set; }
        public string cod_fiscale { get; set; }
        public string p_iva { get; set; }
        public string stato_nas { get; set; }
        public string comune_nas { get; set; }
        public string cod_comune_nas { get; set; }
        public string data_nas { get; set; }
        public string data_morte { get; set; }
        public string id_sesso { get; set; }
        public string id_toponimo { get; set; }
        public string indirizzo { get; set; }
        public string edificio { get; set; }
        public string nr_civico { get; set; }
        public string sigla_civico { get; set; }
        public string scala { get; set; }
        public string piano { get; set; }
        public string interno { get; set; }
        public string condominio { get; set; }
        public string frazione { get; set; }
        public string stato { get; set; }
        public string citta { get; set; }
        public string cod_citta { get; set; }
        public string cap { get; set; }
        public string prov { get; set; }
        public string indirizzo_ar { get; set; }
        public string id_contribuente_dom { get; set; }
        public string cognome_dom { get; set; }
        public string nome_dom { get; set; }
        public string rag_sociale_dom { get; set; }
        public string cod_fiscale_dom { get; set; }
        public string p_iva_dom { get; set; }
        public string casella_postale_dom { get; set; }
        public string c_a_dom { get; set; }
        public string id_toponimo_dom { get; set; }
        public string indirizzo_dom { get; set; }
        public string edificio_dom { get; set; }
        public string nr_civico_dom { get; set; }
        public string sigla_civico_dom { get; set; }
        public string scala_dom { get; set; }
        public string piano_dom { get; set; }
        public string interno_dom { get; set; }
        public string condominio_dom { get; set; }
        public string frazione_dom { get; set; }
        public string stato_dom { get; set; }
        public string citta_dom { get; set; }
        public string cod_citta_dom { get; set; }
        public string cap_dom { get; set; }
        public string prov_dom { get; set; }
        public string id_tipo_dom { get; set; }
        public string ccia { get; set; }
        public string flag_web { get; set; }
        public string e_mail { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string id_contribuente_ref { get; set; }
        public string nome_ref { get; set; }
        public string cognome_ref { get; set; }
        public string cod_fiscale_ref { get; set; }
        public string id_tipo_relazione_ref { get; set; }
        public string c_a_ref { get; set; }
        public string id_toponimo_ref { get; set; }
        public string indirizzo_ref { get; set; }
        public string edificio_ref { get; set; }
        public string nr_civico_ref { get; set; }
        public string sigla_civico_ref { get; set; }
        public string scala_ref { get; set; }
        public string piano_ref { get; set; }
        public string interno_ref { get; set; }
        public string condominio_ref { get; set; }
        public string frazione_ref { get; set; }
        public string stato_ref { get; set; }
        public string citta_ref { get; set; }
        public string cod_citta_ref { get; set; }
        public string cap_ref { get; set; }
        public string prov_ref { get; set; }
        public string note { get; set; }
        public string id_risorsa { get; set; }
        public string data_aggiornamento { get; set; }
        public string flag_aggiornamento { get; set; }
        public string data_inizio_val { get; set; }
        public string data_fine_val { get; set; }
        public string flag_verifica_dati { get; set; }
        public string flag_on_off { get; set; }
        public Nullable<System.DateTime> data_stato { get; set; }
        public Nullable<int> id_struttura_stato { get; set; }
        public Nullable<int> id_risorsa_stato { get; set; }
        public Nullable<int> id_toponimo_normalizzato { get; set; }
    
        ///<summary><para>Relazione: FK_tab_contribuente_sto_anagrafica_ente_gestito</para> Chiave Origine: id_ente_gestito</summary>
     public virtual anagrafica_ente_gestito anagrafica_ente_gestito { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuente_sto_tab_contribuente</para> Chiave Origine: id_anag_contribuente</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
        ///<summary><para>Relazione: FK_tab_contribuente_sto_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
    }
}
