//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_f24_g1
    {
        public int id_g1 { get; set; }
        public int id_tab_f24_a1 { get; set; }
        public Nullable<int> id_tab_mov_pag { get; set; }
        public string tipo_record { get; set; }
        public Nullable<System.DateTime> data_fornitura { get; set; }
        public Nullable<int> progressivo_fornitura { get; set; }
        public Nullable<System.DateTime> data_ripartizione { get; set; }
        public Nullable<int> progressivo_ripartizione { get; set; }
        public Nullable<System.DateTime> data_bonifico { get; set; }
        public Nullable<int> progressivo_delega { get; set; }
        public Nullable<int> progressivo_riga { get; set; }
        public string codice_ente { get; set; }
        public string tipo_ente { get; set; }
        public string cab { get; set; }
        public string codice_fiscale { get; set; }
        public string flag_errore_cf { get; set; }
        public Nullable<System.DateTime> data_riscossione { get; set; }
        public string codice_ente_comunale { get; set; }
        public string codice_tributo { get; set; }
        public string flag_errore_ct { get; set; }
        public Nullable<int> rateazione { get; set; }
        public Nullable<int> anno_riferimento { get; set; }
        public string flag_errato_anno { get; set; }
        public string codice_valuta { get; set; }
        public Nullable<decimal> importo_a_debito { get; set; }
        public Nullable<decimal> importo_a_credito { get; set; }
        public string ravvedimento_ici { get; set; }
        public string immobili_variabili_ici { get; set; }
        public string acconto_ici { get; set; }
        public string saldo_ici { get; set; }
        public Nullable<int> numero_fabbricati_ici { get; set; }
        public string flag_errati_dati_ici { get; set; }
        public Nullable<decimal> detrazione_ab_principale { get; set; }
        public string denominazione { get; set; }
        public string nome { get; set; }
        public string sesso { get; set; }
        public Nullable<System.DateTime> data_nascita { get; set; }
        public string comune_stato_estero { get; set; }
        public string provincia { get; set; }
        public string tipo_imposta { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public Nullable<System.DateTime> data_stato { get; set; }
        public Nullable<int> id_struttura_stato { get; set; }
        public Nullable<int> id_risorsa_stato { get; set; }
        public string secondo_codice_fiscale { get; set; }
        public string cod_identificativo_secondo_codice_fiscale { get; set; }
        public string identificativo_operazione { get; set; }
    
        ///<summary><para>Relazione: FK_tab_f24_g1_tab_f24_a1</para> Chiave Origine: id_tab_f24_a1</summary>
     public virtual tab_f24_a1 tab_f24_a1 { get; set; }
        ///<summary><para>Relazione: FK_tab_f24_g1_tab_mov_pag</para> Chiave Origine: id_tab_mov_pag</summary>
     public virtual tab_mov_pag tab_mov_pag { get; set; }
    }
}
