//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_agevolazioni_verifica
    {
        public tab_agevolazioni_verifica()
        {
            this.join_documenti_pratiche = new HashSet<join_documenti_pratiche>();
        }
    
        public int id_tab_agevolazioni_verifica { get; set; }
        public string tipo_operazione { get; set; }
        public Nullable<int> id_pratica { get; set; }
        public Nullable<int> anno_pratica { get; set; }
        public Nullable<int> numero_pratica { get; set; }
        public string codice_pratica { get; set; }
        public Nullable<int> id_join_avv_pag_doc_input { get; set; }
        public Nullable<int> id_unita_contribuzione { get; set; }
        public Nullable<int> id_causale_operazione { get; set; }
        public Nullable<decimal> id_contribuente { get; set; }
        public Nullable<decimal> id_oggetto { get; set; }
        public Nullable<decimal> id_oggetto_contribuzione { get; set; }
        public Nullable<int> id_tab_agevolazioni { get; set; }
        public Nullable<int> id_entrata { get; set; }
        public Nullable<int> id_anagrafica_agevolazione { get; set; }
        public Nullable<int> quantita_agevolazione { get; set; }
        public Nullable<System.DateTime> data_inizio_validita { get; set; }
        public Nullable<System.DateTime> data_fine_validita { get; set; }
        public Nullable<int> id_stato { get; set; }
        public string cod_stato { get; set; }
        public Nullable<System.DateTime> data_stato { get; set; }
        public Nullable<int> id_struttura_stato { get; set; }
        public Nullable<int> id_risorsa_stato { get; set; }
    
        ///<summary><para>Relazione: FK_tab_agevolazioni_verifica_anagrafica_agevolazione</para> Chiave Origine: id_anagrafica_agevolazione</summary>
     public virtual anagrafica_agevolazione anagrafica_agevolazione { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_verifica_anagrafica_causale</para> Chiave Origine: id_causale_operazione</summary>
     public virtual anagrafica_causale anagrafica_causale { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_verifica_anagrafica_entrate</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_verifica_anagrafica_stato_agevolazione</para> Chiave Origine: id_stato</summary>
     public virtual anagrafica_stato_agevolazione anagrafica_stato_agevolazione { get; set; }
        ///<summary><para>Relazione: FK_join_documenti_pratiche_tab_agevolazioni_verifica</para> Chiave Origine: id_agevolazioni_verifica</summary>
     public virtual ICollection<join_documenti_pratiche> join_documenti_pratiche { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_verifica_tab_contribuente</para> Chiave Origine: id_contribuente</summary>
     public virtual tab_contribuente tab_contribuente { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_verifica_tab_doc_input</para> Chiave Origine: id_pratica</summary>
     public virtual tab_doc_input tab_doc_input { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_verifica_tab_oggetti</para> Chiave Origine: id_oggetto</summary>
     public virtual tab_oggetti tab_oggetti { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_verifica_tab_oggetti_contribuzione</para> Chiave Origine: id_oggetto_contribuzione</summary>
     public virtual tab_oggetti_contribuzione tab_oggetti_contribuzione { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_verifica_tab_agevolazioni</para> Chiave Origine: id_tab_agevolazioni</summary>
     public virtual tab_agevolazioni tab_agevolazioni { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_verifica_join_tab_avv_pag_tab_doc_input</para> Chiave Origine: id_join_avv_pag_doc_input</summary>
     public virtual join_tab_avv_pag_tab_doc_input join_tab_avv_pag_tab_doc_input { get; set; }
        ///<summary><para>Relazione: FK_tab_agevolazioni_verifica_tab_unita_contribuzione</para> Chiave Origine: id_unita_contribuzione</summary>
     public virtual tab_unita_contribuzione tab_unita_contribuzione { get; set; }
    }
}
