//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_log_operatori
    {
        public tab_log_operatori()
        {
            this.tab_log_utenti = new HashSet<tab_log_utenti>();
            this.tab_log_operazioni_operatore = new HashSet<tab_log_operazioni_operatore>();
        }
    
        public int id_log_operatori { get; set; }
        public int id_struttura_aziendale { get; set; }
        public int id_risorsa { get; set; }
        public string modalita_operativa { get; set; }
        public System.DateTime inizio_attivita { get; set; }
        public Nullable<System.DateTime> fine_attivita { get; set; }
        public Nullable<int> id_ente { get; set; }
    
        ///<summary><para>Relazione: FK_tab_log_operatori_anagrafica_risorse</para> Chiave Origine: id_risorsa</summary>
     public virtual anagrafica_risorse anagrafica_risorse { get; set; }
        ///<summary><para>Relazione: FK_tab_log_operatori_anagrafica_strutture_aziendali</para> Chiave Origine: id_struttura_aziendale</summary>
     public virtual anagrafica_strutture_aziendali anagrafica_strutture_aziendali { get; set; }
        ///<summary><para>Relazione: FK_tab_log_utenti_tab_log_operatori</para> Chiave Origine: id_log_operatori</summary>
     public virtual ICollection<tab_log_utenti> tab_log_utenti { get; set; }
        ///<summary><para>Relazione: FK_tab_log_operazioni_operatore_tab_log_operatori</para> Chiave Origine: id_log_operatori</summary>
     public virtual ICollection<tab_log_operazioni_operatore> tab_log_operazioni_operatore { get; set; }
    }
}
