//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_cuas
    {
        public tab_cuas()
        {
            this.tab_mov_pag_fatt_emissione = new HashSet<tab_mov_pag_fatt_emissione>();
            this.join_doc_input_pag_avvpag = new HashSet<join_doc_input_pag_avvpag>();
        }
    
        public int id_cuas { get; set; }
        public string sigla_citta { get; set; }
        public string nome_citta { get; set; }
    
        ///<summary><para>Relazione: FK_tab_mov_pag_fatt_emissione_tab_cuas</para> Chiave Origine: id_cuas</summary>
     public virtual ICollection<tab_mov_pag_fatt_emissione> tab_mov_pag_fatt_emissione { get; set; }
        ///<summary><para>Relazione: FK_join_doc_input_pag_avvpag_tab_cuas</para> Chiave Origine: id_cuas</summary>
     public virtual ICollection<join_doc_input_pag_avvpag> join_doc_input_pag_avvpag { get; set; }
    }
}
