//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_voci_contrattuali_NEW
    {
        public tab_voci_contrattuali_NEW()
        {
            this.tab_riversamenti_contrattuali = new HashSet<tab_riversamenti_contrattuali>();
        }
    
        public int id_voce_contrattuale { get; set; }
        public Nullable<int> id_ente { get; set; }
        public Nullable<int> id_contratto { get; set; }
        public Nullable<int> id_entrata { get; set; }
        public Nullable<int> id_servizio { get; set; }
        public string descr_voce_contrattuale { get; set; }
        public Nullable<int> Anno_rif_da { get; set; }
        public Nullable<int> Anno_rif_a { get; set; }
        public string flag_modalita_calcolo_corrispettivo { get; set; }
        public Nullable<decimal> aggio { get; set; }
        public Nullable<decimal> importo_unitario { get; set; }
        public string flag_iva { get; set; }
        public Nullable<decimal> aliquota_iva { get; set; }
        public string descr_iva { get; set; }
        public Nullable<System.DateTime> data_dec_corrispettivo { get; set; }
        public Nullable<System.DateTime> data_scadenza_corrispettivo { get; set; }
        public Nullable<decimal> minimo_garantito { get; set; }
        public Nullable<System.DateTime> data_conguaglio_minimo_garantito { get; set; }
        public Nullable<System.DateTime> data_ultimo_conguaglio_minimo_garantito { get; set; }
        public Nullable<int> Anno_rif_ultimo_conguaglio_minimo_garantito { get; set; }
        public string flag_modalita_pagamento { get; set; }
        public Nullable<int> scadenza_gg_recupero_credito { get; set; }
        public Nullable<int> scadenza_gg_datafattura { get; set; }
        public int id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
        public string flag_AggioRiscoCoattiva { get; set; }
        public Nullable<decimal> Aggio_RiscoCoattiva { get; set; }
        public string flag_AggioAccOmVersamento { get; set; }
        public Nullable<decimal> Aggio_AccOmVersamento { get; set; }
        public string flag_AggioInteressiMora { get; set; }
        public Nullable<decimal> Aggio_InteressiMora { get; set; }
        public string flag_AggioInteressiLeg { get; set; }
        public Nullable<decimal> Aggio_InteressiLeg { get; set; }
        public string flag_AggioSanzioni { get; set; }
        public Nullable<decimal> Aggio_Sanzioni { get; set; }
        public Nullable<decimal> Importo_Base_Calcolo { get; set; }
        public Nullable<decimal> Importo_Corpo { get; set; }
        public Nullable<int> id_ente_gestito { get; set; }
        public string flag_ente_accredito_corr { get; set; }
        public string flag_ente_addebito_corr { get; set; }
        public Nullable<int> id_ente_accredito_corr { get; set; }
        public Nullable<int> id_ente_addebito_corr { get; set; }
        public string tipo_scadenza_pagamento { get; set; }
        public string tipo_recupero { get; set; }
        public string fonte_avvpag_aggio { get; set; }
        public Nullable<int> id_anagrafica_voce { get; set; }
        public string NUMERO_CONTO_CONTABILE_RICAVI { get; set; }
        public string NUMERO_CONTO_CONTABILE_FATT_DA_EMETTERE { get; set; }
        public string NUMERO_CONTO_CONTABILE_IVA { get; set; }
        public string tipo_voce_ricavo { get; set; }
        public Nullable<int> id_voce_budget { get; set; }
        public string tipo_credito { get; set; }
        public string cod_coll { get; set; }
    
        ///<summary><para>Relazione: FK_tab_voci_contrattuali_NEW_anagrafica_entrate</para> Chiave Origine: id_entrata</summary>
     public virtual anagrafica_entrate anagrafica_entrate { get; set; }
        ///<summary><para>Relazione: FK_tab_voci_contrattuali_NEW_anagrafica_servizi</para> Chiave Origine: id_servizio</summary>
     public virtual anagrafica_servizi anagrafica_servizi { get; set; }
        ///<summary><para>Relazione: FK_tab_voci_contrattuali_NEW_tab_voci_contrattuali_NEW</para> Chiave Origine: id_contratto</summary>
     public virtual tab_contratti_NEW tab_contratti_NEW { get; set; }
        ///<summary><para>Relazione: FK_tab_riversamenti_contrattuali_tab_voci_contrattuali_NEW</para> Chiave Origine: id_voce_contrattuale</summary>
     public virtual ICollection<tab_riversamenti_contrattuali> tab_riversamenti_contrattuali { get; set; }
        ///<summary><para>Relazione: FK_tab_voci_contrattuali_NEW_anagrafica_ente</para> Chiave Origine: id_ente</summary>
     public virtual anagrafica_ente anagrafica_ente { get; set; }
    }
}
