//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_contatore
    {
        public tab_contatore()
        {
            this.join_ogg_contatore = new HashSet<join_ogg_contatore>();
            this.tab_letture = new HashSet<tab_letture>();
            this.tab_rilevazione_acquedotto_dettaglio = new HashSet<tab_rilevazione_acquedotto_dettaglio>();
            this.tab_fatt_cont = new HashSet<tab_fatt_cont>();
            this.tab_fatt_info = new HashSet<tab_fatt_info>();
        }
    
        public int id_contatore { get; set; }
        public Nullable<int> id_tipo_contatore { get; set; }
        public string flag_num_lancetta { get; set; }
        public string matricola { get; set; }
        public Nullable<int> numero_cifre_lancette { get; set; }
        public string numero_sigillo { get; set; }
        public Nullable<System.DateTime> data_istallazione_presa_incarico { get; set; }
        public Nullable<decimal> lettura_iniziale { get; set; }
        public Nullable<System.DateTime> data_cessazione { get; set; }
        public Nullable<decimal> lettura_finale { get; set; }
        public string flag_singolo_generale { get; set; }
        public string flag_istallazione { get; set; }
        public string flag_autoclave { get; set; }
        public string flag_ubicazione { get; set; }
        public string descr_ubicazione { get; set; }
        public Nullable<System.DateTime> data_penultima_lettura { get; set; }
        public Nullable<decimal> penultima_lettura { get; set; }
        public Nullable<System.DateTime> data_ultima_lettura { get; set; }
        public Nullable<decimal> ultima_lettura { get; set; }
        public Nullable<decimal> num_giorni_ultimo_addebito { get; set; }
        public Nullable<decimal> qta_ultimo_addebito { get; set; }
        public Nullable<decimal> prodie_ultimo_addebito { get; set; }
        public Nullable<decimal> num_giorni_totali { get; set; }
        public Nullable<decimal> qta_totale { get; set; }
        public Nullable<decimal> prodie_totale { get; set; }
        public int id_stato { get; set; }
        public string cod_stato { get; set; }
        public System.DateTime data_stato { get; set; }
        public int id_struttura_stato { get; set; }
        public int id_risorsa_stato { get; set; }
    
        ///<summary><para>Relazione: FK_tab_contatore_anagrafica_stato_contatore</para> Chiave Origine: id_stato</summary>
     public virtual anagrafica_stato_contatore anagrafica_stato_contatore { get; set; }
        ///<summary><para>Relazione: FK_join_ogg_contatore_tab_contatore</para> Chiave Origine: id_contatore</summary>
     public virtual ICollection<join_ogg_contatore> join_ogg_contatore { get; set; }
        ///<summary><para>Relazione: FK_tab_contatore_tab_tipo_contatore</para> Chiave Origine: id_tipo_contatore</summary>
     public virtual tab_tipo_contatore tab_tipo_contatore { get; set; }
        ///<summary><para>Relazione: FK_tab_letture_tab_contatore</para> Chiave Origine: id_contatore</summary>
     public virtual ICollection<tab_letture> tab_letture { get; set; }
        ///<summary><para>Relazione: FK_tab_rilevazione_acquedotto_dettaglio_tab_contatore</para> Chiave Origine: id_contatore</summary>
     public virtual ICollection<tab_rilevazione_acquedotto_dettaglio> tab_rilevazione_acquedotto_dettaglio { get; set; }
        ///<summary><para>Relazione: FK_tab_fatt_cont_tab_contatore</para> Chiave Origine: id_contatore</summary>
     public virtual ICollection<tab_fatt_cont> tab_fatt_cont { get; set; }
        ///<summary><para>Relazione: FK_tab_fatt_info_tab_contatore</para> Chiave Origine: id_contatore</summary>
     public virtual ICollection<tab_fatt_info> tab_fatt_info { get; set; }
    }
}
