//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publisoftware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_tipo_ente
    {
        public tab_tipo_ente()
        {
            this.anagrafica_ente_gestito = new HashSet<anagrafica_ente_gestito>();
            this.anagrafica_ente = new HashSet<anagrafica_ente>();
        }
    
        public int id_tipo_ente { get; set; }
        public string cod_tipo_ente { get; set; }
        public string desc_tipo_ente { get; set; }
        public string prefisso_codice { get; set; }
    
        ///<summary><para>Relazione: FK_anagrafica_ente_gestito_tab_tipo_ente</para> Chiave Origine: id_tipo_ente</summary>
     public virtual ICollection<anagrafica_ente_gestito> anagrafica_ente_gestito { get; set; }
        ///<summary><para>Relazione: FK_anagrafica_ente_tab_tipo_ente</para> Chiave Origine: id_tipo_ente</summary>
     public virtual ICollection<anagrafica_ente> anagrafica_ente { get; set; }
    }
}
